/*
 * finiteJ_eqs.hpp -- GENERATED by scripts/finiteJ_emit.py.  Do not edit.
 *
 * ⚠ --q-regular: q = sin^2(theta) q~.  The unknown QF DENOTES q~ in this
 * emission (research round 578; code round 279), so q vanishes on the
 * axis by construction.  Build it as finiteJ_probe_qreg only.
 *
 * The six finite-J equations as Kadath defs, emitted from the ASSEMBLY's
 * structure rather than from an expanded expression: where the assembly
 * applied lap2S the emission says lap2, instead of expanding and hoping to
 * recognise it again.
 *
 * Unknowns PS, PH, QF, BR, BT, QB.  Spin constant JJ.  There are NO sin or
 * cos FIELDS: round 103 measured that neither lies in the scalar COS_EVEN
 * span, so an add_cst holding one stores an alias.  Angular and radial
 * factors go through the coefficient-space operators instead, and
 *
 *     cot(theta) * X  ==  divsint(dt(multsint(X))) - dt(X)
 *
 * which the probe verified to 2e-16 on a field vanishing on the axis.
 *
 * Registered as 340 named sub-defs then the six equations: the parser has a
 * STACK-depth limit near 1000 characters that was not reproducible run to
 * run, so every piece here is kept far below it.
 *
 * ⚠ THE READ-STATE CONTRACT (round 108).  Kadath evaluates a sum
 * differently depending on whether its named operands have been READ --
 * indexed, which forces a Val_domain into configuration space -- before
 * the sum is parsed, and a def parsed in the wrong state does not recover
 * when its operands are read later.  Every sub-def below must therefore be
 * read immediately after it is registered.  That is why the def TEXT is not
 * exported: register through finiteJ_register(), which does it, and call
 * finiteJ_check(), which fails loudly if it was not done.  A requirement in
 * prose gets transcribed wrongly; this one is in the only function that can
 * reach the text.
 */
#pragma once

#include "For_Kadath/Array/headcpp.hpp"
#include "For_Kadath/Space/space.hpp"
#include "For_Kadath/System_of_eqs/system_of_eqs.hpp"

#include <algorithm>
#include <cmath>
#include <sstream>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

namespace Trumpet
{
    struct FiniteJEq { const char* name; const char* def; };

    /// One sum, re-expressed.  `reads` are the operands finiteJ_check()
    /// reads before re-parsing `def`, which is what lets it discriminate.
    struct FiniteJCheck {
        const char* name; const char* of; const char* reads; const char* def;
    };

    namespace finiteJ_detail
    {
        /// ⚠ The def TEXT.  Registering any of this by hand skips the read
        /// the evaluator needs; go through finiteJ_register() instead.
        inline const std::vector<FiniteJEq>& subdefs()
        {
            static const std::vector<FiniteJEq> D = {
                {"D0001",
                 "multsint(multsint(QF))"
                },
                {"D0002",
                 "multsint(multsint(multsint(multsint(QB))))"
                },
                {"D0003",
                 "(2 * (D0001))"
                },
                {"D0004",
                 "(1 / (PS))"
                },
                {"D0005",
                 "(1 / (PH))"
                },
                {"D0006",
                 "((1 / 2) * (log(PS)))"
                },
                {"D0007",
                 "dr(log(PH))"
                },
                {"D0008",
                 "dr(log(PS))"
                },
                {"D0009",
                 "(4 * (D0008))"
                },
                {"D0010",
                 "(D0007 - D0009)"
                },
                {"D0011",
                 "dt(log(PH))"
                },
                {"D0012",
                 "dt(log(PS))"
                },
                {"D0013",
                 "(4 * (D0012))"
                },
                {"D0014",
                 "(D0011 - D0013)"
                },
                {"D0015",
                 "dr(D0001)"
                },
                {"D0016",
                 "(2 * (D0015))"
                },
                {"D0017",
                 "(D0010 - D0016)"
                },
                {"D0018",
                 "dt(D0001)"
                },
                {"D0019",
                 "(2 * (D0018))"
                },
                {"D0020",
                 "(D0014 - D0019)"
                },
                {"D0021",
                 "dr(D0002)"
                },
                {"D0022",
                 "dt(D0002)"
                },
                {"D0023",
                 "(6*JJ * (multsint(multsint(multsint(ones)))))"
                },
                {"D0024",
                 "(D0022 + D0023)"
                },
                {"D0025",
                 "divr(divr(D0024))"
                },
                {"D0026",
                 "(PS * D0005)"
                },
                {"D0027",
                 "(BR * D0021)"
                },
                {"D0028",
                 "(BT * D0024)"
                },
                {"D0029",
                 "(D0027 + D0028)"
                },
                {"D0030",
                 "(D0026 * D0029)"
                },
                {"D0031",
                 "(-1 * (D0030))"
                },
                {"D0032",
                 "(D0031 * D0004)"
                },
                {"D0033",
                 "(-1 * (D0001))"
                },
                {"D0034",
                 "(D0032 * exp(D0033))"
                },
                {"D0035",
                 "dr(D0006)"
                },
                {"D0036",
                 "dt(D0006)"
                },
                {"D0037",
                 "(PS * D0005)"
                },
                {"D0038",
                 "(2 * (D0035))"
                },
                {"D0039",
                 "divr(ones)"
                },
                {"D0040",
                 "(D0038 + D0039)"
                },
                {"D0041",
                 "(BR * D0040)"
                },
                {"D0042",
                 "(2 * (D0036))"
                },
                {"D0043",
                 "(BT * D0042)"
                },
                {"D0044",
                 "(divsint(dt(multsint(BT))) - dt(BT))"
                },
                {"D0045",
                 "D0044"
                },
                {"D0046",
                 "(D0043 + D0045)"
                },
                {"D0047",
                 "(D0041 + D0046)"
                },
                {"D0048",
                 "(D0037 * D0047)"
                },
                {"D0049",
                 "(-1 * (D0048))"
                },
                {"D0050",
                 "dr(BR)"
                },
                {"D0051",
                 "dr(BT)"
                },
                {"D0052",
                 "divr(BT)"
                },
                {"D0053",
                 "(D0051 + D0052)"
                },
                {"D0054",
                 "dt(BR)"
                },
                {"D0055",
                 "(-1 * (multr(BT)))"
                },
                {"D0056",
                 "(D0054 + D0055)"
                },
                {"D0057",
                 "dt(BT)"
                },
                {"D0058",
                 "divr(BR)"
                },
                {"D0059",
                 "(D0057 + D0058)"
                },
                {"D0060",
                 "(D0050 + D0059)"
                },
                {"D0061",
                 "(2 * (D0050))"
                },
                {"D0062",
                 "(D0061 - D0060)"
                },
                {"D0063",
                 "divr(divr(D0059))"
                },
                {"D0064",
                 "(2 * (D0063))"
                },
                {"D0065",
                 "divr(divr(D0060))"
                },
                {"D0066",
                 "(D0064 - D0065)"
                },
                {"D0067",
                 "divr(divr(D0056))"
                },
                {"D0068",
                 "(D0053 + D0067)"
                },
                {"D0069",
                 "(PS * D0005)"
                },
                {"D0070",
                 "(D0069 * D0062)"
                },
                {"D0071",
                 "(PS * D0005)"
                },
                {"D0072",
                 "(D0071 * D0066)"
                },
                {"D0073",
                 "(PS * D0005)"
                },
                {"D0074",
                 "(D0073 * D0068)"
                },
                {"D0075",
                 "((1 / 2) * (D0070))"
                },
                {"D0076",
                 "((1 / 2) * (D0072))"
                },
                {"D0077",
                 "((1 / 2) * (D0074))"
                },
                {"D0078",
                 "(D0075 * D0075)"
                },
                {"D0079",
                 "(D0076 * D0076)"
                },
                {"D0080",
                 "D0079"
                },
                {"D0358",
                 "multr(multr(D0076))"
                },
                {"D0081",
                 "(D0358 * D0358)"
                },
                {"D0082",
                 "(D0078 + D0081)"
                },
                {"D0083",
                 "(D0077 * D0077)"
                },
                {"D0084",
                 "(2 * (D0083))"
                },
                {"D0085",
                 "multr(multr(D0084))"
                },
                {"D0086",
                 "(D0082 + D0085)"
                },
                {"D0087",
                 "(PS * D0005)"
                },
                {"D0088",
                 "dr(D0049)"
                },
                {"D0089",
                 "(BR * D0088)"
                },
                {"D0090",
                 "dt(D0049)"
                },
                {"D0091",
                 "(BT * D0090)"
                },
                {"D0092",
                 "(D0089 + D0091)"
                },
                {"D0093",
                 "(D0087 * D0092)"
                },
                {"D0094",
                 "(PS * D0005)"
                },
                {"D0095",
                 "dr(D0031)"
                },
                {"D0096",
                 "(BR * D0095)"
                },
                {"D0097",
                 "dt(D0031)"
                },
                {"D0098",
                 "(BT * D0097)"
                },
                {"D0099",
                 "(D0096 + D0098)"
                },
                {"D0100",
                 "(D0094 * D0099)"
                },
                {"D0101",
                 "(D0049 * D0049)"
                },
                {"D0102",
                 "((3 / 2) * (D0101))"
                },
                {"D0103",
                 "(D0086 + D0102)"
                },
                {"D0104",
                 "(PS * PS)"
                },
                {"D0105",
                 "(D0104 * PS)"
                },
                {"D0106",
                 "(D0105 * PS)"
                },
                {"D0107",
                 "(1 / (D0106))"
                },
                {"D0108",
                 "(PS * PS)"
                },
                {"D0109",
                 "(D0108 * exp(D0003))"
                },
                {"D0110",
                 "lap2(D0002)"
                },
                {"D0111",
                 "dr(D0002)"
                },
                {"D0112",
                 "divr(D0111)"
                },
                {"D0113",
                 "dt(D0002)"
                },
                {"D0114",
                 "(divsint(dt(multsint(D0113))) - dt(D0113))"
                },
                {"D0115",
                 "D0114"
                },
                {"D0116",
                 "divr(divr(D0115))"
                },
                {"D0117",
                 "(D0112 + D0116)"
                },
                {"D0118",
                 "(3 * (D0117))"
                },
                {"D0119",
                 "(D0110 - D0118)"
                },
                {"D0120",
                 "(D0021 * D0010)"
                },
                {"D0121",
                 "(D0119 + D0120)"
                },
                {"D0122",
                 "multr(multr(D0025))"
                },
                {"D0123",
                 "(D0122 * D0014)"
                },
                {"D0124",
                 "divr(divr(D0123))"
                },
                {"D0125",
                 "(D0121 + D0124)"
                },
                {"D0126",
                 "(D0031 * D0049)"
                },
                {"D0127",
                 "(4 * (D0126))"
                },
                {"D0128",
                 "(D0127 + D0100)"
                },
                {"D0129",
                 "(D0109 * D0128)"
                },
                {"D0130",
                 "(D0125 + D0129)"
                },
                {"D0131",
                 "dr(D0050)"
                },
                {"D0132",
                 "dt(D0056)"
                },
                {"D0133",
                 "(-1 * (multr(D0050)))"
                },
                {"D0134",
                 "(-1 * D0133)"
                },
                {"D0135",
                 "(-1 * (multr(D0059)))"
                },
                {"D0136",
                 "(D0134 + D0135)"
                },
                {"D0137",
                 "(D0132 + D0136)"
                },
                {"D0138",
                 "divr(divr(D0137))"
                },
                {"D0139",
                 "(D0131 + D0138)"
                },
                {"D0140",
                 "dr(D0053)"
                },
                {"D0141",
                 "divr(D0053)"
                },
                {"D0142",
                 "(D0140 + D0141)"
                },
                {"D0143",
                 "dt(D0059)"
                },
                {"D0144",
                 "divr(D0056)"
                },
                {"D0145",
                 "(-1 * (multr(D0053)))"
                },
                {"D0146",
                 "(D0144 - D0145)"
                },
                {"D0147",
                 "(D0143 + D0146)"
                },
                {"D0148",
                 "divr(divr(D0147))"
                },
                {"D0149",
                 "(D0142 + D0148)"
                },
                {"D0150",
                 "divr(D0062)"
                },
                {"D0151",
                 "multr(multr(D0068))"
                },
                {"D0152",
                 "(divsint(dt(multsint(D0151))) - dt(D0151))"
                },
                {"D0153",
                 "D0152"
                },
                {"D0154",
                 "divr(divr(D0153))"
                },
                {"D0155",
                 "(D0150 + D0154)"
                },
                {"D0156",
                 "(D0139 + D0155)"
                },
                {"D0157",
                 "(D0062 * D0017)"
                },
                {"D0158",
                 "multr(multr(D0068))"
                },
                {"D0159",
                 "(D0158 * D0020)"
                },
                {"D0160",
                 "divr(divr(D0159))"
                },
                {"D0161",
                 "(D0157 + D0160)"
                },
                {"D0162",
                 "(D0156 - D0161)"
                },
                {"D0163",
                 "(PH * D0031)"
                },
                {"D0164",
                 "(D0163 * D0021)"
                },
                {"D0165",
                 "(PS * PS)"
                },
                {"D0166",
                 "(D0165 * PS)"
                },
                {"D0167",
                 "(D0166 * PS)"
                },
                {"D0168",
                 "(D0167 * PS)"
                },
                {"D0169",
                 "(D0168 * PS)"
                },
                {"D0170",
                 "(D0169 * PS)"
                },
                {"D0171",
                 "(1 / (D0170))"
                },
                {"D0172",
                 "(D0164 * D0171)"
                },
                {"D0173",
                 "divsint(divsint(divsint(divsint(divr(divr(divr(divr(D0172))))))))"
                },
                {"D0174",
                 "(D0162 + D0173)"
                },
                {"D0175",
                 "(PH * D0004)"
                },
                {"D0176",
                 "(D0175 * D0049)"
                },
                {"D0177",
                 "D0176"
                },
                {"D0178",
                 "divr(D0177)"
                },
                {"D0179",
                 "(3 * (D0178))"
                },
                {"D0180",
                 "(D0174 + D0179)"
                },
                {"D0181",
                 "D0175"
                },
                {"D0182",
                 "dr(D0049)"
                },
                {"D0183",
                 "(D0181 * D0182)"
                },
                {"D0184",
                 "(D0180 + D0183)"
                },
                {"D0185",
                 "(D0175 * D0049)"
                },
                {"D0186",
                 "D0185"
                },
                {"D0187",
                 "(D0186 * D0035)"
                },
                {"D0188",
                 "(6 * (D0187))"
                },
                {"D0189",
                 "(D0184 + D0188)"
                },
                {"D0190",
                 "divr(D0068)"
                },
                {"D0191",
                 "multr(multr(D0066))"
                },
                {"D0197",
                 "(D0068 * D0017)"
                },
                {"D0198",
                 "multr(multr(D0066))"
                },
                {"D0199",
                 "(D0198 * D0020)"
                },
                {"D0200",
                 "divr(divr(D0199))"
                },
                {"D0201",
                 "(D0197 + D0200)"
                },
                {"D0203",
                 "(PH * D0031)"
                },
                {"D0204",
                 "(D0203 * D0025)"
                },
                {"D0205",
                 "(PS * PS)"
                },
                {"D0206",
                 "(D0205 * PS)"
                },
                {"D0207",
                 "(D0206 * PS)"
                },
                {"D0208",
                 "(D0207 * PS)"
                },
                {"D0209",
                 "(D0208 * PS)"
                },
                {"D0210",
                 "(D0209 * PS)"
                },
                {"D0211",
                 "(1 / (D0210))"
                },
                {"D0212",
                 "(D0204 * D0211)"
                },
                {"D0213",
                 "divsint(divsint(divsint(divsint(divr(divr(divr(divr(D0212))))))))"
                },
                {"D0215",
                 "(PH * D0004)"
                },
                {"D0216",
                 "(D0215 * D0049)"
                },
                {"D0217",
                 "divr(divr(D0216))"
                },
                {"D0222",
                 "divr(divr(D0215))"
                },
                {"D0223",
                 "dt(D0049)"
                },
                {"D0231",
                 "lap(PH)"
                },
                {"D0232",
                 "dr(PH)"
                },
                {"D0233",
                 "divr(D0232)"
                },
                {"D0234",
                 "dt(PH)"
                },
                {"D0235",
                 "(divsint(dt(multsint(D0234))) - dt(D0234))"
                },
                {"D0236",
                 "D0235"
                },
                {"D0237",
                 "divr(divr(D0236))"
                },
                {"D0238",
                 "(D0233 + D0237)"
                },
                {"D0239",
                 "(D0231 + D0238)"
                },
                {"D0240",
                 "(PH * D0109)"
                },
                {"D0241",
                 "(D0103 - D0093)"
                },
                {"D0242",
                 "(D0240 * D0241)"
                },
                {"D0243",
                 "(D0239 - D0242)"
                },
                {"D0244",
                 "(PH * D0034)"
                },
                {"D0245",
                 "(D0244 * D0034)"
                },
                {"D0246",
                 "(D0107 * D0245)"
                },
                {"D0247",
                 "((1 / 4) * (divsint(divsint(divsint(divsint(divr(divr(divr(divr(D0246))))))))))"
                },
                {"D0248",
                 "(D0243 - D0247)"
                },
                {"D0249",
                 "(D0021 * D0021)"
                },
                {"D0250",
                 "(D0024 * D0024)"
                },
                {"D0251",
                 "divr(divr(D0250))"
                },
                {"D0252",
                 "(D0249 + D0251)"
                },
                {"D0253",
                 "lap2(D0001)"
                },
                {"D0254",
                 "(D0035 * D0035)"
                },
                {"D0255",
                 "(D0036 * D0036)"
                },
                {"D0256",
                 "divr(divr(D0255))"
                },
                {"D0257",
                 "(D0254 + D0256)"
                },
                {"D0258",
                 "(4 * (D0257))"
                },
                {"D0259",
                 "(D0253 + D0258)"
                },
                {"D0260",
                 "dr(log(PH))"
                },
                {"D0261",
                 "(D0035 * D0260)"
                },
                {"D0262",
                 "dt(log(PH))"
                },
                {"D0263",
                 "(D0036 * D0262)"
                },
                {"D0264",
                 "divr(divr(D0263))"
                },
                {"D0265",
                 "(D0261 + D0264)"
                },
                {"D0266",
                 "(4 * (D0265))"
                },
                {"D0267",
                 "(D0259 - D0266)"
                },
                {"D0268",
                 "dr(log(PH))"
                },
                {"D0269",
                 "divr(D0268)"
                },
                {"D0270",
                 "dt(log(PH))"
                },
                {"D0271",
                 "(divsint(dt(multsint(D0270))) - dt(D0270))"
                },
                {"D0272",
                 "D0271"
                },
                {"D0273",
                 "divr(divr(D0272))"
                },
                {"D0274",
                 "(D0269 + D0273)"
                },
                {"D0275",
                 "(2 * (D0274))"
                },
                {"D0276",
                 "(D0267 - D0275)"
                },
                {"D0277",
                 "(4 * (D0093))"
                },
                {"D0278",
                 "(D0103 - D0277)"
                },
                {"D0279",
                 "(D0109 * D0278)"
                },
                {"D0280",
                 "((1 / 2) * (D0279))"
                },
                {"D0281",
                 "(D0276 + D0280)"
                },
                {"D0282",
                 "(D0034 * D0034)"
                },
                {"D0283",
                 "(5 * (D0282))"
                },
                {"D0284",
                 "(3 * (D0252))"
                },
                {"D0285",
                 "(D0283 - D0284)"
                },
                {"D0286",
                 "(D0107 * D0285)"
                },
                {"D0287",
                 "((1 / 4) * (divsint(divsint(divsint(divsint(divr(divr(divr(divr(D0286))))))))))"
                },
                {"D0288",
                 "(D0281 + D0287)"
                },
                {"D0289",
                 "lap(D0006)"
                },
                {"D0290",
                 "dr(PH)"
                },
                {"D0291",
                 "(D0035 * D0290)"
                },
                {"D0292",
                 "dt(PH)"
                },
                {"D0293",
                 "(D0036 * D0292)"
                },
                {"D0294",
                 "divr(divr(D0293))"
                },
                {"D0295",
                 "(D0291 + D0294)"
                },
                {"D0296",
                 "(D0295 * D0005)"
                },
                {"D0297",
                 "(D0289 + D0296)"
                },
                {"D0298",
                 "dr(PH)"
                },
                {"D0299",
                 "divr(D0298)"
                },
                {"D0300",
                 "dt(PH)"
                },
                {"D0301",
                 "(divsint(dt(multsint(D0300))) - dt(D0300))"
                },
                {"D0302",
                 "D0301"
                },
                {"D0303",
                 "divr(divr(D0302))"
                },
                {"D0304",
                 "(D0299 + D0303)"
                },
                {"D0305",
                 "(D0304 * D0005)"
                },
                {"D0306",
                 "((1 / 2) * (D0305))"
                },
                {"D0307",
                 "(D0297 + D0306)"
                },
                {"D0308",
                 "(D0109 * D0093)"
                },
                {"D0309",
                 "((1 / 2) * (D0308))"
                },
                {"D0310",
                 "(D0307 + D0309)"
                },
                {"D0311",
                 "(D0034 * D0034)"
                },
                {"D0312",
                 "(D0252 - D0311)"
                },
                {"D0313",
                 "(D0107 * D0312)"
                },
                {"D0314",
                 "((1 / 4) * (divsint(divsint(divsint(divsint(divr(divr(divr(divr(D0313))))))))))"
                },
                {"D0315",
                 "(D0310 + D0314)"
                },
                {"D0316",
                 "multsint(D0149)"
                },
                {"D0317",
                 "multsint(D0190)"
                },
                {"D0318",
                 "multsint(D0191)"
                },
                {"D0319",
                 "dt(D0318)"
                },
                {"D0320",
                 "dt(D0191)"
                },
                {"D0321",
                 "multsint(D0320)"
                },
                {"D0322",
                 "(D0319 - D0321)"
                },
                {"D0323",
                 "divr(D0322)"
                },
                {"D0324",
                 "divr(D0323)"
                },
                {"D0325",
                 "(D0317 + D0324)"
                },
                {"D0326",
                 "(D0316 + D0325)"
                },
                {"D0327",
                 "multsint(D0201)"
                },
                {"D0328",
                 "(D0326 - D0327)"
                },
                {"D0329",
                 "multsint(D0213)"
                },
                {"D0330",
                 "(D0328 + D0329)"
                },
                {"D0331",
                 "multsint(D0217)"
                },
                {"D0332",
                 "dt(D0331)"
                },
                {"D0333",
                 "dt(D0217)"
                },
                {"D0334",
                 "multsint(D0333)"
                },
                {"D0335",
                 "(D0332 - D0334)"
                },
                {"D0336",
                 "(3 * (D0335))"
                },
                {"D0337",
                 "(D0330 + D0336)"
                },
                {"D0338",
                 "multsint(D0223)"
                },
                {"D0339",
                 "(D0222 * D0338)"
                },
                {"D0340",
                 "(D0337 + D0339)"
                },
                {"D0341",
                 "multsint(D0041)"
                },
                {"D0342",
                 "multsint(D0043)"
                },
                {"D0343",
                 "multsint(BT)"
                },
                {"D0344",
                 "dt(D0343)"
                },
                {"D0345",
                 "dt(BT)"
                },
                {"D0346",
                 "multsint(D0345)"
                },
                {"D0347",
                 "(D0344 - D0346)"
                },
                {"D0348",
                 "(D0342 + D0347)"
                },
                {"D0349",
                 "(D0341 + D0348)"
                },
                {"D0350",
                 "(D0037 * D0349)"
                },
                {"D0351",
                 "(-1 * (D0350))"
                },
                {"D0352",
                 "(D0215 * D0351)"
                },
                {"D0353",
                 "divr(D0352)"
                },
                {"D0354",
                 "divr(D0353)"
                },
                {"D0355",
                 "(D0354 * D0036)"
                },
                {"D0356",
                 "(6 * (D0355))"
                },
                {"D0357",
                 "(D0340 + D0356)"
                },
            };
            return D;
        }

        inline const std::vector<FiniteJEq>& equations()
        {
            static const std::vector<FiniteJEq> E = {
                {"EQTW",
                 "D0130"
                },
                {"ESHR",
                 "D0189"
                },
                {"ESHT",
                 "D0357"
                },
                {"EPHI",
                 "D0248"
                },
                {"EQFN",
                 "D0288"
                },
                {"ESIG",
                 "D0315"
                },
            };
            return E;
        }

        inline const std::vector<FiniteJCheck>& checks()
        {
            static const std::vector<FiniteJCheck> C = {
                {"CK0010", "D0010", "D0007 D0009",
                 "(D0007 - D0009)"
                },
                {"CK0014", "D0014", "D0011 D0013",
                 "(D0011 - D0013)"
                },
                {"CK0017", "D0017", "D0010 D0016",
                 "(D0010 - D0016)"
                },
                {"CK0020", "D0020", "D0014 D0019",
                 "(D0014 - D0019)"
                },
                {"CK0024", "D0024", "D0022 D0023",
                 "(D0022 + D0023)"
                },
                {"CK0029", "D0029", "D0027 D0028",
                 "(D0027 + D0028)"
                },
                {"CK0040", "D0040", "D0038 D0039",
                 "(D0038 + D0039)"
                },
                {"CK0044", "D0044", "",
                 "(divsint(dt(multsint(BT))) - dt(BT))"
                },
                {"CK0046", "D0046", "D0043 D0045",
                 "(D0043 + D0045)"
                },
                {"CK0047", "D0047", "D0041 D0046",
                 "(D0041 + D0046)"
                },
                {"CK0053", "D0053", "D0051 D0052",
                 "(D0051 + D0052)"
                },
                {"CK0056", "D0056", "D0054 D0055",
                 "(D0054 + D0055)"
                },
                {"CK0059", "D0059", "D0057 D0058",
                 "(D0057 + D0058)"
                },
                {"CK0060", "D0060", "D0050 D0059",
                 "(D0050 + D0059)"
                },
                {"CK0062", "D0062", "D0060 D0061",
                 "(D0061 - D0060)"
                },
                {"CK0066", "D0066", "D0064 D0065",
                 "(D0064 - D0065)"
                },
                {"CK0068", "D0068", "D0053 D0067",
                 "(D0053 + D0067)"
                },
                {"CK0082", "D0082", "D0078 D0081",
                 "(D0078 + D0081)"
                },
                {"CK0086", "D0086", "D0082 D0085",
                 "(D0082 + D0085)"
                },
                {"CK0092", "D0092", "D0089 D0091",
                 "(D0089 + D0091)"
                },
                {"CK0099", "D0099", "D0096 D0098",
                 "(D0096 + D0098)"
                },
                {"CK0103", "D0103", "D0086 D0102",
                 "(D0086 + D0102)"
                },
                {"CK0114", "D0114", "D0113",
                 "(divsint(dt(multsint(D0113))) - dt(D0113))"
                },
                {"CK0117", "D0117", "D0112 D0116",
                 "(D0112 + D0116)"
                },
                {"CK0119", "D0119", "D0110 D0118",
                 "(D0110 - D0118)"
                },
                {"CK0121", "D0121", "D0119 D0120",
                 "(D0119 + D0120)"
                },
                {"CK0125", "D0125", "D0121 D0124",
                 "(D0121 + D0124)"
                },
                {"CK0128", "D0128", "D0100 D0127",
                 "(D0127 + D0100)"
                },
                {"CK0130", "D0130", "D0125 D0129",
                 "(D0125 + D0129)"
                },
                {"CK0136", "D0136", "D0134 D0135",
                 "(D0134 + D0135)"
                },
                {"CK0137", "D0137", "D0132 D0136",
                 "(D0132 + D0136)"
                },
                {"CK0139", "D0139", "D0131 D0138",
                 "(D0131 + D0138)"
                },
                {"CK0142", "D0142", "D0140 D0141",
                 "(D0140 + D0141)"
                },
                {"CK0146", "D0146", "D0144 D0145",
                 "(D0144 - D0145)"
                },
                {"CK0147", "D0147", "D0143 D0146",
                 "(D0143 + D0146)"
                },
                {"CK0149", "D0149", "D0142 D0148",
                 "(D0142 + D0148)"
                },
                {"CK0152", "D0152", "D0151",
                 "(divsint(dt(multsint(D0151))) - dt(D0151))"
                },
                {"CK0155", "D0155", "D0150 D0154",
                 "(D0150 + D0154)"
                },
                {"CK0156", "D0156", "D0139 D0155",
                 "(D0139 + D0155)"
                },
                {"CK0161", "D0161", "D0157 D0160",
                 "(D0157 + D0160)"
                },
                {"CK0162", "D0162", "D0156 D0161",
                 "(D0156 - D0161)"
                },
                {"CK0174", "D0174", "D0162 D0173",
                 "(D0162 + D0173)"
                },
                {"CK0180", "D0180", "D0174 D0179",
                 "(D0174 + D0179)"
                },
                {"CK0184", "D0184", "D0180 D0183",
                 "(D0180 + D0183)"
                },
                {"CK0189", "D0189", "D0184 D0188",
                 "(D0184 + D0188)"
                },
                {"CK0201", "D0201", "D0197 D0200",
                 "(D0197 + D0200)"
                },
                {"CK0235", "D0235", "D0234",
                 "(divsint(dt(multsint(D0234))) - dt(D0234))"
                },
                {"CK0238", "D0238", "D0233 D0237",
                 "(D0233 + D0237)"
                },
                {"CK0239", "D0239", "D0231 D0238",
                 "(D0231 + D0238)"
                },
                {"CK0241", "D0241", "D0093 D0103",
                 "(D0103 - D0093)"
                },
                {"CK0243", "D0243", "D0239 D0242",
                 "(D0239 - D0242)"
                },
                {"CK0248", "D0248", "D0243 D0247",
                 "(D0243 - D0247)"
                },
                {"CK0252", "D0252", "D0249 D0251",
                 "(D0249 + D0251)"
                },
                {"CK0257", "D0257", "D0254 D0256",
                 "(D0254 + D0256)"
                },
                {"CK0259", "D0259", "D0253 D0258",
                 "(D0253 + D0258)"
                },
                {"CK0265", "D0265", "D0261 D0264",
                 "(D0261 + D0264)"
                },
                {"CK0267", "D0267", "D0259 D0266",
                 "(D0259 - D0266)"
                },
                {"CK0271", "D0271", "D0270",
                 "(divsint(dt(multsint(D0270))) - dt(D0270))"
                },
                {"CK0274", "D0274", "D0269 D0273",
                 "(D0269 + D0273)"
                },
                {"CK0276", "D0276", "D0267 D0275",
                 "(D0267 - D0275)"
                },
                {"CK0278", "D0278", "D0103 D0277",
                 "(D0103 - D0277)"
                },
                {"CK0281", "D0281", "D0276 D0280",
                 "(D0276 + D0280)"
                },
                {"CK0285", "D0285", "D0283 D0284",
                 "(D0283 - D0284)"
                },
                {"CK0288", "D0288", "D0281 D0287",
                 "(D0281 + D0287)"
                },
                {"CK0295", "D0295", "D0291 D0294",
                 "(D0291 + D0294)"
                },
                {"CK0297", "D0297", "D0289 D0296",
                 "(D0289 + D0296)"
                },
                {"CK0301", "D0301", "D0300",
                 "(divsint(dt(multsint(D0300))) - dt(D0300))"
                },
                {"CK0304", "D0304", "D0299 D0303",
                 "(D0299 + D0303)"
                },
                {"CK0307", "D0307", "D0297 D0306",
                 "(D0297 + D0306)"
                },
                {"CK0310", "D0310", "D0307 D0309",
                 "(D0307 + D0309)"
                },
                {"CK0312", "D0312", "D0252 D0311",
                 "(D0252 - D0311)"
                },
                {"CK0315", "D0315", "D0310 D0314",
                 "(D0310 + D0314)"
                },
                {"CK0322", "D0322", "D0319 D0321",
                 "(D0319 - D0321)"
                },
                {"CK0325", "D0325", "D0317 D0324",
                 "(D0317 + D0324)"
                },
                {"CK0326", "D0326", "D0316 D0325",
                 "(D0316 + D0325)"
                },
                {"CK0328", "D0328", "D0326 D0327",
                 "(D0326 - D0327)"
                },
                {"CK0330", "D0330", "D0328 D0329",
                 "(D0328 + D0329)"
                },
                {"CK0335", "D0335", "D0332 D0334",
                 "(D0332 - D0334)"
                },
                {"CK0337", "D0337", "D0330 D0336",
                 "(D0330 + D0336)"
                },
                {"CK0340", "D0340", "D0337 D0339",
                 "(D0337 + D0339)"
                },
                {"CK0347", "D0347", "D0344 D0346",
                 "(D0344 - D0346)"
                },
                {"CK0348", "D0348", "D0342 D0347",
                 "(D0342 + D0347)"
                },
                {"CK0349", "D0349", "D0341 D0348",
                 "(D0341 + D0348)"
                },
                {"CK0357", "D0357", "D0340 D0356",
                 "(D0340 + D0356)"
                },
            };
            return C;
        }

        /// Read a def into CONFIGURATION space.  Fetching the Val_domain
        /// is not enough -- indexing it is what converts, and a probe that
        /// only fetched returned two false negatives (round 108).
        inline void read_def(Kadath::System_of_eqs& syst,
                             const Kadath::Space& sp, const char* nm,
                             int dmin, int dmax)
        {
            for (int d = dmin; d <= dmax; d++) {
                const Kadath::Val_domain& v =
                    syst.give_val_def_scalar_domain(nm, d);
                Kadath::Index ix(sp.get_domain(d)->get_nbr_points());
                (void)v(ix);
            }
        }
    } // namespace finiteJ_detail

    /// The sub-def names, in dependency order, for reading values back.
    inline const std::vector<const char*>& finiteJ_names()
    {
        static const std::vector<const char*> N = [] {
            std::vector<const char*> v;
            for (const auto& d : finiteJ_detail::subdefs()) v.push_back(d.name);
            return v;
        }();
        return N;
    }

    /// The six equation names.
    inline const std::vector<const char*>& finiteJ_eq_names()
    {
        static const std::vector<const char*> N = [] {
            std::vector<const char*> v;
            for (const auto& e : finiteJ_detail::equations()) v.push_back(e.name);
            return v;
        }();
        return N;
    }

    /// The angular bases this emission was analysed under.  The caller
    /// MUST register the six unknowns in these bases: the basis lattice
    /// that decided every sum ordering assumed them, and if the run
    /// registers something else the analysis describes a different
    /// system.  Names, not integers, so a renumbering in the library
    /// cannot silently reinterpret them.
    inline const std::vector<std::pair<const char*, const char*>>&
    finiteJ_declared_basis()
    {
        static const std::vector<std::pair<const char*, const char*>> B = {
            {"PS", "COS_EVEN"},
            {"PH", "COS_EVEN"},
            {"QF", "COS_EVEN"},
            {"BR", "COS_EVEN"},
            {"BT", "SIN_EVEN"},
            {"QB", "COS_ODD"},
        };
        return B;
    }

    /// Sums reordered by --order-sums, which is seed-specific: see the
    /// header comment.  Empty means the emission was written without it.
    inline const std::vector<const char*>& finiteJ_ordered_sums()
    {
        static const std::vector<const char*> O = {
        };
        return O;
    }

    /// Emission-time AXIS PRECONDITION violations carried into the
    /// artefact: each is a divsint applied where the emitter could not
    /// show the operand vanishes on the axis.  Empty is the only
    /// acceptable state, and since round 342 it is the only reachable
    /// one: the emitter refuses to write a violating emission at all.
    inline const std::vector<const char*>& finiteJ_axis_violations()
    {
        static const std::vector<const char*> V = {
        };
        return V;
    }

    /**
     * Register the emission, keeping the read-state contract.
     *
     * read_defs = false deliberately BREAKS the contract.  It exists so a
     * caller can show finiteJ_check() catches the breach; nothing else
     * should ever pass it.
     */
    inline void finiteJ_register(Kadath::System_of_eqs& syst,
                                 const Kadath::Space& sp, int dmin, int dmax,
                                 bool read_defs = true)
    {
        for (const auto& d : finiteJ_detail::subdefs()) {
            syst.add_def((std::string(d.name) + " = " + d.def).c_str());
            if (read_defs)
                finiteJ_detail::read_def(syst, sp, d.name, dmin, dmax);
        }
        for (const auto& e : finiteJ_detail::equations()) {
            syst.add_def((std::string(e.name) + " = " + e.def).c_str());
            if (read_defs)
                finiteJ_detail::read_def(syst, sp, e.name, dmin, dmax);
        }
    }

    /**
     * THE CONTROL.  Re-register every sum with its operands READ first and
     * compare pointwise with the original.  Returns the worst relative
     * difference and throws above tol.
     *
     * ⚠ Reading the operands before re-parsing is the whole mechanism.  A
     * version that re-registers without reading puts both spellings in the
     * same evaluator state, and two spellings in one state cannot
     * discriminate a defect whose variable IS the state -- which is how
     * round 107 shipped a check weaker than it was reported to be.
     */
    inline double finiteJ_check(Kadath::System_of_eqs& syst,
                                const Kadath::Space& sp, int dmin, int dmax,
                                double tol = 1e-12)
    {
        double worst = 0.0;
        std::string worst_name;
        for (const auto& c : finiteJ_detail::checks()) {
            std::istringstream is(c.reads);
            for (std::string nm; is >> nm;)
                finiteJ_detail::read_def(syst, sp, nm.c_str(), dmin, dmax);
            syst.add_def((std::string(c.name) + " = " + c.def).c_str());
            double mx = 0.0, scale = 0.0;
            for (int d = dmin; d <= dmax; d++) {
                const Kadath::Val_domain& a =
                    syst.give_val_def_scalar_domain(c.of, d);
                const Kadath::Val_domain& b =
                    syst.give_val_def_scalar_domain(c.name, d);
                Kadath::Index ix(sp.get_domain(d)->get_nbr_points());
                do {
                    mx = std::max(mx, std::fabs(a(ix) - b(ix)));
                    scale = std::max(scale, std::fabs(a(ix)));
                } while (ix.inc());
            }
            const double rel = mx / std::max(scale, 1e-300);
            if (rel > worst) { worst = rel; worst_name = c.of; }
        }
        if (worst > tol)
            throw std::runtime_error(
                "finiteJ read-state contract broken: " + worst_name
                + " differs from its own re-expression by "
                + std::to_string(worst)
                + " -- the defs were registered without being read");
        return worst;
    }

} // namespace Trumpet
