/*
 * finiteJ_eqs.hpp -- GENERATED by scripts/finiteJ_emit.py.  Do not edit.
 *
 * The six finite-J equations as Kadath defs, emitted from the ASSEMBLY's
 * structure rather than from an expanded expression: where the assembly
 * applied lap2S the emission says lap2, instead of expanding and hoping to
 * recognise it again.
 *
 * Unknowns PS, PH, QF, BR, BT, QB.  Spin constant JJ.  There are NO sin or
 * cos FIELDS: round 103 measured that neither lies in the scalar COS_EVEN
 * span, so an add_cst holding one stores an alias.  Angular and radial
 * factors go through the coefficient-space operators instead, and
 *
 *     cot(theta) * X  ==  divsint(dt(multsint(X))) - dt(X)
 *
 * which the probe verified to 2e-16 on a field vanishing on the axis.
 *
 * Registered as 334 named sub-defs then the six equations: the parser has a
 * STACK-depth limit near 1000 characters that was not reproducible run to
 * run, so every piece here is kept far below it.
 *
 * ⚠ THE READ-STATE CONTRACT (round 108).  Kadath evaluates a sum
 * differently depending on whether its named operands have been READ --
 * indexed, which forces a Val_domain into configuration space -- before
 * the sum is parsed, and a def parsed in the wrong state does not recover
 * when its operands are read later.  Every sub-def below must therefore be
 * read immediately after it is registered.  That is why the def TEXT is not
 * exported: register through finiteJ_register(), which does it, and call
 * finiteJ_check(), which fails loudly if it was not done.  A requirement in
 * prose gets transcribed wrongly; this one is in the only function that can
 * reach the text.
 *
 * ⚠ WRITTEN UNDER --allow-axis-violations.  4 divsint application(s)
 * in 1 def(s) are applied to an operand the emitter could NOT show
 * vanishes on the axis, which is the precondition divsint and the cot
 * construction need.  Those defs are wrong and the emission is not
 * accepted:
 *
 *     D0105  divsint at guaranteed sin-order 0
 *     D0105  divsint at guaranteed sin-order -1
 *     D0105  divsint at guaranteed sin-order -2
 *     D0105  divsint at guaranteed sin-order -3
 *
 * finiteJ_axis_violations() carries the same list at run time.
 */
#pragma once

#include "For_Kadath/Array/headcpp.hpp"
#include "For_Kadath/Space/space.hpp"
#include "For_Kadath/System_of_eqs/system_of_eqs.hpp"

#include <algorithm>
#include <cmath>
#include <sstream>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

namespace Trumpet
{
    struct FiniteJEq { const char* name; const char* def; };

    /// One sum, re-expressed.  `reads` are the operands finiteJ_check()
    /// reads before re-parsing `def`, which is what lets it discriminate.
    struct FiniteJCheck {
        const char* name; const char* of; const char* reads; const char* def;
    };

    namespace finiteJ_detail
    {
        /// ⚠ The def TEXT.  Registering any of this by hand skips the read
        /// the evaluator needs; go through finiteJ_register() instead.
        inline const std::vector<FiniteJEq>& subdefs()
        {
            static const std::vector<FiniteJEq> D = {
                {"D0001",
                 "multsint(multsint(multsint(multsint(QB))))"
                },
                {"D0002",
                 "(2 * (QF))"
                },
                {"D0003",
                 "(1 / (PS))"
                },
                {"D0004",
                 "(1 / (PH))"
                },
                {"D0005",
                 "((1 / 2) * (log(PS)))"
                },
                {"D0006",
                 "dr(log(PH))"
                },
                {"D0007",
                 "dr(log(PS))"
                },
                {"D0008",
                 "(4 * (D0007))"
                },
                {"D0009",
                 "(D0006 - D0008)"
                },
                {"D0010",
                 "dt(log(PH))"
                },
                {"D0011",
                 "dt(log(PS))"
                },
                {"D0012",
                 "(4 * (D0011))"
                },
                {"D0013",
                 "(D0010 - D0012)"
                },
                {"D0014",
                 "dr(QF)"
                },
                {"D0015",
                 "(2 * (D0014))"
                },
                {"D0016",
                 "(D0009 - D0015)"
                },
                {"D0017",
                 "dt(QF)"
                },
                {"D0018",
                 "(2 * (D0017))"
                },
                {"D0019",
                 "(D0013 - D0018)"
                },
                {"D0020",
                 "dr(D0001)"
                },
                {"D0021",
                 "dt(D0001)"
                },
                {"D0022",
                 "(6*JJ * (multsint(multsint(multsint(ones)))))"
                },
                {"D0023",
                 "(D0021 + D0022)"
                },
                {"D0024",
                 "divr(divr(D0023))"
                },
                {"D0025",
                 "(PS * D0004)"
                },
                {"D0026",
                 "(BR * D0020)"
                },
                {"D0027",
                 "(BT * D0023)"
                },
                {"D0028",
                 "(D0026 + D0027)"
                },
                {"D0029",
                 "(D0025 * D0028)"
                },
                {"D0030",
                 "(-1 * (D0029))"
                },
                {"D0031",
                 "(D0030 * D0003)"
                },
                {"D0032",
                 "(-1 * (QF))"
                },
                {"D0033",
                 "(D0031 * exp(D0032))"
                },
                {"D0034",
                 "dr(D0005)"
                },
                {"D0035",
                 "dt(D0005)"
                },
                {"D0036",
                 "(PS * D0004)"
                },
                {"D0037",
                 "(2 * (D0034))"
                },
                {"D0038",
                 "divr(ones)"
                },
                {"D0039",
                 "(D0037 + D0038)"
                },
                {"D0040",
                 "(BR * D0039)"
                },
                {"D0041",
                 "(2 * (D0035))"
                },
                {"D0042",
                 "(BT * D0041)"
                },
                {"D0043",
                 "(divsint(dt(multsint(BT))) - dt(BT))"
                },
                {"D0044",
                 "D0043"
                },
                {"D0045",
                 "(D0042 + D0044)"
                },
                {"D0046",
                 "(D0040 + D0045)"
                },
                {"D0047",
                 "(D0036 * D0046)"
                },
                {"D0048",
                 "(-1 * (D0047))"
                },
                {"D0049",
                 "dr(BR)"
                },
                {"D0050",
                 "dr(BT)"
                },
                {"D0051",
                 "dt(BR)"
                },
                {"D0052",
                 "(-1 * (multr(BT)))"
                },
                {"D0053",
                 "(D0051 + D0052)"
                },
                {"D0054",
                 "dt(BT)"
                },
                {"D0055",
                 "divr(BR)"
                },
                {"D0056",
                 "(D0054 + D0055)"
                },
                {"D0057",
                 "(D0049 + D0056)"
                },
                {"D0058",
                 "(2 * (D0049))"
                },
                {"D0059",
                 "(D0058 - D0057)"
                },
                {"D0060",
                 "divr(divr(D0056))"
                },
                {"D0061",
                 "(2 * (D0060))"
                },
                {"D0062",
                 "divr(divr(D0057))"
                },
                {"D0063",
                 "(D0061 - D0062)"
                },
                {"D0064",
                 "divr(divr(D0053))"
                },
                {"D0065",
                 "(D0050 + D0064)"
                },
                {"D0066",
                 "(PS * D0004)"
                },
                {"D0067",
                 "(D0066 * D0059)"
                },
                {"D0068",
                 "(PS * D0004)"
                },
                {"D0069",
                 "(D0068 * D0063)"
                },
                {"D0070",
                 "(PS * D0004)"
                },
                {"D0071",
                 "(D0070 * D0065)"
                },
                {"D0072",
                 "((1 / 2) * (D0067))"
                },
                {"D0073",
                 "((1 / 2) * (D0069))"
                },
                {"D0074",
                 "((1 / 2) * (D0071))"
                },
                {"D0075",
                 "(D0072 * D0072)"
                },
                {"D0076",
                 "(D0073 * D0073)"
                },
                {"D0077",
                 "D0076"
                },
                {"D0078",
                 "multr(multr(multr(multr(D0077))))"
                },
                {"D0079",
                 "(D0075 + D0078)"
                },
                {"D0080",
                 "(D0074 * D0074)"
                },
                {"D0081",
                 "(2 * (D0080))"
                },
                {"D0082",
                 "multr(multr(D0081))"
                },
                {"D0083",
                 "(D0079 + D0082)"
                },
                {"D0084",
                 "(PS * D0004)"
                },
                {"D0085",
                 "dr(D0048)"
                },
                {"D0086",
                 "(BR * D0085)"
                },
                {"D0087",
                 "dt(D0048)"
                },
                {"D0088",
                 "(BT * D0087)"
                },
                {"D0089",
                 "(D0086 + D0088)"
                },
                {"D0090",
                 "(D0084 * D0089)"
                },
                {"D0091",
                 "(PS * D0004)"
                },
                {"D0092",
                 "dr(D0030)"
                },
                {"D0093",
                 "(BR * D0092)"
                },
                {"D0094",
                 "dt(D0030)"
                },
                {"D0095",
                 "(BT * D0094)"
                },
                {"D0096",
                 "(D0093 + D0095)"
                },
                {"D0097",
                 "(D0091 * D0096)"
                },
                {"D0098",
                 "(D0048 * D0048)"
                },
                {"D0099",
                 "((3 / 2) * (D0098))"
                },
                {"D0100",
                 "(D0083 + D0099)"
                },
                {"D0101",
                 "(PS * PS)"
                },
                {"D0102",
                 "(D0101 * PS)"
                },
                {"D0103",
                 "(D0102 * PS)"
                },
                {"D0104",
                 "(1 / (D0103))"
                },
                {"D0105",
                 "((1 / 4) * (divsint(divsint(divsint(divsint(divr(divr(divr(divr(D0104))))))))))"
                },
                {"D0106",
                 "(PS * PS)"
                },
                {"D0107",
                 "(D0106 * exp(D0002))"
                },
                {"D0108",
                 "lap2(D0001)"
                },
                {"D0109",
                 "dr(D0001)"
                },
                {"D0110",
                 "divr(D0109)"
                },
                {"D0111",
                 "dt(D0001)"
                },
                {"D0112",
                 "(divsint(dt(multsint(D0111))) - dt(D0111))"
                },
                {"D0113",
                 "D0112"
                },
                {"D0114",
                 "divr(divr(D0113))"
                },
                {"D0115",
                 "(D0110 + D0114)"
                },
                {"D0116",
                 "(3 * (D0115))"
                },
                {"D0117",
                 "(D0108 - D0116)"
                },
                {"D0118",
                 "(D0020 * D0009)"
                },
                {"D0119",
                 "(D0117 + D0118)"
                },
                {"D0120",
                 "multr(multr(D0024))"
                },
                {"D0121",
                 "(D0120 * D0013)"
                },
                {"D0122",
                 "divr(divr(D0121))"
                },
                {"D0123",
                 "(D0119 + D0122)"
                },
                {"D0124",
                 "(D0030 * D0048)"
                },
                {"D0125",
                 "(4 * (D0124))"
                },
                {"D0126",
                 "(D0125 + D0097)"
                },
                {"D0127",
                 "(D0107 * D0126)"
                },
                {"D0128",
                 "(D0123 + D0127)"
                },
                {"D0129",
                 "dr(D0049)"
                },
                {"D0130",
                 "dt(D0053)"
                },
                {"D0131",
                 "(-1 * (multr(D0049)))"
                },
                {"D0132",
                 "(-1 * D0131)"
                },
                {"D0133",
                 "(-1 * (multr(D0056)))"
                },
                {"D0134",
                 "(D0132 + D0133)"
                },
                {"D0135",
                 "(D0130 + D0134)"
                },
                {"D0136",
                 "divr(divr(D0135))"
                },
                {"D0137",
                 "(D0129 + D0136)"
                },
                {"D0138",
                 "dr(D0050)"
                },
                {"D0139",
                 "divr(D0050)"
                },
                {"D0140",
                 "(D0138 + D0139)"
                },
                {"D0141",
                 "dt(D0056)"
                },
                {"D0142",
                 "divr(D0053)"
                },
                {"D0143",
                 "(-1 * (multr(D0050)))"
                },
                {"D0144",
                 "(D0142 - D0143)"
                },
                {"D0145",
                 "(D0141 + D0144)"
                },
                {"D0146",
                 "divr(divr(D0145))"
                },
                {"D0147",
                 "(D0140 + D0146)"
                },
                {"D0148",
                 "divr(D0059)"
                },
                {"D0149",
                 "multr(multr(D0065))"
                },
                {"D0150",
                 "(divsint(dt(multsint(D0149))) - dt(D0149))"
                },
                {"D0151",
                 "D0150"
                },
                {"D0152",
                 "divr(divr(D0151))"
                },
                {"D0153",
                 "(D0148 + D0152)"
                },
                {"D0154",
                 "(D0137 + D0153)"
                },
                {"D0155",
                 "(D0059 * D0016)"
                },
                {"D0156",
                 "multr(multr(D0065))"
                },
                {"D0157",
                 "(D0156 * D0019)"
                },
                {"D0158",
                 "divr(divr(D0157))"
                },
                {"D0159",
                 "(D0155 + D0158)"
                },
                {"D0160",
                 "(D0154 - D0159)"
                },
                {"D0161",
                 "(PH * D0030)"
                },
                {"D0162",
                 "(D0161 * D0020)"
                },
                {"D0163",
                 "(PS * PS)"
                },
                {"D0164",
                 "(D0163 * PS)"
                },
                {"D0165",
                 "(D0164 * PS)"
                },
                {"D0166",
                 "(D0165 * PS)"
                },
                {"D0167",
                 "(D0166 * PS)"
                },
                {"D0168",
                 "(D0167 * PS)"
                },
                {"D0169",
                 "(1 / (D0168))"
                },
                {"D0170",
                 "(D0162 * D0169)"
                },
                {"D0171",
                 "divsint(divsint(divsint(divsint(divr(divr(divr(divr(D0170))))))))"
                },
                {"D0172",
                 "(D0160 + D0171)"
                },
                {"D0173",
                 "(PH * D0003)"
                },
                {"D0174",
                 "(D0173 * D0048)"
                },
                {"D0175",
                 "D0174"
                },
                {"D0176",
                 "divr(D0175)"
                },
                {"D0177",
                 "(3 * (D0176))"
                },
                {"D0178",
                 "(D0172 + D0177)"
                },
                {"D0179",
                 "D0173"
                },
                {"D0180",
                 "dr(D0048)"
                },
                {"D0181",
                 "(D0179 * D0180)"
                },
                {"D0182",
                 "(D0178 + D0181)"
                },
                {"D0183",
                 "(D0173 * D0048)"
                },
                {"D0184",
                 "D0183"
                },
                {"D0185",
                 "(D0184 * D0034)"
                },
                {"D0186",
                 "(6 * (D0185))"
                },
                {"D0187",
                 "(D0182 + D0186)"
                },
                {"D0188",
                 "divr(D0065)"
                },
                {"D0189",
                 "multr(multr(D0063))"
                },
                {"D0195",
                 "(D0065 * D0016)"
                },
                {"D0196",
                 "multr(multr(D0063))"
                },
                {"D0197",
                 "(D0196 * D0019)"
                },
                {"D0198",
                 "divr(divr(D0197))"
                },
                {"D0199",
                 "(D0195 + D0198)"
                },
                {"D0201",
                 "(PH * D0030)"
                },
                {"D0202",
                 "(D0201 * D0024)"
                },
                {"D0203",
                 "(PS * PS)"
                },
                {"D0204",
                 "(D0203 * PS)"
                },
                {"D0205",
                 "(D0204 * PS)"
                },
                {"D0206",
                 "(D0205 * PS)"
                },
                {"D0207",
                 "(D0206 * PS)"
                },
                {"D0208",
                 "(D0207 * PS)"
                },
                {"D0209",
                 "(1 / (D0208))"
                },
                {"D0210",
                 "(D0202 * D0209)"
                },
                {"D0211",
                 "divsint(divsint(divsint(divsint(divr(divr(divr(divr(D0210))))))))"
                },
                {"D0213",
                 "(PH * D0003)"
                },
                {"D0214",
                 "(D0213 * D0048)"
                },
                {"D0215",
                 "divr(divr(D0214))"
                },
                {"D0220",
                 "divr(divr(D0213))"
                },
                {"D0221",
                 "dt(D0048)"
                },
                {"D0229",
                 "lap(PH)"
                },
                {"D0230",
                 "dr(PH)"
                },
                {"D0231",
                 "divr(D0230)"
                },
                {"D0232",
                 "dt(PH)"
                },
                {"D0233",
                 "(divsint(dt(multsint(D0232))) - dt(D0232))"
                },
                {"D0234",
                 "D0233"
                },
                {"D0235",
                 "divr(divr(D0234))"
                },
                {"D0236",
                 "(D0231 + D0235)"
                },
                {"D0237",
                 "(D0229 + D0236)"
                },
                {"D0238",
                 "(PH * D0107)"
                },
                {"D0239",
                 "(D0100 - D0090)"
                },
                {"D0240",
                 "(D0238 * D0239)"
                },
                {"D0241",
                 "(D0237 - D0240)"
                },
                {"D0242",
                 "(PH * D0033)"
                },
                {"D0243",
                 "(D0242 * D0033)"
                },
                {"D0244",
                 "(D0243 * D0105)"
                },
                {"D0245",
                 "(D0241 - D0244)"
                },
                {"D0246",
                 "(D0020 * D0020)"
                },
                {"D0247",
                 "(D0023 * D0023)"
                },
                {"D0248",
                 "divr(divr(D0247))"
                },
                {"D0249",
                 "(D0246 + D0248)"
                },
                {"D0250",
                 "lap2(QF)"
                },
                {"D0251",
                 "(D0034 * D0034)"
                },
                {"D0252",
                 "(D0035 * D0035)"
                },
                {"D0253",
                 "divr(divr(D0252))"
                },
                {"D0254",
                 "(D0251 + D0253)"
                },
                {"D0255",
                 "(4 * (D0254))"
                },
                {"D0256",
                 "(D0250 + D0255)"
                },
                {"D0257",
                 "dr(log(PH))"
                },
                {"D0258",
                 "(D0034 * D0257)"
                },
                {"D0259",
                 "dt(log(PH))"
                },
                {"D0260",
                 "(D0035 * D0259)"
                },
                {"D0261",
                 "divr(divr(D0260))"
                },
                {"D0262",
                 "(D0258 + D0261)"
                },
                {"D0263",
                 "(4 * (D0262))"
                },
                {"D0264",
                 "(D0256 - D0263)"
                },
                {"D0265",
                 "dr(log(PH))"
                },
                {"D0266",
                 "divr(D0265)"
                },
                {"D0267",
                 "dt(log(PH))"
                },
                {"D0268",
                 "(divsint(dt(multsint(D0267))) - dt(D0267))"
                },
                {"D0269",
                 "D0268"
                },
                {"D0270",
                 "divr(divr(D0269))"
                },
                {"D0271",
                 "(D0266 + D0270)"
                },
                {"D0272",
                 "(2 * (D0271))"
                },
                {"D0273",
                 "(D0264 - D0272)"
                },
                {"D0274",
                 "(4 * (D0090))"
                },
                {"D0275",
                 "(D0100 - D0274)"
                },
                {"D0276",
                 "(D0107 * D0275)"
                },
                {"D0277",
                 "((1 / 2) * (D0276))"
                },
                {"D0278",
                 "(D0273 + D0277)"
                },
                {"D0279",
                 "(D0033 * D0033)"
                },
                {"D0280",
                 "(5 * (D0279))"
                },
                {"D0281",
                 "(3 * (D0249))"
                },
                {"D0282",
                 "(D0280 - D0281)"
                },
                {"D0283",
                 "(D0282 * D0105)"
                },
                {"D0284",
                 "(D0278 + D0283)"
                },
                {"D0285",
                 "lap(D0005)"
                },
                {"D0286",
                 "dr(PH)"
                },
                {"D0287",
                 "(D0034 * D0286)"
                },
                {"D0288",
                 "dt(PH)"
                },
                {"D0289",
                 "(D0035 * D0288)"
                },
                {"D0290",
                 "divr(divr(D0289))"
                },
                {"D0291",
                 "(D0287 + D0290)"
                },
                {"D0292",
                 "(D0291 * D0004)"
                },
                {"D0293",
                 "(D0285 + D0292)"
                },
                {"D0294",
                 "dr(PH)"
                },
                {"D0295",
                 "divr(D0294)"
                },
                {"D0296",
                 "dt(PH)"
                },
                {"D0297",
                 "(divsint(dt(multsint(D0296))) - dt(D0296))"
                },
                {"D0298",
                 "D0297"
                },
                {"D0299",
                 "divr(divr(D0298))"
                },
                {"D0300",
                 "(D0295 + D0299)"
                },
                {"D0301",
                 "(D0300 * D0004)"
                },
                {"D0302",
                 "((1 / 2) * (D0301))"
                },
                {"D0303",
                 "(D0293 + D0302)"
                },
                {"D0304",
                 "(D0107 * D0090)"
                },
                {"D0305",
                 "((1 / 2) * (D0304))"
                },
                {"D0306",
                 "(D0303 + D0305)"
                },
                {"D0307",
                 "(D0033 * D0033)"
                },
                {"D0308",
                 "(D0249 - D0307)"
                },
                {"D0309",
                 "(D0308 * D0105)"
                },
                {"D0310",
                 "(D0306 + D0309)"
                },
                {"D0311",
                 "multsint(D0147)"
                },
                {"D0312",
                 "multsint(D0188)"
                },
                {"D0313",
                 "multsint(D0189)"
                },
                {"D0314",
                 "dt(D0313)"
                },
                {"D0315",
                 "dt(D0189)"
                },
                {"D0316",
                 "multsint(D0315)"
                },
                {"D0317",
                 "(D0314 - D0316)"
                },
                {"D0318",
                 "divr(D0317)"
                },
                {"D0319",
                 "divr(D0318)"
                },
                {"D0320",
                 "(D0312 + D0319)"
                },
                {"D0321",
                 "(D0311 + D0320)"
                },
                {"D0322",
                 "multsint(D0199)"
                },
                {"D0323",
                 "(D0321 - D0322)"
                },
                {"D0324",
                 "multsint(D0211)"
                },
                {"D0325",
                 "(D0323 + D0324)"
                },
                {"D0326",
                 "multsint(D0215)"
                },
                {"D0327",
                 "dt(D0326)"
                },
                {"D0328",
                 "dt(D0215)"
                },
                {"D0329",
                 "multsint(D0328)"
                },
                {"D0330",
                 "(D0327 - D0329)"
                },
                {"D0331",
                 "(3 * (D0330))"
                },
                {"D0332",
                 "(D0325 + D0331)"
                },
                {"D0333",
                 "multsint(D0221)"
                },
                {"D0334",
                 "(D0220 * D0333)"
                },
                {"D0335",
                 "(D0332 + D0334)"
                },
                {"D0336",
                 "multsint(D0040)"
                },
                {"D0337",
                 "multsint(D0042)"
                },
                {"D0338",
                 "multsint(BT)"
                },
                {"D0339",
                 "dt(D0338)"
                },
                {"D0340",
                 "dt(BT)"
                },
                {"D0341",
                 "multsint(D0340)"
                },
                {"D0342",
                 "(D0339 - D0341)"
                },
                {"D0343",
                 "(D0337 + D0342)"
                },
                {"D0344",
                 "(D0336 + D0343)"
                },
                {"D0345",
                 "(D0036 * D0344)"
                },
                {"D0346",
                 "(-1 * (D0345))"
                },
                {"D0347",
                 "(D0213 * D0346)"
                },
                {"D0348",
                 "divr(D0347)"
                },
                {"D0349",
                 "divr(D0348)"
                },
                {"D0350",
                 "(D0349 * D0035)"
                },
                {"D0351",
                 "(6 * (D0350))"
                },
                {"D0352",
                 "(D0335 + D0351)"
                },
            };
            return D;
        }

        inline const std::vector<FiniteJEq>& equations()
        {
            static const std::vector<FiniteJEq> E = {
                {"EQTW",
                 "D0128"
                },
                {"ESHR",
                 "D0187"
                },
                {"ESHT",
                 "D0352"
                },
                {"EPHI",
                 "D0245"
                },
                {"EQFN",
                 "D0284"
                },
                {"ESIG",
                 "D0310"
                },
            };
            return E;
        }

        inline const std::vector<FiniteJCheck>& checks()
        {
            static const std::vector<FiniteJCheck> C = {
                {"CK0009", "D0009", "D0006 D0008",
                 "(D0006 - D0008)"
                },
                {"CK0013", "D0013", "D0010 D0012",
                 "(D0010 - D0012)"
                },
                {"CK0016", "D0016", "D0009 D0015",
                 "(D0009 - D0015)"
                },
                {"CK0019", "D0019", "D0013 D0018",
                 "(D0013 - D0018)"
                },
                {"CK0023", "D0023", "D0021 D0022",
                 "(D0021 + D0022)"
                },
                {"CK0028", "D0028", "D0026 D0027",
                 "(D0026 + D0027)"
                },
                {"CK0039", "D0039", "D0037 D0038",
                 "(D0037 + D0038)"
                },
                {"CK0043", "D0043", "",
                 "(divsint(dt(multsint(BT))) - dt(BT))"
                },
                {"CK0045", "D0045", "D0042 D0044",
                 "(D0042 + D0044)"
                },
                {"CK0046", "D0046", "D0040 D0045",
                 "(D0040 + D0045)"
                },
                {"CK0053", "D0053", "D0051 D0052",
                 "(D0051 + D0052)"
                },
                {"CK0056", "D0056", "D0054 D0055",
                 "(D0054 + D0055)"
                },
                {"CK0057", "D0057", "D0049 D0056",
                 "(D0049 + D0056)"
                },
                {"CK0059", "D0059", "D0057 D0058",
                 "(D0058 - D0057)"
                },
                {"CK0063", "D0063", "D0061 D0062",
                 "(D0061 - D0062)"
                },
                {"CK0065", "D0065", "D0050 D0064",
                 "(D0050 + D0064)"
                },
                {"CK0079", "D0079", "D0075 D0078",
                 "(D0075 + D0078)"
                },
                {"CK0083", "D0083", "D0079 D0082",
                 "(D0079 + D0082)"
                },
                {"CK0089", "D0089", "D0086 D0088",
                 "(D0086 + D0088)"
                },
                {"CK0096", "D0096", "D0093 D0095",
                 "(D0093 + D0095)"
                },
                {"CK0100", "D0100", "D0083 D0099",
                 "(D0083 + D0099)"
                },
                {"CK0112", "D0112", "D0111",
                 "(divsint(dt(multsint(D0111))) - dt(D0111))"
                },
                {"CK0115", "D0115", "D0110 D0114",
                 "(D0110 + D0114)"
                },
                {"CK0117", "D0117", "D0108 D0116",
                 "(D0108 - D0116)"
                },
                {"CK0119", "D0119", "D0117 D0118",
                 "(D0117 + D0118)"
                },
                {"CK0123", "D0123", "D0119 D0122",
                 "(D0119 + D0122)"
                },
                {"CK0126", "D0126", "D0097 D0125",
                 "(D0125 + D0097)"
                },
                {"CK0128", "D0128", "D0123 D0127",
                 "(D0123 + D0127)"
                },
                {"CK0134", "D0134", "D0132 D0133",
                 "(D0132 + D0133)"
                },
                {"CK0135", "D0135", "D0130 D0134",
                 "(D0130 + D0134)"
                },
                {"CK0137", "D0137", "D0129 D0136",
                 "(D0129 + D0136)"
                },
                {"CK0140", "D0140", "D0138 D0139",
                 "(D0138 + D0139)"
                },
                {"CK0144", "D0144", "D0142 D0143",
                 "(D0142 - D0143)"
                },
                {"CK0145", "D0145", "D0141 D0144",
                 "(D0141 + D0144)"
                },
                {"CK0147", "D0147", "D0140 D0146",
                 "(D0140 + D0146)"
                },
                {"CK0150", "D0150", "D0149",
                 "(divsint(dt(multsint(D0149))) - dt(D0149))"
                },
                {"CK0153", "D0153", "D0148 D0152",
                 "(D0148 + D0152)"
                },
                {"CK0154", "D0154", "D0137 D0153",
                 "(D0137 + D0153)"
                },
                {"CK0159", "D0159", "D0155 D0158",
                 "(D0155 + D0158)"
                },
                {"CK0160", "D0160", "D0154 D0159",
                 "(D0154 - D0159)"
                },
                {"CK0172", "D0172", "D0160 D0171",
                 "(D0160 + D0171)"
                },
                {"CK0178", "D0178", "D0172 D0177",
                 "(D0172 + D0177)"
                },
                {"CK0182", "D0182", "D0178 D0181",
                 "(D0178 + D0181)"
                },
                {"CK0187", "D0187", "D0182 D0186",
                 "(D0182 + D0186)"
                },
                {"CK0199", "D0199", "D0195 D0198",
                 "(D0195 + D0198)"
                },
                {"CK0233", "D0233", "D0232",
                 "(divsint(dt(multsint(D0232))) - dt(D0232))"
                },
                {"CK0236", "D0236", "D0231 D0235",
                 "(D0231 + D0235)"
                },
                {"CK0237", "D0237", "D0229 D0236",
                 "(D0229 + D0236)"
                },
                {"CK0239", "D0239", "D0090 D0100",
                 "(D0100 - D0090)"
                },
                {"CK0241", "D0241", "D0237 D0240",
                 "(D0237 - D0240)"
                },
                {"CK0245", "D0245", "D0241 D0244",
                 "(D0241 - D0244)"
                },
                {"CK0249", "D0249", "D0246 D0248",
                 "(D0246 + D0248)"
                },
                {"CK0254", "D0254", "D0251 D0253",
                 "(D0251 + D0253)"
                },
                {"CK0256", "D0256", "D0250 D0255",
                 "(D0250 + D0255)"
                },
                {"CK0262", "D0262", "D0258 D0261",
                 "(D0258 + D0261)"
                },
                {"CK0264", "D0264", "D0256 D0263",
                 "(D0256 - D0263)"
                },
                {"CK0268", "D0268", "D0267",
                 "(divsint(dt(multsint(D0267))) - dt(D0267))"
                },
                {"CK0271", "D0271", "D0266 D0270",
                 "(D0266 + D0270)"
                },
                {"CK0273", "D0273", "D0264 D0272",
                 "(D0264 - D0272)"
                },
                {"CK0275", "D0275", "D0100 D0274",
                 "(D0100 - D0274)"
                },
                {"CK0278", "D0278", "D0273 D0277",
                 "(D0273 + D0277)"
                },
                {"CK0282", "D0282", "D0280 D0281",
                 "(D0280 - D0281)"
                },
                {"CK0284", "D0284", "D0278 D0283",
                 "(D0278 + D0283)"
                },
                {"CK0291", "D0291", "D0287 D0290",
                 "(D0287 + D0290)"
                },
                {"CK0293", "D0293", "D0285 D0292",
                 "(D0285 + D0292)"
                },
                {"CK0297", "D0297", "D0296",
                 "(divsint(dt(multsint(D0296))) - dt(D0296))"
                },
                {"CK0300", "D0300", "D0295 D0299",
                 "(D0295 + D0299)"
                },
                {"CK0303", "D0303", "D0293 D0302",
                 "(D0293 + D0302)"
                },
                {"CK0306", "D0306", "D0303 D0305",
                 "(D0303 + D0305)"
                },
                {"CK0308", "D0308", "D0249 D0307",
                 "(D0249 - D0307)"
                },
                {"CK0310", "D0310", "D0306 D0309",
                 "(D0306 + D0309)"
                },
                {"CK0317", "D0317", "D0314 D0316",
                 "(D0314 - D0316)"
                },
                {"CK0320", "D0320", "D0312 D0319",
                 "(D0312 + D0319)"
                },
                {"CK0321", "D0321", "D0311 D0320",
                 "(D0311 + D0320)"
                },
                {"CK0323", "D0323", "D0321 D0322",
                 "(D0321 - D0322)"
                },
                {"CK0325", "D0325", "D0323 D0324",
                 "(D0323 + D0324)"
                },
                {"CK0330", "D0330", "D0327 D0329",
                 "(D0327 - D0329)"
                },
                {"CK0332", "D0332", "D0325 D0331",
                 "(D0325 + D0331)"
                },
                {"CK0335", "D0335", "D0332 D0334",
                 "(D0332 + D0334)"
                },
                {"CK0342", "D0342", "D0339 D0341",
                 "(D0339 - D0341)"
                },
                {"CK0343", "D0343", "D0337 D0342",
                 "(D0337 + D0342)"
                },
                {"CK0344", "D0344", "D0336 D0343",
                 "(D0336 + D0343)"
                },
                {"CK0352", "D0352", "D0335 D0351",
                 "(D0335 + D0351)"
                },
            };
            return C;
        }

        /// Read a def into CONFIGURATION space.  Fetching the Val_domain
        /// is not enough -- indexing it is what converts, and a probe that
        /// only fetched returned two false negatives (round 108).
        inline void read_def(Kadath::System_of_eqs& syst,
                             const Kadath::Space& sp, const char* nm,
                             int dmin, int dmax)
        {
            for (int d = dmin; d <= dmax; d++) {
                const Kadath::Val_domain& v =
                    syst.give_val_def_scalar_domain(nm, d);
                Kadath::Index ix(sp.get_domain(d)->get_nbr_points());
                (void)v(ix);
            }
        }
    } // namespace finiteJ_detail

    /// The sub-def names, in dependency order, for reading values back.
    inline const std::vector<const char*>& finiteJ_names()
    {
        static const std::vector<const char*> N = [] {
            std::vector<const char*> v;
            for (const auto& d : finiteJ_detail::subdefs()) v.push_back(d.name);
            return v;
        }();
        return N;
    }

    /// The six equation names.
    inline const std::vector<const char*>& finiteJ_eq_names()
    {
        static const std::vector<const char*> N = [] {
            std::vector<const char*> v;
            for (const auto& e : finiteJ_detail::equations()) v.push_back(e.name);
            return v;
        }();
        return N;
    }

    /// The angular bases this emission was analysed under.  The caller
    /// MUST register the six unknowns in these bases: the basis lattice
    /// that decided every sum ordering assumed them, and if the run
    /// registers something else the analysis describes a different
    /// system.  Names, not integers, so a renumbering in the library
    /// cannot silently reinterpret them.
    inline const std::vector<std::pair<const char*, const char*>>&
    finiteJ_declared_basis()
    {
        static const std::vector<std::pair<const char*, const char*>> B = {
            {"PS", "COS_EVEN"},
            {"PH", "COS_EVEN"},
            {"QF", "COS_EVEN"},
            {"BR", "COS_EVEN"},
            {"BT", "SIN_EVEN"},
            {"QB", "COS_ODD"},
        };
        return B;
    }

    /// Sums reordered by --order-sums, which is seed-specific: see the
    /// header comment.  Empty means the emission was written without it.
    inline const std::vector<const char*>& finiteJ_ordered_sums()
    {
        static const std::vector<const char*> O = {
        };
        return O;
    }

    /// Emission-time AXIS PRECONDITION violations carried into the
    /// artefact: each is a divsint applied where the emitter could not
    /// show the operand vanishes on the axis.  Empty is the only
    /// acceptable state; a non-empty list means this header was written
    /// under --allow-axis-violations and the defs named here are wrong.
    inline const std::vector<const char*>& finiteJ_axis_violations()
    {
        static const std::vector<const char*> V = {
            "D0105: divsint applied at guaranteed sin-order 0",
            "D0105: divsint applied at guaranteed sin-order -1",
            "D0105: divsint applied at guaranteed sin-order -2",
            "D0105: divsint applied at guaranteed sin-order -3",
        };
        return V;
    }

    /**
     * Register the emission, keeping the read-state contract.
     *
     * read_defs = false deliberately BREAKS the contract.  It exists so a
     * caller can show finiteJ_check() catches the breach; nothing else
     * should ever pass it.
     */
    inline void finiteJ_register(Kadath::System_of_eqs& syst,
                                 const Kadath::Space& sp, int dmin, int dmax,
                                 bool read_defs = true)
    {
        for (const auto& d : finiteJ_detail::subdefs()) {
            syst.add_def((std::string(d.name) + " = " + d.def).c_str());
            if (read_defs)
                finiteJ_detail::read_def(syst, sp, d.name, dmin, dmax);
        }
        for (const auto& e : finiteJ_detail::equations()) {
            syst.add_def((std::string(e.name) + " = " + e.def).c_str());
            if (read_defs)
                finiteJ_detail::read_def(syst, sp, e.name, dmin, dmax);
        }
    }

    /**
     * THE CONTROL.  Re-register every sum with its operands READ first and
     * compare pointwise with the original.  Returns the worst relative
     * difference and throws above tol.
     *
     * ⚠ Reading the operands before re-parsing is the whole mechanism.  A
     * version that re-registers without reading puts both spellings in the
     * same evaluator state, and two spellings in one state cannot
     * discriminate a defect whose variable IS the state -- which is how
     * round 107 shipped a check weaker than it was reported to be.
     */
    inline double finiteJ_check(Kadath::System_of_eqs& syst,
                                const Kadath::Space& sp, int dmin, int dmax,
                                double tol = 1e-12)
    {
        double worst = 0.0;
        std::string worst_name;
        for (const auto& c : finiteJ_detail::checks()) {
            std::istringstream is(c.reads);
            for (std::string nm; is >> nm;)
                finiteJ_detail::read_def(syst, sp, nm.c_str(), dmin, dmax);
            syst.add_def((std::string(c.name) + " = " + c.def).c_str());
            double mx = 0.0, scale = 0.0;
            for (int d = dmin; d <= dmax; d++) {
                const Kadath::Val_domain& a =
                    syst.give_val_def_scalar_domain(c.of, d);
                const Kadath::Val_domain& b =
                    syst.give_val_def_scalar_domain(c.name, d);
                Kadath::Index ix(sp.get_domain(d)->get_nbr_points());
                do {
                    mx = std::max(mx, std::fabs(a(ix) - b(ix)));
                    scale = std::max(scale, std::fabs(a(ix)));
                } while (ix.inc());
            }
            const double rel = mx / std::max(scale, 1e-300);
            if (rel > worst) { worst = rel; worst_name = c.of; }
        }
        if (worst > tol)
            throw std::runtime_error(
                "finiteJ read-state contract broken: " + worst_name
                + " differs from its own re-expression by "
                + std::to_string(worst)
                + " -- the defs were registered without being read");
        return worst;
    }

} // namespace Trumpet
