/*
 * finiteJ_eqs.hpp -- GENERATED by scripts/finiteJ_emit.py.  Do not edit.
 *
 * ⚠ --q-regular: q = sin^2(theta) q~.  The unknown QF DENOTES q~ in this
 * emission (research round 578; code round 279), so q vanishes on the
 * axis by construction.  Build it as finiteJ_probe_qreg only.
 *
 * ⚠ --s-expand (code round 385, research round 793 task 1, A PROBE): the
 * shift-transport term S = rho beta . grad chi by the product rule in the
 * fields and their first / second derivatives (no derivative of a formed
 * chi).  Built only into finiteJ_probe_bulk2_sx (TRUMPET_SEXP).
 *
 * ⚠ --eq-regular (code round 393, research rounds 810-811, A PROBE): E_q's
 * twist group in the regular form [5 sin^4 Wh^2 psibar^-2 - 3 sin^4 QB_r^2
 * - 3 sin^2 W^2/r^2] / (4 psi2^4 r^4) on QB and divsint(BT) -- no explicit
 * 1/sin^4 -- so the q row can be registered UNWEIGHTED in theta.  Built only
 * into finiteJ_probe_bulk2_sxqr (TRUMPET_EQREG).
 *
 * The six finite-J equations as Kadath defs, emitted from the ASSEMBLY's
 * structure rather than from an expanded expression: where the assembly
 * applied lap2S the emission says lap2, instead of expanding and hoping to
 * recognise it again.
 *
 * Unknowns PS, PH, QF, BR, BT, QB.  Spin constant JJ.  There are NO sin or
 * cos FIELDS: round 103 measured that neither lies in the scalar COS_EVEN
 * span, so an add_cst holding one stores an alias.  Angular and radial
 * factors go through the coefficient-space operators instead, and
 *
 *     cot(theta) * X  ==  divsint(dt(multsint(X))) - dt(X)
 *
 * which the probe verified to 2e-16 on a field vanishing on the axis.
 *
 * Registered as 440 named sub-defs then the six equations: the parser has a
 * STACK-depth limit near 1000 characters that was not reproducible run to
 * run, so every piece here is kept far below it.
 *
 * ⚠ THE READ-STATE CONTRACT (round 108).  Kadath evaluates a sum
 * differently depending on whether its named operands have been READ --
 * indexed, which forces a Val_domain into configuration space -- before
 * the sum is parsed, and a def parsed in the wrong state does not recover
 * when its operands are read later.  Every sub-def below must therefore be
 * read immediately after it is registered.  That is why the def TEXT is not
 * exported: register through finiteJ_register(), which does it, and call
 * finiteJ_check(), which fails loudly if it was not done.  A requirement in
 * prose gets transcribed wrongly; this one is in the only function that can
 * reach the text.
 */
#pragma once

#include "For_Kadath/Array/headcpp.hpp"
#include "For_Kadath/Space/space.hpp"
#include "For_Kadath/System_of_eqs/system_of_eqs.hpp"

#include <algorithm>
#include <cmath>
#include <sstream>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

namespace Trumpet
{
    struct FiniteJEq { const char* name; const char* def; };

    /// One sum, re-expressed.  `reads` are the operands finiteJ_check()
    /// reads before re-parsing `def`, which is what lets it discriminate.
    struct FiniteJCheck {
        const char* name; const char* of; const char* reads; const char* def;
    };

    namespace finiteJ_detail
    {
        /// ⚠ The def TEXT.  Registering any of this by hand skips the read
        /// the evaluator needs; go through finiteJ_register() instead.
        inline const std::vector<FiniteJEq>& subdefs()
        {
            static const std::vector<FiniteJEq> D = {
                {"D0001",
                 "multsint(multsint(QF))"
                },
                {"D0002",
                 "multsint(multsint(multsint(multsint(QB))))"
                },
                {"D0003",
                 "(2 * (D0001))"
                },
                {"D0004",
                 "(1 / (PS))"
                },
                {"D0005",
                 "(1 / (PH))"
                },
                {"D0006",
                 "((1 / 2) * (log(PS)))"
                },
                {"D0007",
                 "dr(log(PH))"
                },
                {"D0008",
                 "dr(log(PS))"
                },
                {"D0009",
                 "(4 * (D0008))"
                },
                {"D0010",
                 "(D0007 - D0009)"
                },
                {"D0011",
                 "dt(log(PH))"
                },
                {"D0012",
                 "dt(log(PS))"
                },
                {"D0013",
                 "(4 * (D0012))"
                },
                {"D0014",
                 "(D0011 - D0013)"
                },
                {"D0015",
                 "dr(D0001)"
                },
                {"D0016",
                 "(2 * (D0015))"
                },
                {"D0017",
                 "(D0010 - D0016)"
                },
                {"D0018",
                 "dt(D0001)"
                },
                {"D0019",
                 "(2 * (D0018))"
                },
                {"D0020",
                 "(D0014 - D0019)"
                },
                {"D0021",
                 "dr(D0002)"
                },
                {"D0022",
                 "dt(D0002)"
                },
                {"D0023",
                 "(6*JJ * (multsint(multsint(multsint(ones)))))"
                },
                {"D0024",
                 "(D0022 + D0023)"
                },
                {"D0025",
                 "divr(divr(D0024))"
                },
                {"D0026",
                 "(PS * D0005)"
                },
                {"D0027",
                 "(BR * D0021)"
                },
                {"D0028",
                 "(BT * D0024)"
                },
                {"D0029",
                 "(D0027 + D0028)"
                },
                {"D0030",
                 "(D0026 * D0029)"
                },
                {"D0031",
                 "(-1 * (D0030))"
                },
                {"D0032",
                 "(D0031 * D0004)"
                },
                {"D0033",
                 "(-1 * (D0001))"
                },
                {"D0034",
                 "(D0032 * exp(D0033))"
                },
                {"D0035",
                 "dr(D0006)"
                },
                {"D0036",
                 "dt(D0006)"
                },
                {"D0037",
                 "(PS * D0005)"
                },
                {"D0038",
                 "(2 * (D0035))"
                },
                {"D0039",
                 "divr(ones)"
                },
                {"D0040",
                 "(D0038 + D0039)"
                },
                {"D0041",
                 "(BR * D0040)"
                },
                {"D0042",
                 "(2 * (D0036))"
                },
                {"D0043",
                 "(BT * D0042)"
                },
                {"D0044",
                 "(divsint(dt(multsint(BT))) - dt(BT))"
                },
                {"D0045",
                 "D0044"
                },
                {"D0046",
                 "(D0043 + D0045)"
                },
                {"D0047",
                 "(D0041 + D0046)"
                },
                {"D0048",
                 "(D0037 * D0047)"
                },
                {"D0049",
                 "(-1 * (D0048))"
                },
                {"D0050",
                 "dr(BR)"
                },
                {"D0051",
                 "dr(BT)"
                },
                {"D0052",
                 "divr(BT)"
                },
                {"D0053",
                 "(D0051 + D0052)"
                },
                {"D0054",
                 "dt(BR)"
                },
                {"D0055",
                 "(-1 * (multr(BT)))"
                },
                {"D0056",
                 "(D0054 + D0055)"
                },
                {"D0057",
                 "dt(BT)"
                },
                {"D0058",
                 "divr(BR)"
                },
                {"D0059",
                 "(D0057 + D0058)"
                },
                {"D0060",
                 "(D0050 + D0059)"
                },
                {"D0061",
                 "(2 * (D0050))"
                },
                {"D0062",
                 "(D0061 - D0060)"
                },
                {"D0063",
                 "divr(divr(D0059))"
                },
                {"D0064",
                 "(2 * (D0063))"
                },
                {"D0065",
                 "divr(divr(D0060))"
                },
                {"D0066",
                 "(D0064 - D0065)"
                },
                {"D0067",
                 "divr(divr(D0056))"
                },
                {"D0068",
                 "(D0053 + D0067)"
                },
                {"D0069",
                 "(PS * D0005)"
                },
                {"D0070",
                 "(D0069 * D0062)"
                },
                {"D0071",
                 "(PS * D0005)"
                },
                {"D0072",
                 "(D0071 * D0066)"
                },
                {"D0073",
                 "(PS * D0005)"
                },
                {"D0074",
                 "(D0073 * D0068)"
                },
                {"D0075",
                 "((1 / 2) * (D0070))"
                },
                {"D0076",
                 "((1 / 2) * (D0072))"
                },
                {"D0077",
                 "((1 / 2) * (D0074))"
                },
                {"D0078",
                 "(D0075 * D0075)"
                },
                {"D0079",
                 "(D0076 * D0076)"
                },
                {"D0080",
                 "D0079"
                },
                {"D0458",
                 "multr(multr(D0076))"
                },
                {"D0081",
                 "(D0458 * D0458)"
                },
                {"D0082",
                 "(D0078 + D0081)"
                },
                {"D0083",
                 "(D0077 * D0077)"
                },
                {"D0084",
                 "(2 * (D0083))"
                },
                {"D0085",
                 "multr(multr(D0084))"
                },
                {"D0086",
                 "(D0082 + D0085)"
                },
                {"D0087",
                 "dr(PS)"
                },
                {"D0088",
                 "dt(PS)"
                },
                {"D0089",
                 "(D0087 * D0004)"
                },
                {"D0090",
                 "(D0088 * D0004)"
                },
                {"D0091",
                 "dr(D0087)"
                },
                {"D0092",
                 "(D0091 * D0004)"
                },
                {"D0093",
                 "(D0089 * D0089)"
                },
                {"D0094",
                 "(D0092 - D0093)"
                },
                {"D0095",
                 "dt(D0088)"
                },
                {"D0096",
                 "(D0095 * D0004)"
                },
                {"D0097",
                 "(D0090 * D0090)"
                },
                {"D0098",
                 "(D0096 - D0097)"
                },
                {"D0099",
                 "dt(D0087)"
                },
                {"D0100",
                 "(D0099 * D0004)"
                },
                {"D0101",
                 "(D0089 * D0090)"
                },
                {"D0102",
                 "(D0100 - D0101)"
                },
                {"D0103",
                 "(PS * D0005)"
                },
                {"D0104",
                 "(D0087 * D0005)"
                },
                {"D0105",
                 "dr(PH)"
                },
                {"D0106",
                 "(PS * D0105)"
                },
                {"D0107",
                 "(D0106 * D0005)"
                },
                {"D0108",
                 "(D0107 * D0005)"
                },
                {"D0109",
                 "(D0104 - D0108)"
                },
                {"D0110",
                 "(D0088 * D0005)"
                },
                {"D0111",
                 "dt(PH)"
                },
                {"D0112",
                 "(PS * D0111)"
                },
                {"D0113",
                 "(D0112 * D0005)"
                },
                {"D0114",
                 "(D0113 * D0005)"
                },
                {"D0115",
                 "(D0110 - D0114)"
                },
                {"D0116",
                 "divr(ones)"
                },
                {"D0117",
                 "(D0089 + D0116)"
                },
                {"D0118",
                 "(BR * D0117)"
                },
                {"D0119",
                 "(BT * D0090)"
                },
                {"D0120",
                 "(divsint(dt(multsint(BT))) - dt(BT))"
                },
                {"D0121",
                 "D0120"
                },
                {"D0122",
                 "(D0119 + D0121)"
                },
                {"D0123",
                 "(D0118 + D0122)"
                },
                {"D0124",
                 "dr(BR)"
                },
                {"D0125",
                 "(D0124 * D0117)"
                },
                {"D0126",
                 "(-1 * (divr(divr(ones))))"
                },
                {"D0127",
                 "(D0094 + D0126)"
                },
                {"D0128",
                 "(BR * D0127)"
                },
                {"D0129",
                 "(D0125 + D0128)"
                },
                {"D0130",
                 "dr(BT)"
                },
                {"D0131",
                 "(D0130 * D0090)"
                },
                {"D0132",
                 "(divsint(dt(multsint(D0130))) - dt(D0130))"
                },
                {"D0133",
                 "D0132"
                },
                {"D0134",
                 "(D0131 + D0133)"
                },
                {"D0135",
                 "(D0129 + D0134)"
                },
                {"D0136",
                 "(BT * D0102)"
                },
                {"D0137",
                 "(D0135 + D0136)"
                },
                {"D0138",
                 "dt(BR)"
                },
                {"D0139",
                 "(D0138 * D0117)"
                },
                {"D0140",
                 "(BR * D0102)"
                },
                {"D0141",
                 "(D0139 + D0140)"
                },
                {"D0142",
                 "dt(BT)"
                },
                {"D0143",
                 "(D0142 * D0090)"
                },
                {"D0144",
                 "(D0141 + D0143)"
                },
                {"D0145",
                 "(BT * D0098)"
                },
                {"D0146",
                 "(D0144 + D0145)"
                },
                {"D0147",
                 "(divsint(dt(multsint(BT))) - dt(BT))"
                },
                {"D0148",
                 "D0147"
                },
                {"D0149",
                 "dt(D0148)"
                },
                {"D0150",
                 "(D0146 + D0149)"
                },
                {"D0151",
                 "(D0109 * D0123)"
                },
                {"D0152",
                 "(D0103 * D0137)"
                },
                {"D0153",
                 "(D0151 + D0152)"
                },
                {"D0154",
                 "(-1 * (D0153))"
                },
                {"D0155",
                 "(D0115 * D0123)"
                },
                {"D0156",
                 "(D0103 * D0150)"
                },
                {"D0157",
                 "(D0155 + D0156)"
                },
                {"D0158",
                 "(-1 * (D0157))"
                },
                {"D0159",
                 "(PS * D0005)"
                },
                {"D0160",
                 "(BR * D0154)"
                },
                {"D0161",
                 "(BT * D0158)"
                },
                {"D0162",
                 "(D0160 + D0161)"
                },
                {"D0163",
                 "(D0159 * D0162)"
                },
                {"D0164",
                 "(PS * D0005)"
                },
                {"D0165",
                 "dr(D0031)"
                },
                {"D0166",
                 "(BR * D0165)"
                },
                {"D0167",
                 "dt(D0031)"
                },
                {"D0168",
                 "(BT * D0167)"
                },
                {"D0169",
                 "(D0166 + D0168)"
                },
                {"D0170",
                 "(D0164 * D0169)"
                },
                {"D0171",
                 "(D0049 * D0049)"
                },
                {"D0172",
                 "((3 / 2) * (D0171))"
                },
                {"D0173",
                 "(D0086 + D0172)"
                },
                {"D0174",
                 "(PS * PS)"
                },
                {"D0175",
                 "(D0174 * PS)"
                },
                {"D0176",
                 "(D0175 * PS)"
                },
                {"D0177",
                 "(1 / (D0176))"
                },
                {"D0178",
                 "(PS * PS)"
                },
                {"D0179",
                 "(D0178 * exp(D0003))"
                },
                {"D0180",
                 "lap2(D0002)"
                },
                {"D0181",
                 "dr(D0002)"
                },
                {"D0182",
                 "divr(D0181)"
                },
                {"D0183",
                 "dt(D0002)"
                },
                {"D0184",
                 "(divsint(dt(multsint(D0183))) - dt(D0183))"
                },
                {"D0185",
                 "D0184"
                },
                {"D0186",
                 "divr(divr(D0185))"
                },
                {"D0187",
                 "(D0182 + D0186)"
                },
                {"D0188",
                 "(3 * (D0187))"
                },
                {"D0189",
                 "(D0180 - D0188)"
                },
                {"D0190",
                 "(D0021 * D0010)"
                },
                {"D0191",
                 "(D0189 + D0190)"
                },
                {"D0192",
                 "multr(multr(D0025))"
                },
                {"D0193",
                 "(D0192 * D0014)"
                },
                {"D0194",
                 "divr(divr(D0193))"
                },
                {"D0195",
                 "(D0191 + D0194)"
                },
                {"D0196",
                 "(D0031 * D0049)"
                },
                {"D0197",
                 "(4 * (D0196))"
                },
                {"D0198",
                 "(D0197 + D0170)"
                },
                {"D0199",
                 "(D0179 * D0198)"
                },
                {"D0200",
                 "(D0195 + D0199)"
                },
                {"D0201",
                 "dr(D0050)"
                },
                {"D0202",
                 "dt(D0056)"
                },
                {"D0203",
                 "(-1 * (multr(D0050)))"
                },
                {"D0204",
                 "(-1 * D0203)"
                },
                {"D0205",
                 "(-1 * (multr(D0059)))"
                },
                {"D0206",
                 "(D0204 + D0205)"
                },
                {"D0207",
                 "(D0202 + D0206)"
                },
                {"D0208",
                 "divr(divr(D0207))"
                },
                {"D0209",
                 "(D0201 + D0208)"
                },
                {"D0210",
                 "dr(D0053)"
                },
                {"D0211",
                 "divr(D0053)"
                },
                {"D0212",
                 "(D0210 + D0211)"
                },
                {"D0213",
                 "dt(D0059)"
                },
                {"D0214",
                 "divr(D0056)"
                },
                {"D0215",
                 "(-1 * (multr(D0053)))"
                },
                {"D0216",
                 "(D0214 - D0215)"
                },
                {"D0217",
                 "(D0213 + D0216)"
                },
                {"D0218",
                 "divr(divr(D0217))"
                },
                {"D0219",
                 "(D0212 + D0218)"
                },
                {"D0220",
                 "divr(D0062)"
                },
                {"D0221",
                 "multr(multr(D0068))"
                },
                {"D0222",
                 "(divsint(dt(multsint(D0221))) - dt(D0221))"
                },
                {"D0223",
                 "D0222"
                },
                {"D0224",
                 "divr(divr(D0223))"
                },
                {"D0225",
                 "(D0220 + D0224)"
                },
                {"D0226",
                 "(D0209 + D0225)"
                },
                {"D0227",
                 "(D0062 * D0017)"
                },
                {"D0228",
                 "multr(multr(D0068))"
                },
                {"D0229",
                 "(D0228 * D0020)"
                },
                {"D0230",
                 "divr(divr(D0229))"
                },
                {"D0231",
                 "(D0227 + D0230)"
                },
                {"D0232",
                 "(D0226 - D0231)"
                },
                {"D0233",
                 "(PH * D0031)"
                },
                {"D0234",
                 "(D0233 * D0021)"
                },
                {"D0235",
                 "(PS * PS)"
                },
                {"D0236",
                 "(D0235 * PS)"
                },
                {"D0237",
                 "(D0236 * PS)"
                },
                {"D0238",
                 "(D0237 * PS)"
                },
                {"D0239",
                 "(D0238 * PS)"
                },
                {"D0240",
                 "(D0239 * PS)"
                },
                {"D0241",
                 "(1 / (D0240))"
                },
                {"D0242",
                 "(D0234 * D0241)"
                },
                {"D0243",
                 "divsint(divsint(divsint(divsint(divr(divr(divr(divr(D0242))))))))"
                },
                {"D0244",
                 "(D0232 + D0243)"
                },
                {"D0245",
                 "(PH * D0004)"
                },
                {"D0246",
                 "(D0245 * D0049)"
                },
                {"D0247",
                 "D0246"
                },
                {"D0248",
                 "divr(D0247)"
                },
                {"D0249",
                 "(3 * (D0248))"
                },
                {"D0250",
                 "(D0244 + D0249)"
                },
                {"D0251",
                 "D0245"
                },
                {"D0252",
                 "dr(D0049)"
                },
                {"D0253",
                 "(D0251 * D0252)"
                },
                {"D0254",
                 "(D0250 + D0253)"
                },
                {"D0255",
                 "(D0245 * D0049)"
                },
                {"D0256",
                 "D0255"
                },
                {"D0257",
                 "(D0256 * D0035)"
                },
                {"D0258",
                 "(6 * (D0257))"
                },
                {"D0259",
                 "(D0254 + D0258)"
                },
                {"D0260",
                 "divr(D0068)"
                },
                {"D0261",
                 "multr(multr(D0066))"
                },
                {"D0267",
                 "(D0068 * D0017)"
                },
                {"D0268",
                 "multr(multr(D0066))"
                },
                {"D0269",
                 "(D0268 * D0020)"
                },
                {"D0270",
                 "divr(divr(D0269))"
                },
                {"D0271",
                 "(D0267 + D0270)"
                },
                {"D0273",
                 "(PH * D0031)"
                },
                {"D0274",
                 "(D0273 * D0025)"
                },
                {"D0275",
                 "(PS * PS)"
                },
                {"D0276",
                 "(D0275 * PS)"
                },
                {"D0277",
                 "(D0276 * PS)"
                },
                {"D0278",
                 "(D0277 * PS)"
                },
                {"D0279",
                 "(D0278 * PS)"
                },
                {"D0280",
                 "(D0279 * PS)"
                },
                {"D0281",
                 "(1 / (D0280))"
                },
                {"D0282",
                 "(D0274 * D0281)"
                },
                {"D0283",
                 "divsint(divsint(divsint(divsint(divr(divr(divr(divr(D0282))))))))"
                },
                {"D0285",
                 "(PH * D0004)"
                },
                {"D0286",
                 "(D0285 * D0049)"
                },
                {"D0287",
                 "divr(divr(D0286))"
                },
                {"D0292",
                 "divr(divr(D0285))"
                },
                {"D0293",
                 "dt(D0049)"
                },
                {"D0301",
                 "lap(PH)"
                },
                {"D0302",
                 "dr(PH)"
                },
                {"D0303",
                 "divr(D0302)"
                },
                {"D0304",
                 "dt(PH)"
                },
                {"D0305",
                 "(divsint(dt(multsint(D0304))) - dt(D0304))"
                },
                {"D0306",
                 "D0305"
                },
                {"D0307",
                 "divr(divr(D0306))"
                },
                {"D0308",
                 "(D0303 + D0307)"
                },
                {"D0309",
                 "(D0301 + D0308)"
                },
                {"D0310",
                 "(PH * D0179)"
                },
                {"D0311",
                 "(D0173 - D0163)"
                },
                {"D0312",
                 "(D0310 * D0311)"
                },
                {"D0313",
                 "(D0309 - D0312)"
                },
                {"D0314",
                 "(PH * D0034)"
                },
                {"D0315",
                 "(D0314 * D0034)"
                },
                {"D0316",
                 "(D0177 * D0315)"
                },
                {"D0317",
                 "((1 / 4) * (divsint(divsint(divsint(divsint(divr(divr(divr(divr(D0316))))))))))"
                },
                {"D0318",
                 "(D0313 - D0317)"
                },
                {"D0319",
                 "(D0021 * D0021)"
                },
                {"D0320",
                 "(D0024 * D0024)"
                },
                {"D0321",
                 "divr(divr(D0320))"
                },
                {"D0322",
                 "(D0319 + D0321)"
                },
                {"D0323",
                 "dr(QB)"
                },
                {"D0324",
                 "dt(QB)"
                },
                {"D0325",
                 "multsint(QB)"
                },
                {"D0326",
                 "dt(D0325)"
                },
                {"D0327",
                 "multsint(D0324)"
                },
                {"D0328",
                 "(D0326 - D0327)"
                },
                {"D0329",
                 "(4 * (D0328))"
                },
                {"D0330",
                 "(6*JJ * (ones))"
                },
                {"D0331",
                 "(D0330 + D0329)"
                },
                {"D0332",
                 "multsint(D0324)"
                },
                {"D0333",
                 "(D0331 + D0332)"
                },
                {"D0334",
                 "(PS * D0005)"
                },
                {"D0335",
                 "(BR * D0323)"
                },
                {"D0336",
                 "(divsint(BT) * D0333)"
                },
                {"D0337",
                 "(D0335 + D0336)"
                },
                {"D0338",
                 "(D0334 * D0337)"
                },
                {"D0339",
                 "(-1 * (D0338))"
                },
                {"D0340",
                 "(PS * PS)"
                },
                {"D0341",
                 "(2 * (D0001))"
                },
                {"D0342",
                 "(D0340 * exp(D0341))"
                },
                {"D0343",
                 "(1 / (D0342))"
                },
                {"D0344",
                 "(D0339 * D0339)"
                },
                {"D0345",
                 "(D0344 * D0343)"
                },
                {"D0346",
                 "(5 * (multsint(multsint(multsint(multsint(D0345))))))"
                },
                {"D0347",
                 "(D0323 * D0323)"
                },
                {"D0348",
                 "(3 * (multsint(multsint(multsint(multsint(D0347))))))"
                },
                {"D0349",
                 "(D0346 - D0348)"
                },
                {"D0350",
                 "(D0333 * D0333)"
                },
                {"D0351",
                 "(3 * (multsint(multsint(divr(divr(D0350))))))"
                },
                {"D0352",
                 "(D0349 - D0351)"
                },
                {"D0353",
                 "(PS * PS)"
                },
                {"D0354",
                 "(D0353 * PS)"
                },
                {"D0355",
                 "(D0354 * PS)"
                },
                {"D0356",
                 "(1 / (D0355))"
                },
                {"D0357",
                 "(D0352 * D0356)"
                },
                {"D0358",
                 "((1 / 4) * (divr(divr(divr(divr(D0357))))))"
                },
                {"D0359",
                 "lap2(D0001)"
                },
                {"D0360",
                 "(D0035 * D0035)"
                },
                {"D0361",
                 "(D0036 * D0036)"
                },
                {"D0362",
                 "divr(divr(D0361))"
                },
                {"D0363",
                 "(D0360 + D0362)"
                },
                {"D0364",
                 "(4 * (D0363))"
                },
                {"D0365",
                 "(D0359 + D0364)"
                },
                {"D0366",
                 "dr(log(PH))"
                },
                {"D0367",
                 "(D0035 * D0366)"
                },
                {"D0368",
                 "dt(log(PH))"
                },
                {"D0369",
                 "(D0036 * D0368)"
                },
                {"D0370",
                 "divr(divr(D0369))"
                },
                {"D0371",
                 "(D0367 + D0370)"
                },
                {"D0372",
                 "(4 * (D0371))"
                },
                {"D0373",
                 "(D0365 - D0372)"
                },
                {"D0374",
                 "dr(log(PH))"
                },
                {"D0375",
                 "divr(D0374)"
                },
                {"D0376",
                 "dt(log(PH))"
                },
                {"D0377",
                 "(divsint(dt(multsint(D0376))) - dt(D0376))"
                },
                {"D0378",
                 "D0377"
                },
                {"D0379",
                 "divr(divr(D0378))"
                },
                {"D0380",
                 "(D0375 + D0379)"
                },
                {"D0381",
                 "(2 * (D0380))"
                },
                {"D0382",
                 "(D0373 - D0381)"
                },
                {"D0383",
                 "(4 * (D0163))"
                },
                {"D0384",
                 "(D0173 - D0383)"
                },
                {"D0385",
                 "(D0179 * D0384)"
                },
                {"D0386",
                 "((1 / 2) * (D0385))"
                },
                {"D0387",
                 "(D0382 + D0386)"
                },
                {"D0388",
                 "(D0387 + D0358)"
                },
                {"D0389",
                 "lap(D0006)"
                },
                {"D0390",
                 "dr(PH)"
                },
                {"D0391",
                 "(D0035 * D0390)"
                },
                {"D0392",
                 "dt(PH)"
                },
                {"D0393",
                 "(D0036 * D0392)"
                },
                {"D0394",
                 "divr(divr(D0393))"
                },
                {"D0395",
                 "(D0391 + D0394)"
                },
                {"D0396",
                 "(D0395 * D0005)"
                },
                {"D0397",
                 "(D0389 + D0396)"
                },
                {"D0398",
                 "dr(PH)"
                },
                {"D0399",
                 "divr(D0398)"
                },
                {"D0400",
                 "dt(PH)"
                },
                {"D0401",
                 "(divsint(dt(multsint(D0400))) - dt(D0400))"
                },
                {"D0402",
                 "D0401"
                },
                {"D0403",
                 "divr(divr(D0402))"
                },
                {"D0404",
                 "(D0399 + D0403)"
                },
                {"D0405",
                 "(D0404 * D0005)"
                },
                {"D0406",
                 "((1 / 2) * (D0405))"
                },
                {"D0407",
                 "(D0397 + D0406)"
                },
                {"D0408",
                 "(D0179 * D0163)"
                },
                {"D0409",
                 "((1 / 2) * (D0408))"
                },
                {"D0410",
                 "(D0407 + D0409)"
                },
                {"D0411",
                 "(D0034 * D0034)"
                },
                {"D0412",
                 "(D0322 - D0411)"
                },
                {"D0413",
                 "(D0177 * D0412)"
                },
                {"D0414",
                 "((1 / 4) * (divsint(divsint(divsint(divsint(divr(divr(divr(divr(D0413))))))))))"
                },
                {"D0415",
                 "(D0410 + D0414)"
                },
                {"D0416",
                 "multsint(D0219)"
                },
                {"D0417",
                 "multsint(D0260)"
                },
                {"D0418",
                 "multsint(D0261)"
                },
                {"D0419",
                 "dt(D0418)"
                },
                {"D0420",
                 "dt(D0261)"
                },
                {"D0421",
                 "multsint(D0420)"
                },
                {"D0422",
                 "(D0419 - D0421)"
                },
                {"D0423",
                 "divr(D0422)"
                },
                {"D0424",
                 "divr(D0423)"
                },
                {"D0425",
                 "(D0417 + D0424)"
                },
                {"D0426",
                 "(D0416 + D0425)"
                },
                {"D0427",
                 "multsint(D0271)"
                },
                {"D0428",
                 "(D0426 - D0427)"
                },
                {"D0429",
                 "multsint(D0283)"
                },
                {"D0430",
                 "(D0428 + D0429)"
                },
                {"D0431",
                 "multsint(D0287)"
                },
                {"D0432",
                 "dt(D0431)"
                },
                {"D0433",
                 "dt(D0287)"
                },
                {"D0434",
                 "multsint(D0433)"
                },
                {"D0435",
                 "(D0432 - D0434)"
                },
                {"D0436",
                 "(3 * (D0435))"
                },
                {"D0437",
                 "(D0430 + D0436)"
                },
                {"D0438",
                 "multsint(D0293)"
                },
                {"D0439",
                 "(D0292 * D0438)"
                },
                {"D0440",
                 "(D0437 + D0439)"
                },
                {"D0441",
                 "multsint(D0041)"
                },
                {"D0442",
                 "multsint(D0043)"
                },
                {"D0443",
                 "multsint(BT)"
                },
                {"D0444",
                 "dt(D0443)"
                },
                {"D0445",
                 "dt(BT)"
                },
                {"D0446",
                 "multsint(D0445)"
                },
                {"D0447",
                 "(D0444 - D0446)"
                },
                {"D0448",
                 "(D0442 + D0447)"
                },
                {"D0449",
                 "(D0441 + D0448)"
                },
                {"D0450",
                 "(D0037 * D0449)"
                },
                {"D0451",
                 "(-1 * (D0450))"
                },
                {"D0452",
                 "(D0285 * D0451)"
                },
                {"D0453",
                 "divr(D0452)"
                },
                {"D0454",
                 "divr(D0453)"
                },
                {"D0455",
                 "(D0454 * D0036)"
                },
                {"D0456",
                 "(6 * (D0455))"
                },
                {"D0457",
                 "(D0440 + D0456)"
                },
            };
            return D;
        }

        inline const std::vector<FiniteJEq>& equations()
        {
            static const std::vector<FiniteJEq> E = {
                {"EQTW",
                 "D0200"
                },
                {"ESHR",
                 "D0259"
                },
                {"ESHT",
                 "D0457"
                },
                {"EPHI",
                 "D0318"
                },
                {"EQFN",
                 "D0388"
                },
                {"ESIG",
                 "D0415"
                },
            };
            return E;
        }

        inline const std::vector<FiniteJCheck>& checks()
        {
            static const std::vector<FiniteJCheck> C = {
                {"CK0010", "D0010", "D0007 D0009",
                 "(D0007 - D0009)"
                },
                {"CK0014", "D0014", "D0011 D0013",
                 "(D0011 - D0013)"
                },
                {"CK0017", "D0017", "D0010 D0016",
                 "(D0010 - D0016)"
                },
                {"CK0020", "D0020", "D0014 D0019",
                 "(D0014 - D0019)"
                },
                {"CK0024", "D0024", "D0022 D0023",
                 "(D0022 + D0023)"
                },
                {"CK0029", "D0029", "D0027 D0028",
                 "(D0027 + D0028)"
                },
                {"CK0040", "D0040", "D0038 D0039",
                 "(D0038 + D0039)"
                },
                {"CK0044", "D0044", "",
                 "(divsint(dt(multsint(BT))) - dt(BT))"
                },
                {"CK0046", "D0046", "D0043 D0045",
                 "(D0043 + D0045)"
                },
                {"CK0047", "D0047", "D0041 D0046",
                 "(D0041 + D0046)"
                },
                {"CK0053", "D0053", "D0051 D0052",
                 "(D0051 + D0052)"
                },
                {"CK0056", "D0056", "D0054 D0055",
                 "(D0054 + D0055)"
                },
                {"CK0059", "D0059", "D0057 D0058",
                 "(D0057 + D0058)"
                },
                {"CK0060", "D0060", "D0050 D0059",
                 "(D0050 + D0059)"
                },
                {"CK0062", "D0062", "D0060 D0061",
                 "(D0061 - D0060)"
                },
                {"CK0066", "D0066", "D0064 D0065",
                 "(D0064 - D0065)"
                },
                {"CK0068", "D0068", "D0053 D0067",
                 "(D0053 + D0067)"
                },
                {"CK0082", "D0082", "D0078 D0081",
                 "(D0078 + D0081)"
                },
                {"CK0086", "D0086", "D0082 D0085",
                 "(D0082 + D0085)"
                },
                {"CK0094", "D0094", "D0092 D0093",
                 "(D0092 - D0093)"
                },
                {"CK0098", "D0098", "D0096 D0097",
                 "(D0096 - D0097)"
                },
                {"CK0102", "D0102", "D0100 D0101",
                 "(D0100 - D0101)"
                },
                {"CK0109", "D0109", "D0104 D0108",
                 "(D0104 - D0108)"
                },
                {"CK0115", "D0115", "D0110 D0114",
                 "(D0110 - D0114)"
                },
                {"CK0117", "D0117", "D0089 D0116",
                 "(D0089 + D0116)"
                },
                {"CK0120", "D0120", "",
                 "(divsint(dt(multsint(BT))) - dt(BT))"
                },
                {"CK0122", "D0122", "D0119 D0121",
                 "(D0119 + D0121)"
                },
                {"CK0123", "D0123", "D0118 D0122",
                 "(D0118 + D0122)"
                },
                {"CK0127", "D0127", "D0094 D0126",
                 "(D0094 + D0126)"
                },
                {"CK0129", "D0129", "D0125 D0128",
                 "(D0125 + D0128)"
                },
                {"CK0132", "D0132", "D0130",
                 "(divsint(dt(multsint(D0130))) - dt(D0130))"
                },
                {"CK0134", "D0134", "D0131 D0133",
                 "(D0131 + D0133)"
                },
                {"CK0135", "D0135", "D0129 D0134",
                 "(D0129 + D0134)"
                },
                {"CK0137", "D0137", "D0135 D0136",
                 "(D0135 + D0136)"
                },
                {"CK0141", "D0141", "D0139 D0140",
                 "(D0139 + D0140)"
                },
                {"CK0144", "D0144", "D0141 D0143",
                 "(D0141 + D0143)"
                },
                {"CK0146", "D0146", "D0144 D0145",
                 "(D0144 + D0145)"
                },
                {"CK0147", "D0147", "",
                 "(divsint(dt(multsint(BT))) - dt(BT))"
                },
                {"CK0150", "D0150", "D0146 D0149",
                 "(D0146 + D0149)"
                },
                {"CK0153", "D0153", "D0151 D0152",
                 "(D0151 + D0152)"
                },
                {"CK0157", "D0157", "D0155 D0156",
                 "(D0155 + D0156)"
                },
                {"CK0162", "D0162", "D0160 D0161",
                 "(D0160 + D0161)"
                },
                {"CK0169", "D0169", "D0166 D0168",
                 "(D0166 + D0168)"
                },
                {"CK0173", "D0173", "D0086 D0172",
                 "(D0086 + D0172)"
                },
                {"CK0184", "D0184", "D0183",
                 "(divsint(dt(multsint(D0183))) - dt(D0183))"
                },
                {"CK0187", "D0187", "D0182 D0186",
                 "(D0182 + D0186)"
                },
                {"CK0189", "D0189", "D0180 D0188",
                 "(D0180 - D0188)"
                },
                {"CK0191", "D0191", "D0189 D0190",
                 "(D0189 + D0190)"
                },
                {"CK0195", "D0195", "D0191 D0194",
                 "(D0191 + D0194)"
                },
                {"CK0198", "D0198", "D0170 D0197",
                 "(D0197 + D0170)"
                },
                {"CK0200", "D0200", "D0195 D0199",
                 "(D0195 + D0199)"
                },
                {"CK0206", "D0206", "D0204 D0205",
                 "(D0204 + D0205)"
                },
                {"CK0207", "D0207", "D0202 D0206",
                 "(D0202 + D0206)"
                },
                {"CK0209", "D0209", "D0201 D0208",
                 "(D0201 + D0208)"
                },
                {"CK0212", "D0212", "D0210 D0211",
                 "(D0210 + D0211)"
                },
                {"CK0216", "D0216", "D0214 D0215",
                 "(D0214 - D0215)"
                },
                {"CK0217", "D0217", "D0213 D0216",
                 "(D0213 + D0216)"
                },
                {"CK0219", "D0219", "D0212 D0218",
                 "(D0212 + D0218)"
                },
                {"CK0222", "D0222", "D0221",
                 "(divsint(dt(multsint(D0221))) - dt(D0221))"
                },
                {"CK0225", "D0225", "D0220 D0224",
                 "(D0220 + D0224)"
                },
                {"CK0226", "D0226", "D0209 D0225",
                 "(D0209 + D0225)"
                },
                {"CK0231", "D0231", "D0227 D0230",
                 "(D0227 + D0230)"
                },
                {"CK0232", "D0232", "D0226 D0231",
                 "(D0226 - D0231)"
                },
                {"CK0244", "D0244", "D0232 D0243",
                 "(D0232 + D0243)"
                },
                {"CK0250", "D0250", "D0244 D0249",
                 "(D0244 + D0249)"
                },
                {"CK0254", "D0254", "D0250 D0253",
                 "(D0250 + D0253)"
                },
                {"CK0259", "D0259", "D0254 D0258",
                 "(D0254 + D0258)"
                },
                {"CK0271", "D0271", "D0267 D0270",
                 "(D0267 + D0270)"
                },
                {"CK0305", "D0305", "D0304",
                 "(divsint(dt(multsint(D0304))) - dt(D0304))"
                },
                {"CK0308", "D0308", "D0303 D0307",
                 "(D0303 + D0307)"
                },
                {"CK0309", "D0309", "D0301 D0308",
                 "(D0301 + D0308)"
                },
                {"CK0311", "D0311", "D0163 D0173",
                 "(D0173 - D0163)"
                },
                {"CK0313", "D0313", "D0309 D0312",
                 "(D0309 - D0312)"
                },
                {"CK0318", "D0318", "D0313 D0317",
                 "(D0313 - D0317)"
                },
                {"CK0322", "D0322", "D0319 D0321",
                 "(D0319 + D0321)"
                },
                {"CK0328", "D0328", "D0326 D0327",
                 "(D0326 - D0327)"
                },
                {"CK0331", "D0331", "D0329 D0330",
                 "(D0330 + D0329)"
                },
                {"CK0333", "D0333", "D0331 D0332",
                 "(D0331 + D0332)"
                },
                {"CK0337", "D0337", "D0335 D0336",
                 "(D0335 + D0336)"
                },
                {"CK0349", "D0349", "D0346 D0348",
                 "(D0346 - D0348)"
                },
                {"CK0352", "D0352", "D0349 D0351",
                 "(D0349 - D0351)"
                },
                {"CK0363", "D0363", "D0360 D0362",
                 "(D0360 + D0362)"
                },
                {"CK0365", "D0365", "D0359 D0364",
                 "(D0359 + D0364)"
                },
                {"CK0371", "D0371", "D0367 D0370",
                 "(D0367 + D0370)"
                },
                {"CK0373", "D0373", "D0365 D0372",
                 "(D0365 - D0372)"
                },
                {"CK0377", "D0377", "D0376",
                 "(divsint(dt(multsint(D0376))) - dt(D0376))"
                },
                {"CK0380", "D0380", "D0375 D0379",
                 "(D0375 + D0379)"
                },
                {"CK0382", "D0382", "D0373 D0381",
                 "(D0373 - D0381)"
                },
                {"CK0384", "D0384", "D0173 D0383",
                 "(D0173 - D0383)"
                },
                {"CK0387", "D0387", "D0382 D0386",
                 "(D0382 + D0386)"
                },
                {"CK0388", "D0388", "D0358 D0387",
                 "(D0387 + D0358)"
                },
                {"CK0395", "D0395", "D0391 D0394",
                 "(D0391 + D0394)"
                },
                {"CK0397", "D0397", "D0389 D0396",
                 "(D0389 + D0396)"
                },
                {"CK0401", "D0401", "D0400",
                 "(divsint(dt(multsint(D0400))) - dt(D0400))"
                },
                {"CK0404", "D0404", "D0399 D0403",
                 "(D0399 + D0403)"
                },
                {"CK0407", "D0407", "D0397 D0406",
                 "(D0397 + D0406)"
                },
                {"CK0410", "D0410", "D0407 D0409",
                 "(D0407 + D0409)"
                },
                {"CK0412", "D0412", "D0322 D0411",
                 "(D0322 - D0411)"
                },
                {"CK0415", "D0415", "D0410 D0414",
                 "(D0410 + D0414)"
                },
                {"CK0422", "D0422", "D0419 D0421",
                 "(D0419 - D0421)"
                },
                {"CK0425", "D0425", "D0417 D0424",
                 "(D0417 + D0424)"
                },
                {"CK0426", "D0426", "D0416 D0425",
                 "(D0416 + D0425)"
                },
                {"CK0428", "D0428", "D0426 D0427",
                 "(D0426 - D0427)"
                },
                {"CK0430", "D0430", "D0428 D0429",
                 "(D0428 + D0429)"
                },
                {"CK0435", "D0435", "D0432 D0434",
                 "(D0432 - D0434)"
                },
                {"CK0437", "D0437", "D0430 D0436",
                 "(D0430 + D0436)"
                },
                {"CK0440", "D0440", "D0437 D0439",
                 "(D0437 + D0439)"
                },
                {"CK0447", "D0447", "D0444 D0446",
                 "(D0444 - D0446)"
                },
                {"CK0448", "D0448", "D0442 D0447",
                 "(D0442 + D0447)"
                },
                {"CK0449", "D0449", "D0441 D0448",
                 "(D0441 + D0448)"
                },
                {"CK0457", "D0457", "D0440 D0456",
                 "(D0440 + D0456)"
                },
            };
            return C;
        }

        /// Read a def into CONFIGURATION space.  Fetching the Val_domain
        /// is not enough -- indexing it is what converts, and a probe that
        /// only fetched returned two false negatives (round 108).
        inline void read_def(Kadath::System_of_eqs& syst,
                             const Kadath::Space& sp, const char* nm,
                             int dmin, int dmax)
        {
            for (int d = dmin; d <= dmax; d++) {
                const Kadath::Val_domain& v =
                    syst.give_val_def_scalar_domain(nm, d);
                Kadath::Index ix(sp.get_domain(d)->get_nbr_points());
                (void)v(ix);
            }
        }
    } // namespace finiteJ_detail

    /// The sub-def names, in dependency order, for reading values back.
    inline const std::vector<const char*>& finiteJ_names()
    {
        static const std::vector<const char*> N = [] {
            std::vector<const char*> v;
            for (const auto& d : finiteJ_detail::subdefs()) v.push_back(d.name);
            return v;
        }();
        return N;
    }

    /// The six equation names.
    inline const std::vector<const char*>& finiteJ_eq_names()
    {
        static const std::vector<const char*> N = [] {
            std::vector<const char*> v;
            for (const auto& e : finiteJ_detail::equations()) v.push_back(e.name);
            return v;
        }();
        return N;
    }

    /// The angular bases this emission was analysed under.  The caller
    /// MUST register the six unknowns in these bases: the basis lattice
    /// that decided every sum ordering assumed them, and if the run
    /// registers something else the analysis describes a different
    /// system.  Names, not integers, so a renumbering in the library
    /// cannot silently reinterpret them.
    inline const std::vector<std::pair<const char*, const char*>>&
    finiteJ_declared_basis()
    {
        static const std::vector<std::pair<const char*, const char*>> B = {
            {"PS", "COS_EVEN"},
            {"PH", "COS_EVEN"},
            {"QF", "COS_EVEN"},
            {"BR", "COS_EVEN"},
            {"BT", "SIN_EVEN"},
            {"QB", "COS_ODD"},
        };
        return B;
    }

    /// Sums reordered by --order-sums, which is seed-specific: see the
    /// header comment.  Empty means the emission was written without it.
    inline const std::vector<const char*>& finiteJ_ordered_sums()
    {
        static const std::vector<const char*> O = {
        };
        return O;
    }

    /// Emission-time AXIS PRECONDITION violations carried into the
    /// artefact: each is a divsint applied where the emitter could not
    /// show the operand vanishes on the axis.  Empty is the only
    /// acceptable state, and since round 342 it is the only reachable
    /// one: the emitter refuses to write a violating emission at all.
    inline const std::vector<const char*>& finiteJ_axis_violations()
    {
        static const std::vector<const char*> V = {
        };
        return V;
    }

    /**
     * Register the emission, keeping the read-state contract.
     *
     * read_defs = false deliberately BREAKS the contract.  It exists so a
     * caller can show finiteJ_check() catches the breach; nothing else
     * should ever pass it.
     */
    inline void finiteJ_register(Kadath::System_of_eqs& syst,
                                 const Kadath::Space& sp, int dmin, int dmax,
                                 bool read_defs = true)
    {
        for (const auto& d : finiteJ_detail::subdefs()) {
            syst.add_def((std::string(d.name) + " = " + d.def).c_str());
            if (read_defs)
                finiteJ_detail::read_def(syst, sp, d.name, dmin, dmax);
        }
        for (const auto& e : finiteJ_detail::equations()) {
            syst.add_def((std::string(e.name) + " = " + e.def).c_str());
            if (read_defs)
                finiteJ_detail::read_def(syst, sp, e.name, dmin, dmax);
        }
    }

    /**
     * THE CONTROL.  Re-register every sum with its operands READ first and
     * compare pointwise with the original.  Returns the worst relative
     * difference and throws above tol.
     *
     * ⚠ Reading the operands before re-parsing is the whole mechanism.  A
     * version that re-registers without reading puts both spellings in the
     * same evaluator state, and two spellings in one state cannot
     * discriminate a defect whose variable IS the state -- which is how
     * round 107 shipped a check weaker than it was reported to be.
     */
    inline double finiteJ_check(Kadath::System_of_eqs& syst,
                                const Kadath::Space& sp, int dmin, int dmax,
                                double tol = 1e-12)
    {
        double worst = 0.0;
        std::string worst_name;
        for (const auto& c : finiteJ_detail::checks()) {
            std::istringstream is(c.reads);
            for (std::string nm; is >> nm;)
                finiteJ_detail::read_def(syst, sp, nm.c_str(), dmin, dmax);
            syst.add_def((std::string(c.name) + " = " + c.def).c_str());
            double mx = 0.0, scale = 0.0;
            for (int d = dmin; d <= dmax; d++) {
                const Kadath::Val_domain& a =
                    syst.give_val_def_scalar_domain(c.of, d);
                const Kadath::Val_domain& b =
                    syst.give_val_def_scalar_domain(c.name, d);
                Kadath::Index ix(sp.get_domain(d)->get_nbr_points());
                do {
                    mx = std::max(mx, std::fabs(a(ix) - b(ix)));
                    scale = std::max(scale, std::fabs(a(ix)));
                } while (ix.inc());
            }
            const double rel = mx / std::max(scale, 1e-300);
            if (rel > worst) { worst = rel; worst_name = c.of; }
        }
        if (worst > tol)
            throw std::runtime_error(
                "finiteJ read-state contract broken: " + worst_name
                + " differs from its own re-expression by "
                + std::to_string(worst)
                + " -- the defs were registered without being read");
        return worst;
    }

} // namespace Trumpet
