/*
 * finiteJ_eqs.hpp -- GENERATED by scripts/finiteJ_emit.py.  Do not edit.
 *
 * ⚠ --q-regular: q = sin^2(theta) q~.  The unknown QF DENOTES q~ in this
 * emission (research round 578; code round 279), so q vanishes on the
 * axis by construction.  Build it as finiteJ_probe_qreg only.
 *
 * ⚠ --c3 (code round 384, research ruling H2 PREPARED, NOT ADOPTED): the
 * C3 twist terms of rounds 728 / 733 -- bOmw = Omw psi2 e^q, the shift
 * Omega_omega term / psi2^5, E_Phi's -bOmw^2 Ncal doubled.  Built only
 * into finiteJ_probe_bulk2_c3 (TRUMPET_C3).
 *
 * The six finite-J equations as Kadath defs, emitted from the ASSEMBLY's
 * structure rather than from an expanded expression: where the assembly
 * applied lap2S the emission says lap2, instead of expanding and hoping to
 * recognise it again.
 *
 * Unknowns PS, PH, QF, BR, BT, QB.  Spin constant JJ.  There are NO sin or
 * cos FIELDS: round 103 measured that neither lies in the scalar COS_EVEN
 * span, so an add_cst holding one stores an alias.  Angular and radial
 * factors go through the coefficient-space operators instead, and
 *
 *     cot(theta) * X  ==  divsint(dt(multsint(X))) - dt(X)
 *
 * which the probe verified to 2e-16 on a field vanishing on the axis.
 *
 * Registered as 336 named sub-defs then the six equations: the parser has a
 * STACK-depth limit near 1000 characters that was not reproducible run to
 * run, so every piece here is kept far below it.
 *
 * ⚠ THE READ-STATE CONTRACT (round 108).  Kadath evaluates a sum
 * differently depending on whether its named operands have been READ --
 * indexed, which forces a Val_domain into configuration space -- before
 * the sum is parsed, and a def parsed in the wrong state does not recover
 * when its operands are read later.  Every sub-def below must therefore be
 * read immediately after it is registered.  That is why the def TEXT is not
 * exported: register through finiteJ_register(), which does it, and call
 * finiteJ_check(), which fails loudly if it was not done.  A requirement in
 * prose gets transcribed wrongly; this one is in the only function that can
 * reach the text.
 */
#pragma once

#include "For_Kadath/Array/headcpp.hpp"
#include "For_Kadath/Space/space.hpp"
#include "For_Kadath/System_of_eqs/system_of_eqs.hpp"

#include <algorithm>
#include <cmath>
#include <sstream>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

namespace Trumpet
{
    struct FiniteJEq { const char* name; const char* def; };

    /// One sum, re-expressed.  `reads` are the operands finiteJ_check()
    /// reads before re-parsing `def`, which is what lets it discriminate.
    struct FiniteJCheck {
        const char* name; const char* of; const char* reads; const char* def;
    };

    namespace finiteJ_detail
    {
        /// ⚠ The def TEXT.  Registering any of this by hand skips the read
        /// the evaluator needs; go through finiteJ_register() instead.
        inline const std::vector<FiniteJEq>& subdefs()
        {
            static const std::vector<FiniteJEq> D = {
                {"D0001",
                 "multsint(multsint(QF))"
                },
                {"D0002",
                 "multsint(multsint(multsint(multsint(QB))))"
                },
                {"D0003",
                 "(2 * (D0001))"
                },
                {"D0004",
                 "(1 / (PS))"
                },
                {"D0005",
                 "(1 / (PH))"
                },
                {"D0006",
                 "((1 / 2) * (log(PS)))"
                },
                {"D0007",
                 "dr(log(PH))"
                },
                {"D0008",
                 "dr(log(PS))"
                },
                {"D0009",
                 "(4 * (D0008))"
                },
                {"D0010",
                 "(D0007 - D0009)"
                },
                {"D0011",
                 "dt(log(PH))"
                },
                {"D0012",
                 "dt(log(PS))"
                },
                {"D0013",
                 "(4 * (D0012))"
                },
                {"D0014",
                 "(D0011 - D0013)"
                },
                {"D0015",
                 "dr(D0001)"
                },
                {"D0016",
                 "(2 * (D0015))"
                },
                {"D0017",
                 "(D0010 - D0016)"
                },
                {"D0018",
                 "dt(D0001)"
                },
                {"D0019",
                 "(2 * (D0018))"
                },
                {"D0020",
                 "(D0014 - D0019)"
                },
                {"D0021",
                 "dr(D0002)"
                },
                {"D0022",
                 "dt(D0002)"
                },
                {"D0023",
                 "(6*JJ * (multsint(multsint(multsint(ones)))))"
                },
                {"D0024",
                 "(D0022 + D0023)"
                },
                {"D0025",
                 "divr(divr(D0024))"
                },
                {"D0026",
                 "(PS * D0005)"
                },
                {"D0027",
                 "(BR * D0021)"
                },
                {"D0028",
                 "(BT * D0024)"
                },
                {"D0029",
                 "(D0027 + D0028)"
                },
                {"D0030",
                 "(D0026 * D0029)"
                },
                {"D0031",
                 "(-1 * (D0030))"
                },
                {"D0032",
                 "(D0031 * PS)"
                },
                {"D0033",
                 "(D0032 * exp(D0001))"
                },
                {"D0034",
                 "dr(D0006)"
                },
                {"D0035",
                 "dt(D0006)"
                },
                {"D0036",
                 "(PS * D0005)"
                },
                {"D0037",
                 "(2 * (D0034))"
                },
                {"D0038",
                 "divr(ones)"
                },
                {"D0039",
                 "(D0037 + D0038)"
                },
                {"D0040",
                 "(BR * D0039)"
                },
                {"D0041",
                 "(2 * (D0035))"
                },
                {"D0042",
                 "(BT * D0041)"
                },
                {"D0043",
                 "(divsint(dt(multsint(BT))) - dt(BT))"
                },
                {"D0044",
                 "D0043"
                },
                {"D0045",
                 "(D0042 + D0044)"
                },
                {"D0046",
                 "(D0040 + D0045)"
                },
                {"D0047",
                 "(D0036 * D0046)"
                },
                {"D0048",
                 "(-1 * (D0047))"
                },
                {"D0049",
                 "dr(BR)"
                },
                {"D0050",
                 "dr(BT)"
                },
                {"D0051",
                 "divr(BT)"
                },
                {"D0052",
                 "(D0050 + D0051)"
                },
                {"D0053",
                 "dt(BR)"
                },
                {"D0054",
                 "(-1 * (multr(BT)))"
                },
                {"D0055",
                 "(D0053 + D0054)"
                },
                {"D0056",
                 "dt(BT)"
                },
                {"D0057",
                 "divr(BR)"
                },
                {"D0058",
                 "(D0056 + D0057)"
                },
                {"D0059",
                 "(D0049 + D0058)"
                },
                {"D0060",
                 "(2 * (D0049))"
                },
                {"D0061",
                 "(D0060 - D0059)"
                },
                {"D0062",
                 "divr(divr(D0058))"
                },
                {"D0063",
                 "(2 * (D0062))"
                },
                {"D0064",
                 "divr(divr(D0059))"
                },
                {"D0065",
                 "(D0063 - D0064)"
                },
                {"D0066",
                 "divr(divr(D0055))"
                },
                {"D0067",
                 "(D0052 + D0066)"
                },
                {"D0068",
                 "(PS * D0005)"
                },
                {"D0069",
                 "(D0068 * D0061)"
                },
                {"D0070",
                 "(PS * D0005)"
                },
                {"D0071",
                 "(D0070 * D0065)"
                },
                {"D0072",
                 "(PS * D0005)"
                },
                {"D0073",
                 "(D0072 * D0067)"
                },
                {"D0074",
                 "((1 / 2) * (D0069))"
                },
                {"D0075",
                 "((1 / 2) * (D0071))"
                },
                {"D0076",
                 "((1 / 2) * (D0073))"
                },
                {"D0077",
                 "(D0074 * D0074)"
                },
                {"D0078",
                 "(D0075 * D0075)"
                },
                {"D0079",
                 "D0078"
                },
                {"D0354",
                 "multr(multr(D0075))"
                },
                {"D0080",
                 "(D0354 * D0354)"
                },
                {"D0081",
                 "(D0077 + D0080)"
                },
                {"D0082",
                 "(D0076 * D0076)"
                },
                {"D0083",
                 "(2 * (D0082))"
                },
                {"D0084",
                 "multr(multr(D0083))"
                },
                {"D0085",
                 "(D0081 + D0084)"
                },
                {"D0086",
                 "(PS * D0005)"
                },
                {"D0087",
                 "dr(D0048)"
                },
                {"D0088",
                 "(BR * D0087)"
                },
                {"D0089",
                 "dt(D0048)"
                },
                {"D0090",
                 "(BT * D0089)"
                },
                {"D0091",
                 "(D0088 + D0090)"
                },
                {"D0092",
                 "(D0086 * D0091)"
                },
                {"D0093",
                 "(PS * D0005)"
                },
                {"D0094",
                 "dr(D0031)"
                },
                {"D0095",
                 "(BR * D0094)"
                },
                {"D0096",
                 "dt(D0031)"
                },
                {"D0097",
                 "(BT * D0096)"
                },
                {"D0098",
                 "(D0095 + D0097)"
                },
                {"D0099",
                 "(D0093 * D0098)"
                },
                {"D0100",
                 "(D0048 * D0048)"
                },
                {"D0101",
                 "((3 / 2) * (D0100))"
                },
                {"D0102",
                 "(D0085 + D0101)"
                },
                {"D0103",
                 "(PS * PS)"
                },
                {"D0104",
                 "(D0103 * PS)"
                },
                {"D0105",
                 "(D0104 * PS)"
                },
                {"D0106",
                 "(1 / (D0105))"
                },
                {"D0107",
                 "(PS * PS)"
                },
                {"D0108",
                 "(D0107 * exp(D0003))"
                },
                {"D0109",
                 "lap2(D0002)"
                },
                {"D0110",
                 "dr(D0002)"
                },
                {"D0111",
                 "divr(D0110)"
                },
                {"D0112",
                 "dt(D0002)"
                },
                {"D0113",
                 "(divsint(dt(multsint(D0112))) - dt(D0112))"
                },
                {"D0114",
                 "D0113"
                },
                {"D0115",
                 "divr(divr(D0114))"
                },
                {"D0116",
                 "(D0111 + D0115)"
                },
                {"D0117",
                 "(3 * (D0116))"
                },
                {"D0118",
                 "(D0109 - D0117)"
                },
                {"D0119",
                 "(D0021 * D0010)"
                },
                {"D0120",
                 "(D0118 + D0119)"
                },
                {"D0121",
                 "multr(multr(D0025))"
                },
                {"D0122",
                 "(D0121 * D0014)"
                },
                {"D0123",
                 "divr(divr(D0122))"
                },
                {"D0124",
                 "(D0120 + D0123)"
                },
                {"D0125",
                 "(D0031 * D0048)"
                },
                {"D0126",
                 "(4 * (D0125))"
                },
                {"D0127",
                 "(D0126 + D0099)"
                },
                {"D0128",
                 "(D0108 * D0127)"
                },
                {"D0129",
                 "(D0124 + D0128)"
                },
                {"D0130",
                 "dr(D0049)"
                },
                {"D0131",
                 "dt(D0055)"
                },
                {"D0132",
                 "(-1 * (multr(D0049)))"
                },
                {"D0133",
                 "(-1 * D0132)"
                },
                {"D0134",
                 "(-1 * (multr(D0058)))"
                },
                {"D0135",
                 "(D0133 + D0134)"
                },
                {"D0136",
                 "(D0131 + D0135)"
                },
                {"D0137",
                 "divr(divr(D0136))"
                },
                {"D0138",
                 "(D0130 + D0137)"
                },
                {"D0139",
                 "dr(D0052)"
                },
                {"D0140",
                 "divr(D0052)"
                },
                {"D0141",
                 "(D0139 + D0140)"
                },
                {"D0142",
                 "dt(D0058)"
                },
                {"D0143",
                 "divr(D0055)"
                },
                {"D0144",
                 "(-1 * (multr(D0052)))"
                },
                {"D0145",
                 "(D0143 - D0144)"
                },
                {"D0146",
                 "(D0142 + D0145)"
                },
                {"D0147",
                 "divr(divr(D0146))"
                },
                {"D0148",
                 "(D0141 + D0147)"
                },
                {"D0149",
                 "divr(D0061)"
                },
                {"D0150",
                 "multr(multr(D0067))"
                },
                {"D0151",
                 "(divsint(dt(multsint(D0150))) - dt(D0150))"
                },
                {"D0152",
                 "D0151"
                },
                {"D0153",
                 "divr(divr(D0152))"
                },
                {"D0154",
                 "(D0149 + D0153)"
                },
                {"D0155",
                 "(D0138 + D0154)"
                },
                {"D0156",
                 "(D0061 * D0017)"
                },
                {"D0157",
                 "multr(multr(D0067))"
                },
                {"D0158",
                 "(D0157 * D0020)"
                },
                {"D0159",
                 "divr(divr(D0158))"
                },
                {"D0160",
                 "(D0156 + D0159)"
                },
                {"D0161",
                 "(D0155 - D0160)"
                },
                {"D0162",
                 "(PH * D0031)"
                },
                {"D0163",
                 "(D0162 * D0021)"
                },
                {"D0164",
                 "(PS * PS)"
                },
                {"D0165",
                 "(D0164 * PS)"
                },
                {"D0166",
                 "(D0165 * PS)"
                },
                {"D0167",
                 "(D0166 * PS)"
                },
                {"D0168",
                 "(1 / (D0167))"
                },
                {"D0169",
                 "(D0163 * D0168)"
                },
                {"D0170",
                 "divsint(divsint(divsint(divsint(divr(divr(divr(divr(D0169))))))))"
                },
                {"D0171",
                 "(D0161 + D0170)"
                },
                {"D0172",
                 "(PH * D0004)"
                },
                {"D0173",
                 "(D0172 * D0048)"
                },
                {"D0174",
                 "D0173"
                },
                {"D0175",
                 "divr(D0174)"
                },
                {"D0176",
                 "(3 * (D0175))"
                },
                {"D0177",
                 "(D0171 + D0176)"
                },
                {"D0178",
                 "D0172"
                },
                {"D0179",
                 "dr(D0048)"
                },
                {"D0180",
                 "(D0178 * D0179)"
                },
                {"D0181",
                 "(D0177 + D0180)"
                },
                {"D0182",
                 "(D0172 * D0048)"
                },
                {"D0183",
                 "D0182"
                },
                {"D0184",
                 "(D0183 * D0034)"
                },
                {"D0185",
                 "(6 * (D0184))"
                },
                {"D0186",
                 "(D0181 + D0185)"
                },
                {"D0187",
                 "divr(D0067)"
                },
                {"D0188",
                 "multr(multr(D0065))"
                },
                {"D0194",
                 "(D0067 * D0017)"
                },
                {"D0195",
                 "multr(multr(D0065))"
                },
                {"D0196",
                 "(D0195 * D0020)"
                },
                {"D0197",
                 "divr(divr(D0196))"
                },
                {"D0198",
                 "(D0194 + D0197)"
                },
                {"D0200",
                 "(PH * D0031)"
                },
                {"D0201",
                 "(D0200 * D0025)"
                },
                {"D0202",
                 "(PS * PS)"
                },
                {"D0203",
                 "(D0202 * PS)"
                },
                {"D0204",
                 "(D0203 * PS)"
                },
                {"D0205",
                 "(D0204 * PS)"
                },
                {"D0206",
                 "(1 / (D0205))"
                },
                {"D0207",
                 "(D0201 * D0206)"
                },
                {"D0208",
                 "divsint(divsint(divsint(divsint(divr(divr(divr(divr(D0207))))))))"
                },
                {"D0210",
                 "(PH * D0004)"
                },
                {"D0211",
                 "(D0210 * D0048)"
                },
                {"D0212",
                 "divr(divr(D0211))"
                },
                {"D0217",
                 "divr(divr(D0210))"
                },
                {"D0218",
                 "dt(D0048)"
                },
                {"D0226",
                 "lap(PH)"
                },
                {"D0227",
                 "dr(PH)"
                },
                {"D0228",
                 "divr(D0227)"
                },
                {"D0229",
                 "dt(PH)"
                },
                {"D0230",
                 "(divsint(dt(multsint(D0229))) - dt(D0229))"
                },
                {"D0231",
                 "D0230"
                },
                {"D0232",
                 "divr(divr(D0231))"
                },
                {"D0233",
                 "(D0228 + D0232)"
                },
                {"D0234",
                 "(D0226 + D0233)"
                },
                {"D0235",
                 "(PH * D0108)"
                },
                {"D0236",
                 "(D0102 - D0092)"
                },
                {"D0237",
                 "(D0235 * D0236)"
                },
                {"D0238",
                 "(D0234 - D0237)"
                },
                {"D0239",
                 "(PH * D0033)"
                },
                {"D0240",
                 "(D0239 * D0033)"
                },
                {"D0241",
                 "(D0106 * D0240)"
                },
                {"D0242",
                 "((1 / 4) * (divsint(divsint(divsint(divsint(divr(divr(divr(divr(D0241))))))))))"
                },
                {"D0243",
                 "(2 * (D0242))"
                },
                {"D0244",
                 "(D0238 - D0243)"
                },
                {"D0245",
                 "(D0021 * D0021)"
                },
                {"D0246",
                 "(D0024 * D0024)"
                },
                {"D0247",
                 "divr(divr(D0246))"
                },
                {"D0248",
                 "(D0245 + D0247)"
                },
                {"D0249",
                 "lap2(D0001)"
                },
                {"D0250",
                 "(D0034 * D0034)"
                },
                {"D0251",
                 "(D0035 * D0035)"
                },
                {"D0252",
                 "divr(divr(D0251))"
                },
                {"D0253",
                 "(D0250 + D0252)"
                },
                {"D0254",
                 "(4 * (D0253))"
                },
                {"D0255",
                 "(D0249 + D0254)"
                },
                {"D0256",
                 "dr(log(PH))"
                },
                {"D0257",
                 "(D0034 * D0256)"
                },
                {"D0258",
                 "dt(log(PH))"
                },
                {"D0259",
                 "(D0035 * D0258)"
                },
                {"D0260",
                 "divr(divr(D0259))"
                },
                {"D0261",
                 "(D0257 + D0260)"
                },
                {"D0262",
                 "(4 * (D0261))"
                },
                {"D0263",
                 "(D0255 - D0262)"
                },
                {"D0264",
                 "dr(log(PH))"
                },
                {"D0265",
                 "divr(D0264)"
                },
                {"D0266",
                 "dt(log(PH))"
                },
                {"D0267",
                 "(divsint(dt(multsint(D0266))) - dt(D0266))"
                },
                {"D0268",
                 "D0267"
                },
                {"D0269",
                 "divr(divr(D0268))"
                },
                {"D0270",
                 "(D0265 + D0269)"
                },
                {"D0271",
                 "(2 * (D0270))"
                },
                {"D0272",
                 "(D0263 - D0271)"
                },
                {"D0273",
                 "(4 * (D0092))"
                },
                {"D0274",
                 "(D0102 - D0273)"
                },
                {"D0275",
                 "(D0108 * D0274)"
                },
                {"D0276",
                 "((1 / 2) * (D0275))"
                },
                {"D0277",
                 "(D0272 + D0276)"
                },
                {"D0278",
                 "(D0033 * D0033)"
                },
                {"D0279",
                 "(5 * (D0278))"
                },
                {"D0280",
                 "(3 * (D0248))"
                },
                {"D0281",
                 "(D0279 - D0280)"
                },
                {"D0282",
                 "(D0106 * D0281)"
                },
                {"D0283",
                 "((1 / 4) * (divsint(divsint(divsint(divsint(divr(divr(divr(divr(D0282))))))))))"
                },
                {"D0284",
                 "(D0277 + D0283)"
                },
                {"D0285",
                 "lap(D0006)"
                },
                {"D0286",
                 "dr(PH)"
                },
                {"D0287",
                 "(D0034 * D0286)"
                },
                {"D0288",
                 "dt(PH)"
                },
                {"D0289",
                 "(D0035 * D0288)"
                },
                {"D0290",
                 "divr(divr(D0289))"
                },
                {"D0291",
                 "(D0287 + D0290)"
                },
                {"D0292",
                 "(D0291 * D0005)"
                },
                {"D0293",
                 "(D0285 + D0292)"
                },
                {"D0294",
                 "dr(PH)"
                },
                {"D0295",
                 "divr(D0294)"
                },
                {"D0296",
                 "dt(PH)"
                },
                {"D0297",
                 "(divsint(dt(multsint(D0296))) - dt(D0296))"
                },
                {"D0298",
                 "D0297"
                },
                {"D0299",
                 "divr(divr(D0298))"
                },
                {"D0300",
                 "(D0295 + D0299)"
                },
                {"D0301",
                 "(D0300 * D0005)"
                },
                {"D0302",
                 "((1 / 2) * (D0301))"
                },
                {"D0303",
                 "(D0293 + D0302)"
                },
                {"D0304",
                 "(D0108 * D0092)"
                },
                {"D0305",
                 "((1 / 2) * (D0304))"
                },
                {"D0306",
                 "(D0303 + D0305)"
                },
                {"D0307",
                 "(D0033 * D0033)"
                },
                {"D0308",
                 "(D0248 - D0307)"
                },
                {"D0309",
                 "(D0106 * D0308)"
                },
                {"D0310",
                 "((1 / 4) * (divsint(divsint(divsint(divsint(divr(divr(divr(divr(D0309))))))))))"
                },
                {"D0311",
                 "(D0306 + D0310)"
                },
                {"D0312",
                 "multsint(D0148)"
                },
                {"D0313",
                 "multsint(D0187)"
                },
                {"D0314",
                 "multsint(D0188)"
                },
                {"D0315",
                 "dt(D0314)"
                },
                {"D0316",
                 "dt(D0188)"
                },
                {"D0317",
                 "multsint(D0316)"
                },
                {"D0318",
                 "(D0315 - D0317)"
                },
                {"D0319",
                 "divr(D0318)"
                },
                {"D0320",
                 "divr(D0319)"
                },
                {"D0321",
                 "(D0313 + D0320)"
                },
                {"D0322",
                 "(D0312 + D0321)"
                },
                {"D0323",
                 "multsint(D0198)"
                },
                {"D0324",
                 "(D0322 - D0323)"
                },
                {"D0325",
                 "multsint(D0208)"
                },
                {"D0326",
                 "(D0324 + D0325)"
                },
                {"D0327",
                 "multsint(D0212)"
                },
                {"D0328",
                 "dt(D0327)"
                },
                {"D0329",
                 "dt(D0212)"
                },
                {"D0330",
                 "multsint(D0329)"
                },
                {"D0331",
                 "(D0328 - D0330)"
                },
                {"D0332",
                 "(3 * (D0331))"
                },
                {"D0333",
                 "(D0326 + D0332)"
                },
                {"D0334",
                 "multsint(D0218)"
                },
                {"D0335",
                 "(D0217 * D0334)"
                },
                {"D0336",
                 "(D0333 + D0335)"
                },
                {"D0337",
                 "multsint(D0040)"
                },
                {"D0338",
                 "multsint(D0042)"
                },
                {"D0339",
                 "multsint(BT)"
                },
                {"D0340",
                 "dt(D0339)"
                },
                {"D0341",
                 "dt(BT)"
                },
                {"D0342",
                 "multsint(D0341)"
                },
                {"D0343",
                 "(D0340 - D0342)"
                },
                {"D0344",
                 "(D0338 + D0343)"
                },
                {"D0345",
                 "(D0337 + D0344)"
                },
                {"D0346",
                 "(D0036 * D0345)"
                },
                {"D0347",
                 "(-1 * (D0346))"
                },
                {"D0348",
                 "(D0210 * D0347)"
                },
                {"D0349",
                 "divr(D0348)"
                },
                {"D0350",
                 "divr(D0349)"
                },
                {"D0351",
                 "(D0350 * D0035)"
                },
                {"D0352",
                 "(6 * (D0351))"
                },
                {"D0353",
                 "(D0336 + D0352)"
                },
            };
            return D;
        }

        inline const std::vector<FiniteJEq>& equations()
        {
            static const std::vector<FiniteJEq> E = {
                {"EQTW",
                 "D0129"
                },
                {"ESHR",
                 "D0186"
                },
                {"ESHT",
                 "D0353"
                },
                {"EPHI",
                 "D0244"
                },
                {"EQFN",
                 "D0284"
                },
                {"ESIG",
                 "D0311"
                },
            };
            return E;
        }

        inline const std::vector<FiniteJCheck>& checks()
        {
            static const std::vector<FiniteJCheck> C = {
                {"CK0010", "D0010", "D0007 D0009",
                 "(D0007 - D0009)"
                },
                {"CK0014", "D0014", "D0011 D0013",
                 "(D0011 - D0013)"
                },
                {"CK0017", "D0017", "D0010 D0016",
                 "(D0010 - D0016)"
                },
                {"CK0020", "D0020", "D0014 D0019",
                 "(D0014 - D0019)"
                },
                {"CK0024", "D0024", "D0022 D0023",
                 "(D0022 + D0023)"
                },
                {"CK0029", "D0029", "D0027 D0028",
                 "(D0027 + D0028)"
                },
                {"CK0039", "D0039", "D0037 D0038",
                 "(D0037 + D0038)"
                },
                {"CK0043", "D0043", "",
                 "(divsint(dt(multsint(BT))) - dt(BT))"
                },
                {"CK0045", "D0045", "D0042 D0044",
                 "(D0042 + D0044)"
                },
                {"CK0046", "D0046", "D0040 D0045",
                 "(D0040 + D0045)"
                },
                {"CK0052", "D0052", "D0050 D0051",
                 "(D0050 + D0051)"
                },
                {"CK0055", "D0055", "D0053 D0054",
                 "(D0053 + D0054)"
                },
                {"CK0058", "D0058", "D0056 D0057",
                 "(D0056 + D0057)"
                },
                {"CK0059", "D0059", "D0049 D0058",
                 "(D0049 + D0058)"
                },
                {"CK0061", "D0061", "D0059 D0060",
                 "(D0060 - D0059)"
                },
                {"CK0065", "D0065", "D0063 D0064",
                 "(D0063 - D0064)"
                },
                {"CK0067", "D0067", "D0052 D0066",
                 "(D0052 + D0066)"
                },
                {"CK0081", "D0081", "D0077 D0080",
                 "(D0077 + D0080)"
                },
                {"CK0085", "D0085", "D0081 D0084",
                 "(D0081 + D0084)"
                },
                {"CK0091", "D0091", "D0088 D0090",
                 "(D0088 + D0090)"
                },
                {"CK0098", "D0098", "D0095 D0097",
                 "(D0095 + D0097)"
                },
                {"CK0102", "D0102", "D0085 D0101",
                 "(D0085 + D0101)"
                },
                {"CK0113", "D0113", "D0112",
                 "(divsint(dt(multsint(D0112))) - dt(D0112))"
                },
                {"CK0116", "D0116", "D0111 D0115",
                 "(D0111 + D0115)"
                },
                {"CK0118", "D0118", "D0109 D0117",
                 "(D0109 - D0117)"
                },
                {"CK0120", "D0120", "D0118 D0119",
                 "(D0118 + D0119)"
                },
                {"CK0124", "D0124", "D0120 D0123",
                 "(D0120 + D0123)"
                },
                {"CK0127", "D0127", "D0099 D0126",
                 "(D0126 + D0099)"
                },
                {"CK0129", "D0129", "D0124 D0128",
                 "(D0124 + D0128)"
                },
                {"CK0135", "D0135", "D0133 D0134",
                 "(D0133 + D0134)"
                },
                {"CK0136", "D0136", "D0131 D0135",
                 "(D0131 + D0135)"
                },
                {"CK0138", "D0138", "D0130 D0137",
                 "(D0130 + D0137)"
                },
                {"CK0141", "D0141", "D0139 D0140",
                 "(D0139 + D0140)"
                },
                {"CK0145", "D0145", "D0143 D0144",
                 "(D0143 - D0144)"
                },
                {"CK0146", "D0146", "D0142 D0145",
                 "(D0142 + D0145)"
                },
                {"CK0148", "D0148", "D0141 D0147",
                 "(D0141 + D0147)"
                },
                {"CK0151", "D0151", "D0150",
                 "(divsint(dt(multsint(D0150))) - dt(D0150))"
                },
                {"CK0154", "D0154", "D0149 D0153",
                 "(D0149 + D0153)"
                },
                {"CK0155", "D0155", "D0138 D0154",
                 "(D0138 + D0154)"
                },
                {"CK0160", "D0160", "D0156 D0159",
                 "(D0156 + D0159)"
                },
                {"CK0161", "D0161", "D0155 D0160",
                 "(D0155 - D0160)"
                },
                {"CK0171", "D0171", "D0161 D0170",
                 "(D0161 + D0170)"
                },
                {"CK0177", "D0177", "D0171 D0176",
                 "(D0171 + D0176)"
                },
                {"CK0181", "D0181", "D0177 D0180",
                 "(D0177 + D0180)"
                },
                {"CK0186", "D0186", "D0181 D0185",
                 "(D0181 + D0185)"
                },
                {"CK0198", "D0198", "D0194 D0197",
                 "(D0194 + D0197)"
                },
                {"CK0230", "D0230", "D0229",
                 "(divsint(dt(multsint(D0229))) - dt(D0229))"
                },
                {"CK0233", "D0233", "D0228 D0232",
                 "(D0228 + D0232)"
                },
                {"CK0234", "D0234", "D0226 D0233",
                 "(D0226 + D0233)"
                },
                {"CK0236", "D0236", "D0092 D0102",
                 "(D0102 - D0092)"
                },
                {"CK0238", "D0238", "D0234 D0237",
                 "(D0234 - D0237)"
                },
                {"CK0244", "D0244", "D0238 D0243",
                 "(D0238 - D0243)"
                },
                {"CK0248", "D0248", "D0245 D0247",
                 "(D0245 + D0247)"
                },
                {"CK0253", "D0253", "D0250 D0252",
                 "(D0250 + D0252)"
                },
                {"CK0255", "D0255", "D0249 D0254",
                 "(D0249 + D0254)"
                },
                {"CK0261", "D0261", "D0257 D0260",
                 "(D0257 + D0260)"
                },
                {"CK0263", "D0263", "D0255 D0262",
                 "(D0255 - D0262)"
                },
                {"CK0267", "D0267", "D0266",
                 "(divsint(dt(multsint(D0266))) - dt(D0266))"
                },
                {"CK0270", "D0270", "D0265 D0269",
                 "(D0265 + D0269)"
                },
                {"CK0272", "D0272", "D0263 D0271",
                 "(D0263 - D0271)"
                },
                {"CK0274", "D0274", "D0102 D0273",
                 "(D0102 - D0273)"
                },
                {"CK0277", "D0277", "D0272 D0276",
                 "(D0272 + D0276)"
                },
                {"CK0281", "D0281", "D0279 D0280",
                 "(D0279 - D0280)"
                },
                {"CK0284", "D0284", "D0277 D0283",
                 "(D0277 + D0283)"
                },
                {"CK0291", "D0291", "D0287 D0290",
                 "(D0287 + D0290)"
                },
                {"CK0293", "D0293", "D0285 D0292",
                 "(D0285 + D0292)"
                },
                {"CK0297", "D0297", "D0296",
                 "(divsint(dt(multsint(D0296))) - dt(D0296))"
                },
                {"CK0300", "D0300", "D0295 D0299",
                 "(D0295 + D0299)"
                },
                {"CK0303", "D0303", "D0293 D0302",
                 "(D0293 + D0302)"
                },
                {"CK0306", "D0306", "D0303 D0305",
                 "(D0303 + D0305)"
                },
                {"CK0308", "D0308", "D0248 D0307",
                 "(D0248 - D0307)"
                },
                {"CK0311", "D0311", "D0306 D0310",
                 "(D0306 + D0310)"
                },
                {"CK0318", "D0318", "D0315 D0317",
                 "(D0315 - D0317)"
                },
                {"CK0321", "D0321", "D0313 D0320",
                 "(D0313 + D0320)"
                },
                {"CK0322", "D0322", "D0312 D0321",
                 "(D0312 + D0321)"
                },
                {"CK0324", "D0324", "D0322 D0323",
                 "(D0322 - D0323)"
                },
                {"CK0326", "D0326", "D0324 D0325",
                 "(D0324 + D0325)"
                },
                {"CK0331", "D0331", "D0328 D0330",
                 "(D0328 - D0330)"
                },
                {"CK0333", "D0333", "D0326 D0332",
                 "(D0326 + D0332)"
                },
                {"CK0336", "D0336", "D0333 D0335",
                 "(D0333 + D0335)"
                },
                {"CK0343", "D0343", "D0340 D0342",
                 "(D0340 - D0342)"
                },
                {"CK0344", "D0344", "D0338 D0343",
                 "(D0338 + D0343)"
                },
                {"CK0345", "D0345", "D0337 D0344",
                 "(D0337 + D0344)"
                },
                {"CK0353", "D0353", "D0336 D0352",
                 "(D0336 + D0352)"
                },
            };
            return C;
        }

        /// Read a def into CONFIGURATION space.  Fetching the Val_domain
        /// is not enough -- indexing it is what converts, and a probe that
        /// only fetched returned two false negatives (round 108).
        inline void read_def(Kadath::System_of_eqs& syst,
                             const Kadath::Space& sp, const char* nm,
                             int dmin, int dmax)
        {
            for (int d = dmin; d <= dmax; d++) {
                const Kadath::Val_domain& v =
                    syst.give_val_def_scalar_domain(nm, d);
                Kadath::Index ix(sp.get_domain(d)->get_nbr_points());
                (void)v(ix);
            }
        }
    } // namespace finiteJ_detail

    /// The sub-def names, in dependency order, for reading values back.
    inline const std::vector<const char*>& finiteJ_names()
    {
        static const std::vector<const char*> N = [] {
            std::vector<const char*> v;
            for (const auto& d : finiteJ_detail::subdefs()) v.push_back(d.name);
            return v;
        }();
        return N;
    }

    /// The six equation names.
    inline const std::vector<const char*>& finiteJ_eq_names()
    {
        static const std::vector<const char*> N = [] {
            std::vector<const char*> v;
            for (const auto& e : finiteJ_detail::equations()) v.push_back(e.name);
            return v;
        }();
        return N;
    }

    /// The angular bases this emission was analysed under.  The caller
    /// MUST register the six unknowns in these bases: the basis lattice
    /// that decided every sum ordering assumed them, and if the run
    /// registers something else the analysis describes a different
    /// system.  Names, not integers, so a renumbering in the library
    /// cannot silently reinterpret them.
    inline const std::vector<std::pair<const char*, const char*>>&
    finiteJ_declared_basis()
    {
        static const std::vector<std::pair<const char*, const char*>> B = {
            {"PS", "COS_EVEN"},
            {"PH", "COS_EVEN"},
            {"QF", "COS_EVEN"},
            {"BR", "COS_EVEN"},
            {"BT", "SIN_EVEN"},
            {"QB", "COS_ODD"},
        };
        return B;
    }

    /// Sums reordered by --order-sums, which is seed-specific: see the
    /// header comment.  Empty means the emission was written without it.
    inline const std::vector<const char*>& finiteJ_ordered_sums()
    {
        static const std::vector<const char*> O = {
        };
        return O;
    }

    /// Emission-time AXIS PRECONDITION violations carried into the
    /// artefact: each is a divsint applied where the emitter could not
    /// show the operand vanishes on the axis.  Empty is the only
    /// acceptable state, and since round 342 it is the only reachable
    /// one: the emitter refuses to write a violating emission at all.
    inline const std::vector<const char*>& finiteJ_axis_violations()
    {
        static const std::vector<const char*> V = {
        };
        return V;
    }

    /**
     * Register the emission, keeping the read-state contract.
     *
     * read_defs = false deliberately BREAKS the contract.  It exists so a
     * caller can show finiteJ_check() catches the breach; nothing else
     * should ever pass it.
     */
    inline void finiteJ_register(Kadath::System_of_eqs& syst,
                                 const Kadath::Space& sp, int dmin, int dmax,
                                 bool read_defs = true)
    {
        for (const auto& d : finiteJ_detail::subdefs()) {
            syst.add_def((std::string(d.name) + " = " + d.def).c_str());
            if (read_defs)
                finiteJ_detail::read_def(syst, sp, d.name, dmin, dmax);
        }
        for (const auto& e : finiteJ_detail::equations()) {
            syst.add_def((std::string(e.name) + " = " + e.def).c_str());
            if (read_defs)
                finiteJ_detail::read_def(syst, sp, e.name, dmin, dmax);
        }
    }

    /**
     * THE CONTROL.  Re-register every sum with its operands READ first and
     * compare pointwise with the original.  Returns the worst relative
     * difference and throws above tol.
     *
     * ⚠ Reading the operands before re-parsing is the whole mechanism.  A
     * version that re-registers without reading puts both spellings in the
     * same evaluator state, and two spellings in one state cannot
     * discriminate a defect whose variable IS the state -- which is how
     * round 107 shipped a check weaker than it was reported to be.
     */
    inline double finiteJ_check(Kadath::System_of_eqs& syst,
                                const Kadath::Space& sp, int dmin, int dmax,
                                double tol = 1e-12)
    {
        double worst = 0.0;
        std::string worst_name;
        for (const auto& c : finiteJ_detail::checks()) {
            std::istringstream is(c.reads);
            for (std::string nm; is >> nm;)
                finiteJ_detail::read_def(syst, sp, nm.c_str(), dmin, dmax);
            syst.add_def((std::string(c.name) + " = " + c.def).c_str());
            double mx = 0.0, scale = 0.0;
            for (int d = dmin; d <= dmax; d++) {
                const Kadath::Val_domain& a =
                    syst.give_val_def_scalar_domain(c.of, d);
                const Kadath::Val_domain& b =
                    syst.give_val_def_scalar_domain(c.name, d);
                Kadath::Index ix(sp.get_domain(d)->get_nbr_points());
                do {
                    mx = std::max(mx, std::fabs(a(ix) - b(ix)));
                    scale = std::max(scale, std::fabs(a(ix)));
                } while (ix.inc());
            }
            const double rel = mx / std::max(scale, 1e-300);
            if (rel > worst) { worst = rel; worst_name = c.of; }
        }
        if (worst > tol)
            throw std::runtime_error(
                "finiteJ read-state contract broken: " + worst_name
                + " differs from its own re-expression by "
                + std::to_string(worst)
                + " -- the defs were registered without being read");
        return worst;
    }

} // namespace Trumpet
