/*
 * finiteJ_eqs.hpp -- GENERATED by scripts/finiteJ_emit.py.  Do not edit.
 *
 * ⚠ --q-regular: q = sin^2(theta) q~.  The unknown QF DENOTES q~ in this
 * emission (research round 578; code round 279), so q vanishes on the
 * axis by construction.  Build it as finiteJ_probe_qreg only.
 *
 * ⚠ --s-expand (code round 385, research round 793 task 1, A PROBE): the
 * shift-transport term S = rho beta . grad chi by the product rule in the
 * fields and their first / second derivatives (no derivative of a formed
 * chi).  Built only into finiteJ_probe_bulk2_sx (TRUMPET_SEXP).
 *
 * ⚠ --c3 (code round 384, research ruling H2 PREPARED, NOT ADOPTED): the
 * C3 twist terms of rounds 728 / 733 -- bOmw = Omw psi2 e^q, the shift
 * Omega_omega term / psi2^5, E_Phi's -bOmw^2 Ncal doubled.  Built only
 * into finiteJ_probe_bulk2_c3 (TRUMPET_C3).
 *
 * The six finite-J equations as Kadath defs, emitted from the ASSEMBLY's
 * structure rather than from an expanded expression: where the assembly
 * applied lap2S the emission says lap2, instead of expanding and hoping to
 * recognise it again.
 *
 * Unknowns PS, PH, QF, BR, BT, QB.  Spin constant JJ.  There are NO sin or
 * cos FIELDS: round 103 measured that neither lies in the scalar COS_EVEN
 * span, so an add_cst holding one stores an alias.  Angular and radial
 * factors go through the coefficient-space operators instead, and
 *
 *     cot(theta) * X  ==  divsint(dt(multsint(X))) - dt(X)
 *
 * which the probe verified to 2e-16 on a field vanishing on the axis.
 *
 * Registered as 406 named sub-defs then the six equations: the parser has a
 * STACK-depth limit near 1000 characters that was not reproducible run to
 * run, so every piece here is kept far below it.
 *
 * ⚠ THE READ-STATE CONTRACT (round 108).  Kadath evaluates a sum
 * differently depending on whether its named operands have been READ --
 * indexed, which forces a Val_domain into configuration space -- before
 * the sum is parsed, and a def parsed in the wrong state does not recover
 * when its operands are read later.  Every sub-def below must therefore be
 * read immediately after it is registered.  That is why the def TEXT is not
 * exported: register through finiteJ_register(), which does it, and call
 * finiteJ_check(), which fails loudly if it was not done.  A requirement in
 * prose gets transcribed wrongly; this one is in the only function that can
 * reach the text.
 */
#pragma once

#include "For_Kadath/Array/headcpp.hpp"
#include "For_Kadath/Space/space.hpp"
#include "For_Kadath/System_of_eqs/system_of_eqs.hpp"

#include <algorithm>
#include <cmath>
#include <sstream>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

namespace Trumpet
{
    struct FiniteJEq { const char* name; const char* def; };

    /// One sum, re-expressed.  `reads` are the operands finiteJ_check()
    /// reads before re-parsing `def`, which is what lets it discriminate.
    struct FiniteJCheck {
        const char* name; const char* of; const char* reads; const char* def;
    };

    namespace finiteJ_detail
    {
        /// ⚠ The def TEXT.  Registering any of this by hand skips the read
        /// the evaluator needs; go through finiteJ_register() instead.
        inline const std::vector<FiniteJEq>& subdefs()
        {
            static const std::vector<FiniteJEq> D = {
                {"D0001",
                 "multsint(multsint(QF))"
                },
                {"D0002",
                 "multsint(multsint(multsint(multsint(QB))))"
                },
                {"D0003",
                 "(2 * (D0001))"
                },
                {"D0004",
                 "(1 / (PS))"
                },
                {"D0005",
                 "(1 / (PH))"
                },
                {"D0006",
                 "((1 / 2) * (log(PS)))"
                },
                {"D0007",
                 "dr(log(PH))"
                },
                {"D0008",
                 "dr(log(PS))"
                },
                {"D0009",
                 "(4 * (D0008))"
                },
                {"D0010",
                 "(D0007 - D0009)"
                },
                {"D0011",
                 "dt(log(PH))"
                },
                {"D0012",
                 "dt(log(PS))"
                },
                {"D0013",
                 "(4 * (D0012))"
                },
                {"D0014",
                 "(D0011 - D0013)"
                },
                {"D0015",
                 "dr(D0001)"
                },
                {"D0016",
                 "(2 * (D0015))"
                },
                {"D0017",
                 "(D0010 - D0016)"
                },
                {"D0018",
                 "dt(D0001)"
                },
                {"D0019",
                 "(2 * (D0018))"
                },
                {"D0020",
                 "(D0014 - D0019)"
                },
                {"D0021",
                 "dr(D0002)"
                },
                {"D0022",
                 "dt(D0002)"
                },
                {"D0023",
                 "(6*JJ * (multsint(multsint(multsint(ones)))))"
                },
                {"D0024",
                 "(D0022 + D0023)"
                },
                {"D0025",
                 "divr(divr(D0024))"
                },
                {"D0026",
                 "(PS * D0005)"
                },
                {"D0027",
                 "(BR * D0021)"
                },
                {"D0028",
                 "(BT * D0024)"
                },
                {"D0029",
                 "(D0027 + D0028)"
                },
                {"D0030",
                 "(D0026 * D0029)"
                },
                {"D0031",
                 "(-1 * (D0030))"
                },
                {"D0032",
                 "(D0031 * PS)"
                },
                {"D0033",
                 "(D0032 * exp(D0001))"
                },
                {"D0034",
                 "dr(D0006)"
                },
                {"D0035",
                 "dt(D0006)"
                },
                {"D0036",
                 "(PS * D0005)"
                },
                {"D0037",
                 "(2 * (D0034))"
                },
                {"D0038",
                 "divr(ones)"
                },
                {"D0039",
                 "(D0037 + D0038)"
                },
                {"D0040",
                 "(BR * D0039)"
                },
                {"D0041",
                 "(2 * (D0035))"
                },
                {"D0042",
                 "(BT * D0041)"
                },
                {"D0043",
                 "(divsint(dt(multsint(BT))) - dt(BT))"
                },
                {"D0044",
                 "D0043"
                },
                {"D0045",
                 "(D0042 + D0044)"
                },
                {"D0046",
                 "(D0040 + D0045)"
                },
                {"D0047",
                 "(D0036 * D0046)"
                },
                {"D0048",
                 "(-1 * (D0047))"
                },
                {"D0049",
                 "dr(BR)"
                },
                {"D0050",
                 "dr(BT)"
                },
                {"D0051",
                 "divr(BT)"
                },
                {"D0052",
                 "(D0050 + D0051)"
                },
                {"D0053",
                 "dt(BR)"
                },
                {"D0054",
                 "(-1 * (multr(BT)))"
                },
                {"D0055",
                 "(D0053 + D0054)"
                },
                {"D0056",
                 "dt(BT)"
                },
                {"D0057",
                 "divr(BR)"
                },
                {"D0058",
                 "(D0056 + D0057)"
                },
                {"D0059",
                 "(D0049 + D0058)"
                },
                {"D0060",
                 "(2 * (D0049))"
                },
                {"D0061",
                 "(D0060 - D0059)"
                },
                {"D0062",
                 "divr(divr(D0058))"
                },
                {"D0063",
                 "(2 * (D0062))"
                },
                {"D0064",
                 "divr(divr(D0059))"
                },
                {"D0065",
                 "(D0063 - D0064)"
                },
                {"D0066",
                 "divr(divr(D0055))"
                },
                {"D0067",
                 "(D0052 + D0066)"
                },
                {"D0068",
                 "(PS * D0005)"
                },
                {"D0069",
                 "(D0068 * D0061)"
                },
                {"D0070",
                 "(PS * D0005)"
                },
                {"D0071",
                 "(D0070 * D0065)"
                },
                {"D0072",
                 "(PS * D0005)"
                },
                {"D0073",
                 "(D0072 * D0067)"
                },
                {"D0074",
                 "((1 / 2) * (D0069))"
                },
                {"D0075",
                 "((1 / 2) * (D0071))"
                },
                {"D0076",
                 "((1 / 2) * (D0073))"
                },
                {"D0077",
                 "(D0074 * D0074)"
                },
                {"D0078",
                 "(D0075 * D0075)"
                },
                {"D0079",
                 "D0078"
                },
                {"D0424",
                 "multr(multr(D0075))"
                },
                {"D0080",
                 "(D0424 * D0424)"
                },
                {"D0081",
                 "(D0077 + D0080)"
                },
                {"D0082",
                 "(D0076 * D0076)"
                },
                {"D0083",
                 "(2 * (D0082))"
                },
                {"D0084",
                 "multr(multr(D0083))"
                },
                {"D0085",
                 "(D0081 + D0084)"
                },
                {"D0086",
                 "dr(PS)"
                },
                {"D0087",
                 "dt(PS)"
                },
                {"D0088",
                 "(D0086 * D0004)"
                },
                {"D0089",
                 "(D0087 * D0004)"
                },
                {"D0090",
                 "dr(D0086)"
                },
                {"D0091",
                 "(D0090 * D0004)"
                },
                {"D0092",
                 "(D0088 * D0088)"
                },
                {"D0093",
                 "(D0091 - D0092)"
                },
                {"D0094",
                 "dt(D0087)"
                },
                {"D0095",
                 "(D0094 * D0004)"
                },
                {"D0096",
                 "(D0089 * D0089)"
                },
                {"D0097",
                 "(D0095 - D0096)"
                },
                {"D0098",
                 "dt(D0086)"
                },
                {"D0099",
                 "(D0098 * D0004)"
                },
                {"D0100",
                 "(D0088 * D0089)"
                },
                {"D0101",
                 "(D0099 - D0100)"
                },
                {"D0102",
                 "(PS * D0005)"
                },
                {"D0103",
                 "(D0086 * D0005)"
                },
                {"D0104",
                 "dr(PH)"
                },
                {"D0105",
                 "(PS * D0104)"
                },
                {"D0106",
                 "(D0105 * D0005)"
                },
                {"D0107",
                 "(D0106 * D0005)"
                },
                {"D0108",
                 "(D0103 - D0107)"
                },
                {"D0109",
                 "(D0087 * D0005)"
                },
                {"D0110",
                 "dt(PH)"
                },
                {"D0111",
                 "(PS * D0110)"
                },
                {"D0112",
                 "(D0111 * D0005)"
                },
                {"D0113",
                 "(D0112 * D0005)"
                },
                {"D0114",
                 "(D0109 - D0113)"
                },
                {"D0115",
                 "divr(ones)"
                },
                {"D0116",
                 "(D0088 + D0115)"
                },
                {"D0117",
                 "(BR * D0116)"
                },
                {"D0118",
                 "(BT * D0089)"
                },
                {"D0119",
                 "(divsint(dt(multsint(BT))) - dt(BT))"
                },
                {"D0120",
                 "D0119"
                },
                {"D0121",
                 "(D0118 + D0120)"
                },
                {"D0122",
                 "(D0117 + D0121)"
                },
                {"D0123",
                 "dr(BR)"
                },
                {"D0124",
                 "(D0123 * D0116)"
                },
                {"D0125",
                 "(-1 * (divr(divr(ones))))"
                },
                {"D0126",
                 "(D0093 + D0125)"
                },
                {"D0127",
                 "(BR * D0126)"
                },
                {"D0128",
                 "(D0124 + D0127)"
                },
                {"D0129",
                 "dr(BT)"
                },
                {"D0130",
                 "(D0129 * D0089)"
                },
                {"D0131",
                 "(divsint(dt(multsint(D0129))) - dt(D0129))"
                },
                {"D0132",
                 "D0131"
                },
                {"D0133",
                 "(D0130 + D0132)"
                },
                {"D0134",
                 "(D0128 + D0133)"
                },
                {"D0135",
                 "(BT * D0101)"
                },
                {"D0136",
                 "(D0134 + D0135)"
                },
                {"D0137",
                 "dt(BR)"
                },
                {"D0138",
                 "(D0137 * D0116)"
                },
                {"D0139",
                 "(BR * D0101)"
                },
                {"D0140",
                 "(D0138 + D0139)"
                },
                {"D0141",
                 "dt(BT)"
                },
                {"D0142",
                 "(D0141 * D0089)"
                },
                {"D0143",
                 "(D0140 + D0142)"
                },
                {"D0144",
                 "(BT * D0097)"
                },
                {"D0145",
                 "(D0143 + D0144)"
                },
                {"D0146",
                 "(divsint(dt(multsint(BT))) - dt(BT))"
                },
                {"D0147",
                 "D0146"
                },
                {"D0148",
                 "dt(D0147)"
                },
                {"D0149",
                 "(D0145 + D0148)"
                },
                {"D0150",
                 "(D0108 * D0122)"
                },
                {"D0151",
                 "(D0102 * D0136)"
                },
                {"D0152",
                 "(D0150 + D0151)"
                },
                {"D0153",
                 "(-1 * (D0152))"
                },
                {"D0154",
                 "(D0114 * D0122)"
                },
                {"D0155",
                 "(D0102 * D0149)"
                },
                {"D0156",
                 "(D0154 + D0155)"
                },
                {"D0157",
                 "(-1 * (D0156))"
                },
                {"D0158",
                 "(PS * D0005)"
                },
                {"D0159",
                 "(BR * D0153)"
                },
                {"D0160",
                 "(BT * D0157)"
                },
                {"D0161",
                 "(D0159 + D0160)"
                },
                {"D0162",
                 "(D0158 * D0161)"
                },
                {"D0163",
                 "(PS * D0005)"
                },
                {"D0164",
                 "dr(D0031)"
                },
                {"D0165",
                 "(BR * D0164)"
                },
                {"D0166",
                 "dt(D0031)"
                },
                {"D0167",
                 "(BT * D0166)"
                },
                {"D0168",
                 "(D0165 + D0167)"
                },
                {"D0169",
                 "(D0163 * D0168)"
                },
                {"D0170",
                 "(D0048 * D0048)"
                },
                {"D0171",
                 "((3 / 2) * (D0170))"
                },
                {"D0172",
                 "(D0085 + D0171)"
                },
                {"D0173",
                 "(PS * PS)"
                },
                {"D0174",
                 "(D0173 * PS)"
                },
                {"D0175",
                 "(D0174 * PS)"
                },
                {"D0176",
                 "(1 / (D0175))"
                },
                {"D0177",
                 "(PS * PS)"
                },
                {"D0178",
                 "(D0177 * exp(D0003))"
                },
                {"D0179",
                 "lap2(D0002)"
                },
                {"D0180",
                 "dr(D0002)"
                },
                {"D0181",
                 "divr(D0180)"
                },
                {"D0182",
                 "dt(D0002)"
                },
                {"D0183",
                 "(divsint(dt(multsint(D0182))) - dt(D0182))"
                },
                {"D0184",
                 "D0183"
                },
                {"D0185",
                 "divr(divr(D0184))"
                },
                {"D0186",
                 "(D0181 + D0185)"
                },
                {"D0187",
                 "(3 * (D0186))"
                },
                {"D0188",
                 "(D0179 - D0187)"
                },
                {"D0189",
                 "(D0021 * D0010)"
                },
                {"D0190",
                 "(D0188 + D0189)"
                },
                {"D0191",
                 "multr(multr(D0025))"
                },
                {"D0192",
                 "(D0191 * D0014)"
                },
                {"D0193",
                 "divr(divr(D0192))"
                },
                {"D0194",
                 "(D0190 + D0193)"
                },
                {"D0195",
                 "(D0031 * D0048)"
                },
                {"D0196",
                 "(4 * (D0195))"
                },
                {"D0197",
                 "(D0196 + D0169)"
                },
                {"D0198",
                 "(D0178 * D0197)"
                },
                {"D0199",
                 "(D0194 + D0198)"
                },
                {"D0200",
                 "dr(D0049)"
                },
                {"D0201",
                 "dt(D0055)"
                },
                {"D0202",
                 "(-1 * (multr(D0049)))"
                },
                {"D0203",
                 "(-1 * D0202)"
                },
                {"D0204",
                 "(-1 * (multr(D0058)))"
                },
                {"D0205",
                 "(D0203 + D0204)"
                },
                {"D0206",
                 "(D0201 + D0205)"
                },
                {"D0207",
                 "divr(divr(D0206))"
                },
                {"D0208",
                 "(D0200 + D0207)"
                },
                {"D0209",
                 "dr(D0052)"
                },
                {"D0210",
                 "divr(D0052)"
                },
                {"D0211",
                 "(D0209 + D0210)"
                },
                {"D0212",
                 "dt(D0058)"
                },
                {"D0213",
                 "divr(D0055)"
                },
                {"D0214",
                 "(-1 * (multr(D0052)))"
                },
                {"D0215",
                 "(D0213 - D0214)"
                },
                {"D0216",
                 "(D0212 + D0215)"
                },
                {"D0217",
                 "divr(divr(D0216))"
                },
                {"D0218",
                 "(D0211 + D0217)"
                },
                {"D0219",
                 "divr(D0061)"
                },
                {"D0220",
                 "multr(multr(D0067))"
                },
                {"D0221",
                 "(divsint(dt(multsint(D0220))) - dt(D0220))"
                },
                {"D0222",
                 "D0221"
                },
                {"D0223",
                 "divr(divr(D0222))"
                },
                {"D0224",
                 "(D0219 + D0223)"
                },
                {"D0225",
                 "(D0208 + D0224)"
                },
                {"D0226",
                 "(D0061 * D0017)"
                },
                {"D0227",
                 "multr(multr(D0067))"
                },
                {"D0228",
                 "(D0227 * D0020)"
                },
                {"D0229",
                 "divr(divr(D0228))"
                },
                {"D0230",
                 "(D0226 + D0229)"
                },
                {"D0231",
                 "(D0225 - D0230)"
                },
                {"D0232",
                 "(PH * D0031)"
                },
                {"D0233",
                 "(D0232 * D0021)"
                },
                {"D0234",
                 "(PS * PS)"
                },
                {"D0235",
                 "(D0234 * PS)"
                },
                {"D0236",
                 "(D0235 * PS)"
                },
                {"D0237",
                 "(D0236 * PS)"
                },
                {"D0238",
                 "(1 / (D0237))"
                },
                {"D0239",
                 "(D0233 * D0238)"
                },
                {"D0240",
                 "divsint(divsint(divsint(divsint(divr(divr(divr(divr(D0239))))))))"
                },
                {"D0241",
                 "(D0231 + D0240)"
                },
                {"D0242",
                 "(PH * D0004)"
                },
                {"D0243",
                 "(D0242 * D0048)"
                },
                {"D0244",
                 "D0243"
                },
                {"D0245",
                 "divr(D0244)"
                },
                {"D0246",
                 "(3 * (D0245))"
                },
                {"D0247",
                 "(D0241 + D0246)"
                },
                {"D0248",
                 "D0242"
                },
                {"D0249",
                 "dr(D0048)"
                },
                {"D0250",
                 "(D0248 * D0249)"
                },
                {"D0251",
                 "(D0247 + D0250)"
                },
                {"D0252",
                 "(D0242 * D0048)"
                },
                {"D0253",
                 "D0252"
                },
                {"D0254",
                 "(D0253 * D0034)"
                },
                {"D0255",
                 "(6 * (D0254))"
                },
                {"D0256",
                 "(D0251 + D0255)"
                },
                {"D0257",
                 "divr(D0067)"
                },
                {"D0258",
                 "multr(multr(D0065))"
                },
                {"D0264",
                 "(D0067 * D0017)"
                },
                {"D0265",
                 "multr(multr(D0065))"
                },
                {"D0266",
                 "(D0265 * D0020)"
                },
                {"D0267",
                 "divr(divr(D0266))"
                },
                {"D0268",
                 "(D0264 + D0267)"
                },
                {"D0270",
                 "(PH * D0031)"
                },
                {"D0271",
                 "(D0270 * D0025)"
                },
                {"D0272",
                 "(PS * PS)"
                },
                {"D0273",
                 "(D0272 * PS)"
                },
                {"D0274",
                 "(D0273 * PS)"
                },
                {"D0275",
                 "(D0274 * PS)"
                },
                {"D0276",
                 "(1 / (D0275))"
                },
                {"D0277",
                 "(D0271 * D0276)"
                },
                {"D0278",
                 "divsint(divsint(divsint(divsint(divr(divr(divr(divr(D0277))))))))"
                },
                {"D0280",
                 "(PH * D0004)"
                },
                {"D0281",
                 "(D0280 * D0048)"
                },
                {"D0282",
                 "divr(divr(D0281))"
                },
                {"D0287",
                 "divr(divr(D0280))"
                },
                {"D0288",
                 "dt(D0048)"
                },
                {"D0296",
                 "lap(PH)"
                },
                {"D0297",
                 "dr(PH)"
                },
                {"D0298",
                 "divr(D0297)"
                },
                {"D0299",
                 "dt(PH)"
                },
                {"D0300",
                 "(divsint(dt(multsint(D0299))) - dt(D0299))"
                },
                {"D0301",
                 "D0300"
                },
                {"D0302",
                 "divr(divr(D0301))"
                },
                {"D0303",
                 "(D0298 + D0302)"
                },
                {"D0304",
                 "(D0296 + D0303)"
                },
                {"D0305",
                 "(PH * D0178)"
                },
                {"D0306",
                 "(D0172 - D0162)"
                },
                {"D0307",
                 "(D0305 * D0306)"
                },
                {"D0308",
                 "(D0304 - D0307)"
                },
                {"D0309",
                 "(PH * D0033)"
                },
                {"D0310",
                 "(D0309 * D0033)"
                },
                {"D0311",
                 "(D0176 * D0310)"
                },
                {"D0312",
                 "((1 / 4) * (divsint(divsint(divsint(divsint(divr(divr(divr(divr(D0311))))))))))"
                },
                {"D0313",
                 "(2 * (D0312))"
                },
                {"D0314",
                 "(D0308 - D0313)"
                },
                {"D0315",
                 "(D0021 * D0021)"
                },
                {"D0316",
                 "(D0024 * D0024)"
                },
                {"D0317",
                 "divr(divr(D0316))"
                },
                {"D0318",
                 "(D0315 + D0317)"
                },
                {"D0319",
                 "lap2(D0001)"
                },
                {"D0320",
                 "(D0034 * D0034)"
                },
                {"D0321",
                 "(D0035 * D0035)"
                },
                {"D0322",
                 "divr(divr(D0321))"
                },
                {"D0323",
                 "(D0320 + D0322)"
                },
                {"D0324",
                 "(4 * (D0323))"
                },
                {"D0325",
                 "(D0319 + D0324)"
                },
                {"D0326",
                 "dr(log(PH))"
                },
                {"D0327",
                 "(D0034 * D0326)"
                },
                {"D0328",
                 "dt(log(PH))"
                },
                {"D0329",
                 "(D0035 * D0328)"
                },
                {"D0330",
                 "divr(divr(D0329))"
                },
                {"D0331",
                 "(D0327 + D0330)"
                },
                {"D0332",
                 "(4 * (D0331))"
                },
                {"D0333",
                 "(D0325 - D0332)"
                },
                {"D0334",
                 "dr(log(PH))"
                },
                {"D0335",
                 "divr(D0334)"
                },
                {"D0336",
                 "dt(log(PH))"
                },
                {"D0337",
                 "(divsint(dt(multsint(D0336))) - dt(D0336))"
                },
                {"D0338",
                 "D0337"
                },
                {"D0339",
                 "divr(divr(D0338))"
                },
                {"D0340",
                 "(D0335 + D0339)"
                },
                {"D0341",
                 "(2 * (D0340))"
                },
                {"D0342",
                 "(D0333 - D0341)"
                },
                {"D0343",
                 "(4 * (D0162))"
                },
                {"D0344",
                 "(D0172 - D0343)"
                },
                {"D0345",
                 "(D0178 * D0344)"
                },
                {"D0346",
                 "((1 / 2) * (D0345))"
                },
                {"D0347",
                 "(D0342 + D0346)"
                },
                {"D0348",
                 "(D0033 * D0033)"
                },
                {"D0349",
                 "(5 * (D0348))"
                },
                {"D0350",
                 "(3 * (D0318))"
                },
                {"D0351",
                 "(D0349 - D0350)"
                },
                {"D0352",
                 "(D0176 * D0351)"
                },
                {"D0353",
                 "((1 / 4) * (divsint(divsint(divsint(divsint(divr(divr(divr(divr(D0352))))))))))"
                },
                {"D0354",
                 "(D0347 + D0353)"
                },
                {"D0355",
                 "lap(D0006)"
                },
                {"D0356",
                 "dr(PH)"
                },
                {"D0357",
                 "(D0034 * D0356)"
                },
                {"D0358",
                 "dt(PH)"
                },
                {"D0359",
                 "(D0035 * D0358)"
                },
                {"D0360",
                 "divr(divr(D0359))"
                },
                {"D0361",
                 "(D0357 + D0360)"
                },
                {"D0362",
                 "(D0361 * D0005)"
                },
                {"D0363",
                 "(D0355 + D0362)"
                },
                {"D0364",
                 "dr(PH)"
                },
                {"D0365",
                 "divr(D0364)"
                },
                {"D0366",
                 "dt(PH)"
                },
                {"D0367",
                 "(divsint(dt(multsint(D0366))) - dt(D0366))"
                },
                {"D0368",
                 "D0367"
                },
                {"D0369",
                 "divr(divr(D0368))"
                },
                {"D0370",
                 "(D0365 + D0369)"
                },
                {"D0371",
                 "(D0370 * D0005)"
                },
                {"D0372",
                 "((1 / 2) * (D0371))"
                },
                {"D0373",
                 "(D0363 + D0372)"
                },
                {"D0374",
                 "(D0178 * D0162)"
                },
                {"D0375",
                 "((1 / 2) * (D0374))"
                },
                {"D0376",
                 "(D0373 + D0375)"
                },
                {"D0377",
                 "(D0033 * D0033)"
                },
                {"D0378",
                 "(D0318 - D0377)"
                },
                {"D0379",
                 "(D0176 * D0378)"
                },
                {"D0380",
                 "((1 / 4) * (divsint(divsint(divsint(divsint(divr(divr(divr(divr(D0379))))))))))"
                },
                {"D0381",
                 "(D0376 + D0380)"
                },
                {"D0382",
                 "multsint(D0218)"
                },
                {"D0383",
                 "multsint(D0257)"
                },
                {"D0384",
                 "multsint(D0258)"
                },
                {"D0385",
                 "dt(D0384)"
                },
                {"D0386",
                 "dt(D0258)"
                },
                {"D0387",
                 "multsint(D0386)"
                },
                {"D0388",
                 "(D0385 - D0387)"
                },
                {"D0389",
                 "divr(D0388)"
                },
                {"D0390",
                 "divr(D0389)"
                },
                {"D0391",
                 "(D0383 + D0390)"
                },
                {"D0392",
                 "(D0382 + D0391)"
                },
                {"D0393",
                 "multsint(D0268)"
                },
                {"D0394",
                 "(D0392 - D0393)"
                },
                {"D0395",
                 "multsint(D0278)"
                },
                {"D0396",
                 "(D0394 + D0395)"
                },
                {"D0397",
                 "multsint(D0282)"
                },
                {"D0398",
                 "dt(D0397)"
                },
                {"D0399",
                 "dt(D0282)"
                },
                {"D0400",
                 "multsint(D0399)"
                },
                {"D0401",
                 "(D0398 - D0400)"
                },
                {"D0402",
                 "(3 * (D0401))"
                },
                {"D0403",
                 "(D0396 + D0402)"
                },
                {"D0404",
                 "multsint(D0288)"
                },
                {"D0405",
                 "(D0287 * D0404)"
                },
                {"D0406",
                 "(D0403 + D0405)"
                },
                {"D0407",
                 "multsint(D0040)"
                },
                {"D0408",
                 "multsint(D0042)"
                },
                {"D0409",
                 "multsint(BT)"
                },
                {"D0410",
                 "dt(D0409)"
                },
                {"D0411",
                 "dt(BT)"
                },
                {"D0412",
                 "multsint(D0411)"
                },
                {"D0413",
                 "(D0410 - D0412)"
                },
                {"D0414",
                 "(D0408 + D0413)"
                },
                {"D0415",
                 "(D0407 + D0414)"
                },
                {"D0416",
                 "(D0036 * D0415)"
                },
                {"D0417",
                 "(-1 * (D0416))"
                },
                {"D0418",
                 "(D0280 * D0417)"
                },
                {"D0419",
                 "divr(D0418)"
                },
                {"D0420",
                 "divr(D0419)"
                },
                {"D0421",
                 "(D0420 * D0035)"
                },
                {"D0422",
                 "(6 * (D0421))"
                },
                {"D0423",
                 "(D0406 + D0422)"
                },
            };
            return D;
        }

        inline const std::vector<FiniteJEq>& equations()
        {
            static const std::vector<FiniteJEq> E = {
                {"EQTW",
                 "D0199"
                },
                {"ESHR",
                 "D0256"
                },
                {"ESHT",
                 "D0423"
                },
                {"EPHI",
                 "D0314"
                },
                {"EQFN",
                 "D0354"
                },
                {"ESIG",
                 "D0381"
                },
            };
            return E;
        }

        inline const std::vector<FiniteJCheck>& checks()
        {
            static const std::vector<FiniteJCheck> C = {
                {"CK0010", "D0010", "D0007 D0009",
                 "(D0007 - D0009)"
                },
                {"CK0014", "D0014", "D0011 D0013",
                 "(D0011 - D0013)"
                },
                {"CK0017", "D0017", "D0010 D0016",
                 "(D0010 - D0016)"
                },
                {"CK0020", "D0020", "D0014 D0019",
                 "(D0014 - D0019)"
                },
                {"CK0024", "D0024", "D0022 D0023",
                 "(D0022 + D0023)"
                },
                {"CK0029", "D0029", "D0027 D0028",
                 "(D0027 + D0028)"
                },
                {"CK0039", "D0039", "D0037 D0038",
                 "(D0037 + D0038)"
                },
                {"CK0043", "D0043", "",
                 "(divsint(dt(multsint(BT))) - dt(BT))"
                },
                {"CK0045", "D0045", "D0042 D0044",
                 "(D0042 + D0044)"
                },
                {"CK0046", "D0046", "D0040 D0045",
                 "(D0040 + D0045)"
                },
                {"CK0052", "D0052", "D0050 D0051",
                 "(D0050 + D0051)"
                },
                {"CK0055", "D0055", "D0053 D0054",
                 "(D0053 + D0054)"
                },
                {"CK0058", "D0058", "D0056 D0057",
                 "(D0056 + D0057)"
                },
                {"CK0059", "D0059", "D0049 D0058",
                 "(D0049 + D0058)"
                },
                {"CK0061", "D0061", "D0059 D0060",
                 "(D0060 - D0059)"
                },
                {"CK0065", "D0065", "D0063 D0064",
                 "(D0063 - D0064)"
                },
                {"CK0067", "D0067", "D0052 D0066",
                 "(D0052 + D0066)"
                },
                {"CK0081", "D0081", "D0077 D0080",
                 "(D0077 + D0080)"
                },
                {"CK0085", "D0085", "D0081 D0084",
                 "(D0081 + D0084)"
                },
                {"CK0093", "D0093", "D0091 D0092",
                 "(D0091 - D0092)"
                },
                {"CK0097", "D0097", "D0095 D0096",
                 "(D0095 - D0096)"
                },
                {"CK0101", "D0101", "D0099 D0100",
                 "(D0099 - D0100)"
                },
                {"CK0108", "D0108", "D0103 D0107",
                 "(D0103 - D0107)"
                },
                {"CK0114", "D0114", "D0109 D0113",
                 "(D0109 - D0113)"
                },
                {"CK0116", "D0116", "D0088 D0115",
                 "(D0088 + D0115)"
                },
                {"CK0119", "D0119", "",
                 "(divsint(dt(multsint(BT))) - dt(BT))"
                },
                {"CK0121", "D0121", "D0118 D0120",
                 "(D0118 + D0120)"
                },
                {"CK0122", "D0122", "D0117 D0121",
                 "(D0117 + D0121)"
                },
                {"CK0126", "D0126", "D0093 D0125",
                 "(D0093 + D0125)"
                },
                {"CK0128", "D0128", "D0124 D0127",
                 "(D0124 + D0127)"
                },
                {"CK0131", "D0131", "D0129",
                 "(divsint(dt(multsint(D0129))) - dt(D0129))"
                },
                {"CK0133", "D0133", "D0130 D0132",
                 "(D0130 + D0132)"
                },
                {"CK0134", "D0134", "D0128 D0133",
                 "(D0128 + D0133)"
                },
                {"CK0136", "D0136", "D0134 D0135",
                 "(D0134 + D0135)"
                },
                {"CK0140", "D0140", "D0138 D0139",
                 "(D0138 + D0139)"
                },
                {"CK0143", "D0143", "D0140 D0142",
                 "(D0140 + D0142)"
                },
                {"CK0145", "D0145", "D0143 D0144",
                 "(D0143 + D0144)"
                },
                {"CK0146", "D0146", "",
                 "(divsint(dt(multsint(BT))) - dt(BT))"
                },
                {"CK0149", "D0149", "D0145 D0148",
                 "(D0145 + D0148)"
                },
                {"CK0152", "D0152", "D0150 D0151",
                 "(D0150 + D0151)"
                },
                {"CK0156", "D0156", "D0154 D0155",
                 "(D0154 + D0155)"
                },
                {"CK0161", "D0161", "D0159 D0160",
                 "(D0159 + D0160)"
                },
                {"CK0168", "D0168", "D0165 D0167",
                 "(D0165 + D0167)"
                },
                {"CK0172", "D0172", "D0085 D0171",
                 "(D0085 + D0171)"
                },
                {"CK0183", "D0183", "D0182",
                 "(divsint(dt(multsint(D0182))) - dt(D0182))"
                },
                {"CK0186", "D0186", "D0181 D0185",
                 "(D0181 + D0185)"
                },
                {"CK0188", "D0188", "D0179 D0187",
                 "(D0179 - D0187)"
                },
                {"CK0190", "D0190", "D0188 D0189",
                 "(D0188 + D0189)"
                },
                {"CK0194", "D0194", "D0190 D0193",
                 "(D0190 + D0193)"
                },
                {"CK0197", "D0197", "D0169 D0196",
                 "(D0196 + D0169)"
                },
                {"CK0199", "D0199", "D0194 D0198",
                 "(D0194 + D0198)"
                },
                {"CK0205", "D0205", "D0203 D0204",
                 "(D0203 + D0204)"
                },
                {"CK0206", "D0206", "D0201 D0205",
                 "(D0201 + D0205)"
                },
                {"CK0208", "D0208", "D0200 D0207",
                 "(D0200 + D0207)"
                },
                {"CK0211", "D0211", "D0209 D0210",
                 "(D0209 + D0210)"
                },
                {"CK0215", "D0215", "D0213 D0214",
                 "(D0213 - D0214)"
                },
                {"CK0216", "D0216", "D0212 D0215",
                 "(D0212 + D0215)"
                },
                {"CK0218", "D0218", "D0211 D0217",
                 "(D0211 + D0217)"
                },
                {"CK0221", "D0221", "D0220",
                 "(divsint(dt(multsint(D0220))) - dt(D0220))"
                },
                {"CK0224", "D0224", "D0219 D0223",
                 "(D0219 + D0223)"
                },
                {"CK0225", "D0225", "D0208 D0224",
                 "(D0208 + D0224)"
                },
                {"CK0230", "D0230", "D0226 D0229",
                 "(D0226 + D0229)"
                },
                {"CK0231", "D0231", "D0225 D0230",
                 "(D0225 - D0230)"
                },
                {"CK0241", "D0241", "D0231 D0240",
                 "(D0231 + D0240)"
                },
                {"CK0247", "D0247", "D0241 D0246",
                 "(D0241 + D0246)"
                },
                {"CK0251", "D0251", "D0247 D0250",
                 "(D0247 + D0250)"
                },
                {"CK0256", "D0256", "D0251 D0255",
                 "(D0251 + D0255)"
                },
                {"CK0268", "D0268", "D0264 D0267",
                 "(D0264 + D0267)"
                },
                {"CK0300", "D0300", "D0299",
                 "(divsint(dt(multsint(D0299))) - dt(D0299))"
                },
                {"CK0303", "D0303", "D0298 D0302",
                 "(D0298 + D0302)"
                },
                {"CK0304", "D0304", "D0296 D0303",
                 "(D0296 + D0303)"
                },
                {"CK0306", "D0306", "D0162 D0172",
                 "(D0172 - D0162)"
                },
                {"CK0308", "D0308", "D0304 D0307",
                 "(D0304 - D0307)"
                },
                {"CK0314", "D0314", "D0308 D0313",
                 "(D0308 - D0313)"
                },
                {"CK0318", "D0318", "D0315 D0317",
                 "(D0315 + D0317)"
                },
                {"CK0323", "D0323", "D0320 D0322",
                 "(D0320 + D0322)"
                },
                {"CK0325", "D0325", "D0319 D0324",
                 "(D0319 + D0324)"
                },
                {"CK0331", "D0331", "D0327 D0330",
                 "(D0327 + D0330)"
                },
                {"CK0333", "D0333", "D0325 D0332",
                 "(D0325 - D0332)"
                },
                {"CK0337", "D0337", "D0336",
                 "(divsint(dt(multsint(D0336))) - dt(D0336))"
                },
                {"CK0340", "D0340", "D0335 D0339",
                 "(D0335 + D0339)"
                },
                {"CK0342", "D0342", "D0333 D0341",
                 "(D0333 - D0341)"
                },
                {"CK0344", "D0344", "D0172 D0343",
                 "(D0172 - D0343)"
                },
                {"CK0347", "D0347", "D0342 D0346",
                 "(D0342 + D0346)"
                },
                {"CK0351", "D0351", "D0349 D0350",
                 "(D0349 - D0350)"
                },
                {"CK0354", "D0354", "D0347 D0353",
                 "(D0347 + D0353)"
                },
                {"CK0361", "D0361", "D0357 D0360",
                 "(D0357 + D0360)"
                },
                {"CK0363", "D0363", "D0355 D0362",
                 "(D0355 + D0362)"
                },
                {"CK0367", "D0367", "D0366",
                 "(divsint(dt(multsint(D0366))) - dt(D0366))"
                },
                {"CK0370", "D0370", "D0365 D0369",
                 "(D0365 + D0369)"
                },
                {"CK0373", "D0373", "D0363 D0372",
                 "(D0363 + D0372)"
                },
                {"CK0376", "D0376", "D0373 D0375",
                 "(D0373 + D0375)"
                },
                {"CK0378", "D0378", "D0318 D0377",
                 "(D0318 - D0377)"
                },
                {"CK0381", "D0381", "D0376 D0380",
                 "(D0376 + D0380)"
                },
                {"CK0388", "D0388", "D0385 D0387",
                 "(D0385 - D0387)"
                },
                {"CK0391", "D0391", "D0383 D0390",
                 "(D0383 + D0390)"
                },
                {"CK0392", "D0392", "D0382 D0391",
                 "(D0382 + D0391)"
                },
                {"CK0394", "D0394", "D0392 D0393",
                 "(D0392 - D0393)"
                },
                {"CK0396", "D0396", "D0394 D0395",
                 "(D0394 + D0395)"
                },
                {"CK0401", "D0401", "D0398 D0400",
                 "(D0398 - D0400)"
                },
                {"CK0403", "D0403", "D0396 D0402",
                 "(D0396 + D0402)"
                },
                {"CK0406", "D0406", "D0403 D0405",
                 "(D0403 + D0405)"
                },
                {"CK0413", "D0413", "D0410 D0412",
                 "(D0410 - D0412)"
                },
                {"CK0414", "D0414", "D0408 D0413",
                 "(D0408 + D0413)"
                },
                {"CK0415", "D0415", "D0407 D0414",
                 "(D0407 + D0414)"
                },
                {"CK0423", "D0423", "D0406 D0422",
                 "(D0406 + D0422)"
                },
            };
            return C;
        }

        /// Read a def into CONFIGURATION space.  Fetching the Val_domain
        /// is not enough -- indexing it is what converts, and a probe that
        /// only fetched returned two false negatives (round 108).
        inline void read_def(Kadath::System_of_eqs& syst,
                             const Kadath::Space& sp, const char* nm,
                             int dmin, int dmax)
        {
            for (int d = dmin; d <= dmax; d++) {
                const Kadath::Val_domain& v =
                    syst.give_val_def_scalar_domain(nm, d);
                Kadath::Index ix(sp.get_domain(d)->get_nbr_points());
                (void)v(ix);
            }
        }
    } // namespace finiteJ_detail

    /// The sub-def names, in dependency order, for reading values back.
    inline const std::vector<const char*>& finiteJ_names()
    {
        static const std::vector<const char*> N = [] {
            std::vector<const char*> v;
            for (const auto& d : finiteJ_detail::subdefs()) v.push_back(d.name);
            return v;
        }();
        return N;
    }

    /// The six equation names.
    inline const std::vector<const char*>& finiteJ_eq_names()
    {
        static const std::vector<const char*> N = [] {
            std::vector<const char*> v;
            for (const auto& e : finiteJ_detail::equations()) v.push_back(e.name);
            return v;
        }();
        return N;
    }

    /// The angular bases this emission was analysed under.  The caller
    /// MUST register the six unknowns in these bases: the basis lattice
    /// that decided every sum ordering assumed them, and if the run
    /// registers something else the analysis describes a different
    /// system.  Names, not integers, so a renumbering in the library
    /// cannot silently reinterpret them.
    inline const std::vector<std::pair<const char*, const char*>>&
    finiteJ_declared_basis()
    {
        static const std::vector<std::pair<const char*, const char*>> B = {
            {"PS", "COS_EVEN"},
            {"PH", "COS_EVEN"},
            {"QF", "COS_EVEN"},
            {"BR", "COS_EVEN"},
            {"BT", "SIN_EVEN"},
            {"QB", "COS_ODD"},
        };
        return B;
    }

    /// Sums reordered by --order-sums, which is seed-specific: see the
    /// header comment.  Empty means the emission was written without it.
    inline const std::vector<const char*>& finiteJ_ordered_sums()
    {
        static const std::vector<const char*> O = {
        };
        return O;
    }

    /// Emission-time AXIS PRECONDITION violations carried into the
    /// artefact: each is a divsint applied where the emitter could not
    /// show the operand vanishes on the axis.  Empty is the only
    /// acceptable state, and since round 342 it is the only reachable
    /// one: the emitter refuses to write a violating emission at all.
    inline const std::vector<const char*>& finiteJ_axis_violations()
    {
        static const std::vector<const char*> V = {
        };
        return V;
    }

    /**
     * Register the emission, keeping the read-state contract.
     *
     * read_defs = false deliberately BREAKS the contract.  It exists so a
     * caller can show finiteJ_check() catches the breach; nothing else
     * should ever pass it.
     */
    inline void finiteJ_register(Kadath::System_of_eqs& syst,
                                 const Kadath::Space& sp, int dmin, int dmax,
                                 bool read_defs = true)
    {
        for (const auto& d : finiteJ_detail::subdefs()) {
            syst.add_def((std::string(d.name) + " = " + d.def).c_str());
            if (read_defs)
                finiteJ_detail::read_def(syst, sp, d.name, dmin, dmax);
        }
        for (const auto& e : finiteJ_detail::equations()) {
            syst.add_def((std::string(e.name) + " = " + e.def).c_str());
            if (read_defs)
                finiteJ_detail::read_def(syst, sp, e.name, dmin, dmax);
        }
    }

    /**
     * THE CONTROL.  Re-register every sum with its operands READ first and
     * compare pointwise with the original.  Returns the worst relative
     * difference and throws above tol.
     *
     * ⚠ Reading the operands before re-parsing is the whole mechanism.  A
     * version that re-registers without reading puts both spellings in the
     * same evaluator state, and two spellings in one state cannot
     * discriminate a defect whose variable IS the state -- which is how
     * round 107 shipped a check weaker than it was reported to be.
     */
    inline double finiteJ_check(Kadath::System_of_eqs& syst,
                                const Kadath::Space& sp, int dmin, int dmax,
                                double tol = 1e-12)
    {
        double worst = 0.0;
        std::string worst_name;
        for (const auto& c : finiteJ_detail::checks()) {
            std::istringstream is(c.reads);
            for (std::string nm; is >> nm;)
                finiteJ_detail::read_def(syst, sp, nm.c_str(), dmin, dmax);
            syst.add_def((std::string(c.name) + " = " + c.def).c_str());
            double mx = 0.0, scale = 0.0;
            for (int d = dmin; d <= dmax; d++) {
                const Kadath::Val_domain& a =
                    syst.give_val_def_scalar_domain(c.of, d);
                const Kadath::Val_domain& b =
                    syst.give_val_def_scalar_domain(c.name, d);
                Kadath::Index ix(sp.get_domain(d)->get_nbr_points());
                do {
                    mx = std::max(mx, std::fabs(a(ix) - b(ix)));
                    scale = std::max(scale, std::fabs(a(ix)));
                } while (ix.inc());
            }
            const double rel = mx / std::max(scale, 1e-300);
            if (rel > worst) { worst = rel; worst_name = c.of; }
        }
        if (worst > tol)
            throw std::runtime_error(
                "finiteJ read-state contract broken: " + worst_name
                + " differs from its own re-expression by "
                + std::to_string(worst)
                + " -- the defs were registered without being read");
        return worst;
    }

} // namespace Trumpet
