/*
 * finiteJ_eqs.hpp -- GENERATED by scripts/finiteJ_emit.py.  Do not edit.
 *
 * The six finite-J equations as Kadath defs, emitted from the ASSEMBLY's
 * structure rather than from an expanded expression: where the assembly
 * applied lap2S the emission says lap2, instead of expanding and hoping to
 * recognise it again.
 *
 * Unknowns PS, PH, QF, BR, BT, QB.  Spin constant JJ.  There are NO sin or
 * cos FIELDS: round 103 measured that neither lies in the scalar COS_EVEN
 * span, so an add_cst holding one stores an alias.  Angular and radial
 * factors go through the coefficient-space operators instead, and
 *
 *     cot(theta) * X  ==  divsint(dt(multsint(X))) - dt(X)
 *
 * which the probe verified to 2e-16 on a field vanishing on the axis.
 *
 * Registered as 23 named sub-defs then the six equations: the parser has a
 * STACK-depth limit near 1000 characters that was not reproducible run to
 * run, so every piece here is kept far below it.
 */
#pragma once

#include <string>
#include <vector>

namespace Trumpet
{
    struct FiniteJEq { const char* name; const char* def; };

    /// T1..T23, in dependency order; register these FIRST.
    inline const std::vector<FiniteJEq>& finiteJ_subdefs()
    {
        static const std::vector<FiniteJEq> D = {
            {"T1",
             "multr(multr(multr(multr(((1 / 2) * (((PS * (1 / (PH))) * ((2 * (divr(divr(dt(BT) + "
             "divr(BR))))) - divr(divr(dr(BR) + (dt(BT) + divr(BR)))))))) * ((1 / 2) * (((PS * (1 "
             "/ (PH))) * ((2 * (divr(divr(dt(BT) + divr(BR))))) - divr(divr(dr(BR) + (dt(BT) + "
             "divr(BR))))))))))))"
            },
            {"T2",
             "(((((1 / 2) * (((PS * (1 / (PH))) * ((2 * (dr(BR))) - (dr(BR) + (dt(BT) + "
             "divr(BR))))))) * ((1 / 2) * (((PS * (1 / (PH))) * ((2 * (dr(BR))) - (dr(BR) + "
             "(dt(BT) + divr(BR)))))))) + T1) + multr(multr(2 * ((((1 / 2) * (((PS * (1 / (PH))) * "
             "(dr(BT) + divr(divr(dt(BR) + (-1 * (multr(BT))))))))) * ((1 / 2) * (((PS * (1 / "
             "(PH))) * (dr(BT) + divr(divr(dt(BR) + (-1 * (multr(BT))))))))))))))"
            },
            {"T3",
             "((BR * dr(-1 * (((PS * (1 / (PH))) * ((BR * ((2 * (dr((1 / 2) * (log(PS))))) + "
             "divr(ones))) + (BT * ((2 * (dt((1 / 2) * (log(PS))))) + (divsint(dt(multsint(ones))) "
             "- dt(ones))))))))) + (BT * dt(-1 * (((PS * (1 / (PH))) * ((BR * ((2 * (dr((1 / 2) * "
             "(log(PS))))) + divr(ones))) + (BT * ((2 * (dt((1 / 2) * (log(PS))))) + "
             "(divsint(dt(multsint(ones))) - dt(ones))))))))))"
            },
            {"T4",
             "((PS * (1 / (PH))) * ((BR * dr(-1 * (((PS * (1 / (PH))) * ((BR * dr(QB)) + (BT * "
             "(dt(QB) + (6*JJ * (multsint(multsint(multsint(ones)))))))))))) + (BT * dt(-1 * (((PS "
             "* (1 / (PH))) * ((BR * dr(QB)) + (BT * (dt(QB) + (6*JJ * "
             "(multsint(multsint(multsint(ones))))))))))))))"
            },
            {"T5",
             "((-1 * (((PS * (1 / (PH))) * ((BR * ((2 * (dr((1 / 2) * (log(PS))))) + divr(ones))) "
             "+ (BT * ((2 * (dt((1 / 2) * (log(PS))))) + (divsint(dt(multsint(ones))) - "
             "dt(ones)))))))) * (-1 * (((PS * (1 / (PH))) * ((BR * ((2 * (dr((1 / 2) * "
             "(log(PS))))) + divr(ones))) + (BT * ((2 * (dt((1 / 2) * (log(PS))))) + "
             "(divsint(dt(multsint(ones))) - dt(ones)))))))))"
            },
            {"T6",
             "(((lap2(QB) - (3 * ((divr(dr(QB)) + divr(divr(divsint(dt(multsint(dt(QB)))) - "
             "dt(dt(QB)))))))) + (dr(QB) * (dr(log(PH)) - (4 * (dr(log(PS))))))) + "
             "divr(divr(multr(multr(divr(divr(dt(QB) + (6*JJ * "
             "(multsint(multsint(multsint(ones))))))))) * (dt(log(PH)) - (4 * (dt(log(PS))))))))"
            },
            {"T7",
             "((-1 * (((PS * (1 / (PH))) * ((BR * dr(QB)) + (BT * (dt(QB) + (6*JJ * "
             "(multsint(multsint(multsint(ones))))))))))) * (-1 * (((PS * (1 / (PH))) * ((BR * ((2 "
             "* (dr((1 / 2) * (log(PS))))) + divr(ones))) + (BT * ((2 * (dt((1 / 2) * (log(PS))))) "
             "+ (divsint(dt(multsint(ones))) - dt(ones)))))))))"
            },
            {"T8",
             "((dr(dr(BR)) + divr(divr(dt(dt(BR) + (-1 * (multr(BT)))) + ((-1 * (-1 * "
             "(multr(dr(BR))))) + (-1 * (multr(dt(BT) + divr(BR)))))))) + (divr((2 * (dr(BR))) - "
             "(dr(BR) + (dt(BT) + divr(BR)))) + divr(divr(divsint(dt(multsint(multr(multr(dr(BT) + "
             "divr(divr(dt(BR) + (-1 * (multr(BT)))))))))) - dt(multr(multr(dr(BT) + "
             "divr(divr(dt(BR) + (-1 * (multr(BT))))))))))))"
            },
            {"T9",
             "((T8 - ((((2 * (dr(BR))) - (dr(BR) + (dt(BT) + divr(BR)))) * ((dr(log(PH)) - (4 * "
             "(dr(log(PS))))) - (2 * (dr(QF))))) + divr(divr(multr(multr(dr(BT) + divr(divr(dt(BR) "
             "+ (-1 * (multr(BT))))))) * ((dt(log(PH)) - (4 * (dt(log(PS))))) - (2 * "
             "(dt(QF)))))))) + divsint(divsint(divsint(divsint(divr(divr(divr(divr(((PH * (-1 * "
             "(((PS * (1 / (PH))) * ((BR * dr(QB)) + (BT * (dt(QB) + (6*JJ * "
             "(multsint(multsint(multsint(ones)))))))))))) * dr(QB)) * (1 / ((((((PS * PS) * PS) * "
             "PS) * PS) * PS) * PS)))))))))))"
            },
            {"T10",
             "((T9 + (3 * (divr((PH * (1 / (PS))) * (-1 * (((PS * (1 / (PH))) * ((BR * ((2 * "
             "(dr((1 / 2) * (log(PS))))) + divr(ones))) + (BT * ((2 * (dt((1 / 2) * (log(PS))))) + "
             "(divsint(dt(multsint(ones))) - dt(ones)))))))))))) + ((PH * (1 / (PS))) * dr(-1 * "
             "(((PS * (1 / (PH))) * ((BR * ((2 * (dr((1 / 2) * (log(PS))))) + divr(ones))) + (BT * "
             "((2 * (dt((1 / 2) * (log(PS))))) + (divsint(dt(multsint(ones))) - dt(ones))))))))))"
            },
            {"T11",
             "(divr(dr(BT) + divr(divr(dt(BR) + (-1 * (multr(BT)))))) + "
             "divr(divr(divsint(dt(multsint(multr(multr((2 * (divr(divr(dt(BT) + divr(BR))))) - "
             "divr(divr(dr(BR) + (dt(BT) + divr(BR))))))))) - dt(multr(multr((2 * "
             "(divr(divr(dt(BT) + divr(BR))))) - divr(divr(dr(BR) + (dt(BT) + divr(BR))))))))))"
            },
            {"T12",
             "(((dr(BT) + divr(divr(dt(BR) + (-1 * (multr(BT)))))) * ((dr(log(PH)) - (4 * "
             "(dr(log(PS))))) - (2 * (dr(QF))))) + divr(divr(multr(multr((2 * (divr(divr(dt(BT) + "
             "divr(BR))))) - divr(divr(dr(BR) + (dt(BT) + divr(BR)))))) * ((dt(log(PH)) - (4 * "
             "(dt(log(PS))))) - (2 * (dt(QF)))))))"
            },
            {"T13",
             "divsint(divsint(divsint(divsint(divr(divr(divr(divr(((PH * (-1 * (((PS * (1 / (PH))) "
             "* ((BR * dr(QB)) + (BT * (dt(QB) + (6*JJ * "
             "(multsint(multsint(multsint(ones)))))))))))) * divr(divr(dt(QB) + (6*JJ * "
             "(multsint(multsint(multsint(ones)))))))) * (1 / ((((((PS * PS) * PS) * PS) * PS) * "
             "PS) * PS))))))))))"
            },
            {"T14",
             "(divsint(dt(multsint(divr(divr((PH * (1 / (PS))) * (-1 * (((PS * (1 / (PH))) * ((BR "
             "* ((2 * (dr((1 / 2) * (log(PS))))) + divr(ones))) + (BT * ((2 * (dt((1 / 2) * "
             "(log(PS))))) + (divsint(dt(multsint(ones))) - dt(ones))))))))))))) - "
             "dt(divr(divr((PH * (1 / (PS))) * (-1 * (((PS * (1 / (PH))) * ((BR * ((2 * (dr((1 / "
             "2) * (log(PS))))) + divr(ones))) + (BT * ((2 * (dt((1 / 2) * (log(PS))))) + "
             "(divsint(dt(multsint(ones))) - dt(ones))))))))))))"
            },
            {"T15",
             "(((((((dr(dr(BT)) + divr(dr(BT))) + divr(divr(dt(dt(BT) + divr(BR)) + (divr(dt(BR) + "
             "(-1 * (multr(BT)))) - (-1 * (multr(dr(BT)))))))) + T11) - T12) + T13) + (3 * (T14))) "
             "+ (divr(divr(PH * (1 / (PS)))) * dt(-1 * (((PS * (1 / (PH))) * ((BR * ((2 * (dr((1 / "
             "2) * (log(PS))))) + divr(ones))) + (BT * ((2 * (dt((1 / 2) * (log(PS))))) + "
             "(divsint(dt(multsint(ones))) - dt(ones))))))))))"
            },
            {"T16",
             "((PH * (((-1 * (((PS * (1 / (PH))) * ((BR * dr(QB)) + (BT * (dt(QB) + (6*JJ * "
             "(multsint(multsint(multsint(ones))))))))))) * (1 / (PS))) * exp(-1 * (QF)))) * (((-1 "
             "* (((PS * (1 / (PH))) * ((BR * dr(QB)) + (BT * (dt(QB) + (6*JJ * "
             "(multsint(multsint(multsint(ones))))))))))) * (1 / (PS))) * exp(-1 * (QF))))"
            },
            {"T17",
             "(((lap(PH) + (divr(dr(PH)) + divr(divr(divsint(dt(multsint(dt(PH)))) - "
             "dt(dt(PH)))))) - ((PH * ((PS * PS) * exp(2 * (QF)))) * ((T2 + ((3 / 2) * (T5))) - "
             "((PS * (1 / (PH))) * T3)))) - (T16 * ((1 / 4) * "
             "(divsint(divsint(divsint(divsint(divr(divr(divr(divr(1 / (((PS * PS) * PS) * "
             "PS)))))))))))))"
            },
            {"T18",
             "(((lap2(QF) + (4 * (((dr((1 / 2) * (log(PS))) * dr((1 / 2) * (log(PS)))) + "
             "divr(divr(dt((1 / 2) * (log(PS))) * dt((1 / 2) * (log(PS))))))))) - (4 * (((dr((1 / "
             "2) * (log(PS))) * dr(log(PH))) + divr(divr(dt((1 / 2) * (log(PS))) * "
             "dt(log(PH)))))))) - (2 * ((divr(dr(log(PH))) + "
             "divr(divr(divsint(dt(multsint(dt(log(PH))))) - dt(dt(log(PH)))))))))"
            },
            {"T19",
             "((((-1 * (((PS * (1 / (PH))) * ((BR * dr(QB)) + (BT * (dt(QB) + (6*JJ * "
             "(multsint(multsint(multsint(ones))))))))))) * (1 / (PS))) * exp(-1 * (QF))) * (((-1 "
             "* (((PS * (1 / (PH))) * ((BR * dr(QB)) + (BT * (dt(QB) + (6*JJ * "
             "(multsint(multsint(multsint(ones))))))))))) * (1 / (PS))) * exp(-1 * (QF))))"
            },
            {"T20",
             "(((5 * (T19)) - (3 * (((dr(QB) * dr(QB)) + divr(divr((dt(QB) + (6*JJ * "
             "(multsint(multsint(multsint(ones)))))) * (dt(QB) + (6*JJ * "
             "(multsint(multsint(multsint(ones)))))))))))) * ((1 / 4) * "
             "(divsint(divsint(divsint(divsint(divr(divr(divr(divr(1 / (((PS * PS) * PS) * "
             "PS))))))))))))"
            },
            {"T21",
             "(((lap((1 / 2) * (log(PS))) + (((dr((1 / 2) * (log(PS))) * dr(PH)) + divr(divr(dt((1 "
             "/ 2) * (log(PS))) * dt(PH)))) * (1 / (PH)))) + ((1 / 2) * (((divr(dr(PH)) + "
             "divr(divr(divsint(dt(multsint(dt(PH)))) - dt(dt(PH))))) * (1 / (PH)))))) + ((1 / 2) "
             "* ((((PS * PS) * exp(2 * (QF))) * ((PS * (1 / (PH))) * T3)))))"
            },
            {"T22",
             "((((-1 * (((PS * (1 / (PH))) * ((BR * dr(QB)) + (BT * (dt(QB) + (6*JJ * "
             "(multsint(multsint(multsint(ones))))))))))) * (1 / (PS))) * exp(-1 * (QF))) * (((-1 "
             "* (((PS * (1 / (PH))) * ((BR * dr(QB)) + (BT * (dt(QB) + (6*JJ * "
             "(multsint(multsint(multsint(ones))))))))))) * (1 / (PS))) * exp(-1 * (QF))))"
            },
            {"T23",
             "((((dr(QB) * dr(QB)) + divr(divr((dt(QB) + (6*JJ * "
             "(multsint(multsint(multsint(ones)))))) * (dt(QB) + (6*JJ * "
             "(multsint(multsint(multsint(ones))))))))) - T22) * ((1 / 4) * "
             "(divsint(divsint(divsint(divsint(divr(divr(divr(divr(1 / (((PS * PS) * PS) * "
             "PS))))))))))))"
            },
        };
        return D;
    }

    inline const std::vector<FiniteJEq>& finiteJ_eqs()
    {
        static const std::vector<FiniteJEq> E = {
            {"EQTW",
             "(T6 + (((PS * PS) * exp(2 * (QF))) * ((4 * (T7)) + T4)))"
            },
            {"ESHR",
             "(T10 + (6 * ((((PH * (1 / (PS))) * (-1 * (((PS * (1 / (PH))) * ((BR * ((2 * (dr((1 / "
             "2) * (log(PS))))) + divr(ones))) + (BT * ((2 * (dt((1 / 2) * (log(PS))))) + "
             "(divsint(dt(multsint(ones))) - dt(ones))))))))) * dr((1 / 2) * (log(PS)))))))"
            },
            {"ESHT",
             "(T15 + (6 * ((divr(divr((PH * (1 / (PS))) * (-1 * (((PS * (1 / (PH))) * ((BR * ((2 * "
             "(dr((1 / 2) * (log(PS))))) + divr(ones))) + (BT * ((2 * (dt((1 / 2) * (log(PS))))) + "
             "(divsint(dt(multsint(ones))) - dt(ones)))))))))) * dt((1 / 2) * (log(PS)))))))"
            },
            {"EPHI",
             "T17"
            },
            {"EQFN",
             "((T18 + ((1 / 2) * ((((PS * PS) * exp(2 * (QF))) * ((T2 + ((3 / 2) * (T5))) - (4 * "
             "(((PS * (1 / (PH))) * T3)))))))) + T20)"
            },
            {"ESIG",
             "(T21 + T23)"
            },
        };
        return E;
    }

} // namespace Trumpet
