/*
 * finiteJ_eqs.hpp -- GENERATED by scripts/finiteJ_emit.py.  Do not edit.
 *
 * ⚠ --q-regular: q = sin^2(theta) q~.  The unknown QF DENOTES q~ in this
 * emission (research round 578; code round 279), so q vanishes on the
 * axis by construction.  Build it as finiteJ_probe_qreg only.
 *
 * The six finite-J equations as Kadath defs, emitted from the ASSEMBLY's
 * structure rather than from an expanded expression: where the assembly
 * applied lap2S the emission says lap2, instead of expanding and hoping to
 * recognise it again.
 *
 * Unknowns PS, PH, QF, BR, BT, QB.  Spin constant JJ.  There are NO sin or
 * cos FIELDS: round 103 measured that neither lies in the scalar COS_EVEN
 * span, so an add_cst holding one stores an alias.  Angular and radial
 * factors go through the coefficient-space operators instead, and
 *
 *     cot(theta) * X  ==  divsint(dt(multsint(X))) - dt(X)
 *
 * which the probe verified to 2e-16 on a field vanishing on the axis.
 *
 * Registered as 337 named sub-defs then the six equations: the parser has a
 * STACK-depth limit near 1000 characters that was not reproducible run to
 * run, so every piece here is kept far below it.
 *
 * ⚠ THE READ-STATE CONTRACT (round 108).  Kadath evaluates a sum
 * differently depending on whether its named operands have been READ --
 * indexed, which forces a Val_domain into configuration space -- before
 * the sum is parsed, and a def parsed in the wrong state does not recover
 * when its operands are read later.  Every sub-def below must therefore be
 * read immediately after it is registered.  That is why the def TEXT is not
 * exported: register through finiteJ_register(), which does it, and call
 * finiteJ_check(), which fails loudly if it was not done.  A requirement in
 * prose gets transcribed wrongly; this one is in the only function that can
 * reach the text.
 */
#pragma once

#include "For_Kadath/Array/headcpp.hpp"
#include "For_Kadath/Space/space.hpp"
#include "For_Kadath/System_of_eqs/system_of_eqs.hpp"

#include <algorithm>
#include <cmath>
#include <sstream>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

namespace Trumpet
{
    struct FiniteJEq { const char* name; const char* def; };

    /// One sum, re-expressed.  `reads` are the operands finiteJ_check()
    /// reads before re-parsing `def`, which is what lets it discriminate.
    struct FiniteJCheck {
        const char* name; const char* of; const char* reads; const char* def;
    };

    namespace finiteJ_detail
    {
        /// ⚠ The def TEXT.  Registering any of this by hand skips the read
        /// the evaluator needs; go through finiteJ_register() instead.
        inline const std::vector<FiniteJEq>& subdefs()
        {
            static const std::vector<FiniteJEq> D = {
                {"D0001",
                 "multsint(multsint(QF))"
                },
                {"D0002",
                 "multsint(multsint(multsint(multsint(QB))))"
                },
                {"D0003",
                 "(2 * (D0001))"
                },
                {"D0004",
                 "(1 / (PS))"
                },
                {"D0005",
                 "(1 / (PH))"
                },
                {"D0006",
                 "((1 / 2) * (log(PS)))"
                },
                {"D0007",
                 "dr(log(PH))"
                },
                {"D0008",
                 "dr(log(PS))"
                },
                {"D0009",
                 "(4 * (D0008))"
                },
                {"D0010",
                 "(D0007 - D0009)"
                },
                {"D0011",
                 "dt(log(PH))"
                },
                {"D0012",
                 "dt(log(PS))"
                },
                {"D0013",
                 "(4 * (D0012))"
                },
                {"D0014",
                 "(D0011 - D0013)"
                },
                {"D0015",
                 "dr(D0001)"
                },
                {"D0016",
                 "(2 * (D0015))"
                },
                {"D0017",
                 "(D0010 - D0016)"
                },
                {"D0018",
                 "dt(D0001)"
                },
                {"D0019",
                 "(2 * (D0018))"
                },
                {"D0020",
                 "(D0014 - D0019)"
                },
                {"D0021",
                 "dr(D0002)"
                },
                {"D0022",
                 "dt(D0002)"
                },
                {"D0023",
                 "(6*JJ * (multsint(multsint(multsint(ones)))))"
                },
                {"D0024",
                 "(D0022 + D0023)"
                },
                {"D0025",
                 "divr(divr(D0024))"
                },
                {"D0026",
                 "(PS * D0005)"
                },
                {"D0027",
                 "(BR * D0021)"
                },
                {"D0028",
                 "(BT * D0024)"
                },
                {"D0029",
                 "(D0027 + D0028)"
                },
                {"D0030",
                 "(D0026 * D0029)"
                },
                {"D0031",
                 "(-1 * (D0030))"
                },
                {"D0032",
                 "(D0031 * D0004)"
                },
                {"D0033",
                 "(-1 * (D0001))"
                },
                {"D0034",
                 "(D0032 * exp(D0033))"
                },
                {"D0035",
                 "dr(D0006)"
                },
                {"D0036",
                 "dt(D0006)"
                },
                {"D0037",
                 "(PS * D0005)"
                },
                {"D0038",
                 "(2 * (D0035))"
                },
                {"D0039",
                 "divr(ones)"
                },
                {"D0040",
                 "(D0038 + D0039)"
                },
                {"D0041",
                 "(BR * D0040)"
                },
                {"D0042",
                 "(2 * (D0036))"
                },
                {"D0043",
                 "(BT * D0042)"
                },
                {"D0044",
                 "(divsint(dt(multsint(BT))) - dt(BT))"
                },
                {"D0045",
                 "D0044"
                },
                {"D0046",
                 "(D0043 + D0045)"
                },
                {"D0047",
                 "(D0041 + D0046)"
                },
                {"D0048",
                 "(D0037 * D0047)"
                },
                {"D0049",
                 "(-1 * (D0048))"
                },
                {"D0050",
                 "dr(BR)"
                },
                {"D0051",
                 "dr(BT)"
                },
                {"D0052",
                 "dt(BR)"
                },
                {"D0053",
                 "(-1 * (multr(BT)))"
                },
                {"D0054",
                 "(D0052 + D0053)"
                },
                {"D0055",
                 "dt(BT)"
                },
                {"D0056",
                 "divr(BR)"
                },
                {"D0057",
                 "(D0055 + D0056)"
                },
                {"D0058",
                 "(D0050 + D0057)"
                },
                {"D0059",
                 "(2 * (D0050))"
                },
                {"D0060",
                 "(D0059 - D0058)"
                },
                {"D0061",
                 "divr(divr(D0057))"
                },
                {"D0062",
                 "(2 * (D0061))"
                },
                {"D0063",
                 "divr(divr(D0058))"
                },
                {"D0064",
                 "(D0062 - D0063)"
                },
                {"D0065",
                 "divr(divr(D0054))"
                },
                {"D0066",
                 "(D0051 + D0065)"
                },
                {"D0067",
                 "(PS * D0005)"
                },
                {"D0068",
                 "(D0067 * D0060)"
                },
                {"D0069",
                 "(PS * D0005)"
                },
                {"D0070",
                 "(D0069 * D0064)"
                },
                {"D0071",
                 "(PS * D0005)"
                },
                {"D0072",
                 "(D0071 * D0066)"
                },
                {"D0073",
                 "((1 / 2) * (D0068))"
                },
                {"D0074",
                 "((1 / 2) * (D0070))"
                },
                {"D0075",
                 "((1 / 2) * (D0072))"
                },
                {"D0076",
                 "(D0073 * D0073)"
                },
                {"D0077",
                 "(D0074 * D0074)"
                },
                {"D0078",
                 "D0077"
                },
                {"D0079",
                 "multr(multr(multr(multr(D0078))))"
                },
                {"D0080",
                 "(D0076 + D0079)"
                },
                {"D0081",
                 "(D0075 * D0075)"
                },
                {"D0082",
                 "(2 * (D0081))"
                },
                {"D0083",
                 "multr(multr(D0082))"
                },
                {"D0084",
                 "(D0080 + D0083)"
                },
                {"D0085",
                 "(PS * D0005)"
                },
                {"D0086",
                 "dr(D0049)"
                },
                {"D0087",
                 "(BR * D0086)"
                },
                {"D0088",
                 "dt(D0049)"
                },
                {"D0089",
                 "(BT * D0088)"
                },
                {"D0090",
                 "(D0087 + D0089)"
                },
                {"D0091",
                 "(D0085 * D0090)"
                },
                {"D0092",
                 "(PS * D0005)"
                },
                {"D0093",
                 "dr(D0031)"
                },
                {"D0094",
                 "(BR * D0093)"
                },
                {"D0095",
                 "dt(D0031)"
                },
                {"D0096",
                 "(BT * D0095)"
                },
                {"D0097",
                 "(D0094 + D0096)"
                },
                {"D0098",
                 "(D0092 * D0097)"
                },
                {"D0099",
                 "(D0049 * D0049)"
                },
                {"D0100",
                 "((3 / 2) * (D0099))"
                },
                {"D0101",
                 "(D0084 + D0100)"
                },
                {"D0102",
                 "(PS * PS)"
                },
                {"D0103",
                 "(D0102 * PS)"
                },
                {"D0104",
                 "(D0103 * PS)"
                },
                {"D0105",
                 "(1 / (D0104))"
                },
                {"D0106",
                 "(PS * PS)"
                },
                {"D0107",
                 "(D0106 * exp(D0003))"
                },
                {"D0108",
                 "lap2(D0002)"
                },
                {"D0109",
                 "dr(D0002)"
                },
                {"D0110",
                 "divr(D0109)"
                },
                {"D0111",
                 "dt(D0002)"
                },
                {"D0112",
                 "(divsint(dt(multsint(D0111))) - dt(D0111))"
                },
                {"D0113",
                 "D0112"
                },
                {"D0114",
                 "divr(divr(D0113))"
                },
                {"D0115",
                 "(D0110 + D0114)"
                },
                {"D0116",
                 "(3 * (D0115))"
                },
                {"D0117",
                 "(D0108 - D0116)"
                },
                {"D0118",
                 "(D0021 * D0010)"
                },
                {"D0119",
                 "(D0117 + D0118)"
                },
                {"D0120",
                 "multr(multr(D0025))"
                },
                {"D0121",
                 "(D0120 * D0014)"
                },
                {"D0122",
                 "divr(divr(D0121))"
                },
                {"D0123",
                 "(D0119 + D0122)"
                },
                {"D0124",
                 "(D0031 * D0049)"
                },
                {"D0125",
                 "(4 * (D0124))"
                },
                {"D0126",
                 "(D0125 + D0098)"
                },
                {"D0127",
                 "(D0107 * D0126)"
                },
                {"D0128",
                 "(D0123 + D0127)"
                },
                {"D0129",
                 "dr(D0050)"
                },
                {"D0130",
                 "dt(D0054)"
                },
                {"D0131",
                 "(-1 * (multr(D0050)))"
                },
                {"D0132",
                 "(-1 * D0131)"
                },
                {"D0133",
                 "(-1 * (multr(D0057)))"
                },
                {"D0134",
                 "(D0132 + D0133)"
                },
                {"D0135",
                 "(D0130 + D0134)"
                },
                {"D0136",
                 "divr(divr(D0135))"
                },
                {"D0137",
                 "(D0129 + D0136)"
                },
                {"D0138",
                 "dr(D0051)"
                },
                {"D0139",
                 "divr(D0051)"
                },
                {"D0140",
                 "(D0138 + D0139)"
                },
                {"D0141",
                 "dt(D0057)"
                },
                {"D0142",
                 "divr(D0054)"
                },
                {"D0143",
                 "(-1 * (multr(D0051)))"
                },
                {"D0144",
                 "(D0142 - D0143)"
                },
                {"D0145",
                 "(D0141 + D0144)"
                },
                {"D0146",
                 "divr(divr(D0145))"
                },
                {"D0147",
                 "(D0140 + D0146)"
                },
                {"D0148",
                 "divr(D0060)"
                },
                {"D0149",
                 "multr(multr(D0066))"
                },
                {"D0150",
                 "(divsint(dt(multsint(D0149))) - dt(D0149))"
                },
                {"D0151",
                 "D0150"
                },
                {"D0152",
                 "divr(divr(D0151))"
                },
                {"D0153",
                 "(D0148 + D0152)"
                },
                {"D0154",
                 "(D0137 + D0153)"
                },
                {"D0155",
                 "(D0060 * D0017)"
                },
                {"D0156",
                 "multr(multr(D0066))"
                },
                {"D0157",
                 "(D0156 * D0020)"
                },
                {"D0158",
                 "divr(divr(D0157))"
                },
                {"D0159",
                 "(D0155 + D0158)"
                },
                {"D0160",
                 "(D0154 - D0159)"
                },
                {"D0161",
                 "(PH * D0031)"
                },
                {"D0162",
                 "(D0161 * D0021)"
                },
                {"D0163",
                 "(PS * PS)"
                },
                {"D0164",
                 "(D0163 * PS)"
                },
                {"D0165",
                 "(D0164 * PS)"
                },
                {"D0166",
                 "(D0165 * PS)"
                },
                {"D0167",
                 "(D0166 * PS)"
                },
                {"D0168",
                 "(D0167 * PS)"
                },
                {"D0169",
                 "(1 / (D0168))"
                },
                {"D0170",
                 "(D0162 * D0169)"
                },
                {"D0171",
                 "divsint(divsint(divsint(divsint(divr(divr(divr(divr(D0170))))))))"
                },
                {"D0172",
                 "(D0160 + D0171)"
                },
                {"D0173",
                 "(PH * D0004)"
                },
                {"D0174",
                 "(D0173 * D0049)"
                },
                {"D0175",
                 "D0174"
                },
                {"D0176",
                 "divr(D0175)"
                },
                {"D0177",
                 "(3 * (D0176))"
                },
                {"D0178",
                 "(D0172 + D0177)"
                },
                {"D0179",
                 "D0173"
                },
                {"D0180",
                 "dr(D0049)"
                },
                {"D0181",
                 "(D0179 * D0180)"
                },
                {"D0182",
                 "(D0178 + D0181)"
                },
                {"D0183",
                 "(D0173 * D0049)"
                },
                {"D0184",
                 "D0183"
                },
                {"D0185",
                 "(D0184 * D0035)"
                },
                {"D0186",
                 "(6 * (D0185))"
                },
                {"D0187",
                 "(D0182 + D0186)"
                },
                {"D0188",
                 "divr(D0066)"
                },
                {"D0189",
                 "multr(multr(D0064))"
                },
                {"D0195",
                 "(D0066 * D0017)"
                },
                {"D0196",
                 "multr(multr(D0064))"
                },
                {"D0197",
                 "(D0196 * D0020)"
                },
                {"D0198",
                 "divr(divr(D0197))"
                },
                {"D0199",
                 "(D0195 + D0198)"
                },
                {"D0201",
                 "(PH * D0031)"
                },
                {"D0202",
                 "(D0201 * D0025)"
                },
                {"D0203",
                 "(PS * PS)"
                },
                {"D0204",
                 "(D0203 * PS)"
                },
                {"D0205",
                 "(D0204 * PS)"
                },
                {"D0206",
                 "(D0205 * PS)"
                },
                {"D0207",
                 "(D0206 * PS)"
                },
                {"D0208",
                 "(D0207 * PS)"
                },
                {"D0209",
                 "(1 / (D0208))"
                },
                {"D0210",
                 "(D0202 * D0209)"
                },
                {"D0211",
                 "divsint(divsint(divsint(divsint(divr(divr(divr(divr(D0210))))))))"
                },
                {"D0213",
                 "(PH * D0004)"
                },
                {"D0214",
                 "(D0213 * D0049)"
                },
                {"D0215",
                 "divr(divr(D0214))"
                },
                {"D0220",
                 "divr(divr(D0213))"
                },
                {"D0221",
                 "dt(D0049)"
                },
                {"D0229",
                 "lap(PH)"
                },
                {"D0230",
                 "dr(PH)"
                },
                {"D0231",
                 "divr(D0230)"
                },
                {"D0232",
                 "dt(PH)"
                },
                {"D0233",
                 "(divsint(dt(multsint(D0232))) - dt(D0232))"
                },
                {"D0234",
                 "D0233"
                },
                {"D0235",
                 "divr(divr(D0234))"
                },
                {"D0236",
                 "(D0231 + D0235)"
                },
                {"D0237",
                 "(D0229 + D0236)"
                },
                {"D0238",
                 "(PH * D0107)"
                },
                {"D0239",
                 "(D0101 - D0091)"
                },
                {"D0240",
                 "(D0238 * D0239)"
                },
                {"D0241",
                 "(D0237 - D0240)"
                },
                {"D0242",
                 "(PH * D0034)"
                },
                {"D0243",
                 "(D0242 * D0034)"
                },
                {"D0244",
                 "(D0105 * D0243)"
                },
                {"D0245",
                 "((1 / 4) * (divsint(divsint(divsint(divsint(divr(divr(divr(divr(D0244))))))))))"
                },
                {"D0246",
                 "(D0241 - D0245)"
                },
                {"D0247",
                 "(D0021 * D0021)"
                },
                {"D0248",
                 "(D0024 * D0024)"
                },
                {"D0249",
                 "divr(divr(D0248))"
                },
                {"D0250",
                 "(D0247 + D0249)"
                },
                {"D0251",
                 "lap2(D0001)"
                },
                {"D0252",
                 "(D0035 * D0035)"
                },
                {"D0253",
                 "(D0036 * D0036)"
                },
                {"D0254",
                 "divr(divr(D0253))"
                },
                {"D0255",
                 "(D0252 + D0254)"
                },
                {"D0256",
                 "(4 * (D0255))"
                },
                {"D0257",
                 "(D0251 + D0256)"
                },
                {"D0258",
                 "dr(log(PH))"
                },
                {"D0259",
                 "(D0035 * D0258)"
                },
                {"D0260",
                 "dt(log(PH))"
                },
                {"D0261",
                 "(D0036 * D0260)"
                },
                {"D0262",
                 "divr(divr(D0261))"
                },
                {"D0263",
                 "(D0259 + D0262)"
                },
                {"D0264",
                 "(4 * (D0263))"
                },
                {"D0265",
                 "(D0257 - D0264)"
                },
                {"D0266",
                 "dr(log(PH))"
                },
                {"D0267",
                 "divr(D0266)"
                },
                {"D0268",
                 "dt(log(PH))"
                },
                {"D0269",
                 "(divsint(dt(multsint(D0268))) - dt(D0268))"
                },
                {"D0270",
                 "D0269"
                },
                {"D0271",
                 "divr(divr(D0270))"
                },
                {"D0272",
                 "(D0267 + D0271)"
                },
                {"D0273",
                 "(2 * (D0272))"
                },
                {"D0274",
                 "(D0265 - D0273)"
                },
                {"D0275",
                 "(4 * (D0091))"
                },
                {"D0276",
                 "(D0101 - D0275)"
                },
                {"D0277",
                 "(D0107 * D0276)"
                },
                {"D0278",
                 "((1 / 2) * (D0277))"
                },
                {"D0279",
                 "(D0274 + D0278)"
                },
                {"D0280",
                 "(D0034 * D0034)"
                },
                {"D0281",
                 "(5 * (D0280))"
                },
                {"D0282",
                 "(3 * (D0250))"
                },
                {"D0283",
                 "(D0281 - D0282)"
                },
                {"D0284",
                 "(D0105 * D0283)"
                },
                {"D0285",
                 "((1 / 4) * (divsint(divsint(divsint(divsint(divr(divr(divr(divr(D0284))))))))))"
                },
                {"D0286",
                 "(D0279 + D0285)"
                },
                {"D0287",
                 "lap(D0006)"
                },
                {"D0288",
                 "dr(PH)"
                },
                {"D0289",
                 "(D0035 * D0288)"
                },
                {"D0290",
                 "dt(PH)"
                },
                {"D0291",
                 "(D0036 * D0290)"
                },
                {"D0292",
                 "divr(divr(D0291))"
                },
                {"D0293",
                 "(D0289 + D0292)"
                },
                {"D0294",
                 "(D0293 * D0005)"
                },
                {"D0295",
                 "(D0287 + D0294)"
                },
                {"D0296",
                 "dr(PH)"
                },
                {"D0297",
                 "divr(D0296)"
                },
                {"D0298",
                 "dt(PH)"
                },
                {"D0299",
                 "(divsint(dt(multsint(D0298))) - dt(D0298))"
                },
                {"D0300",
                 "D0299"
                },
                {"D0301",
                 "divr(divr(D0300))"
                },
                {"D0302",
                 "(D0297 + D0301)"
                },
                {"D0303",
                 "(D0302 * D0005)"
                },
                {"D0304",
                 "((1 / 2) * (D0303))"
                },
                {"D0305",
                 "(D0295 + D0304)"
                },
                {"D0306",
                 "(D0107 * D0091)"
                },
                {"D0307",
                 "((1 / 2) * (D0306))"
                },
                {"D0308",
                 "(D0305 + D0307)"
                },
                {"D0309",
                 "(D0034 * D0034)"
                },
                {"D0310",
                 "(D0250 - D0309)"
                },
                {"D0311",
                 "(D0105 * D0310)"
                },
                {"D0312",
                 "((1 / 4) * (divsint(divsint(divsint(divsint(divr(divr(divr(divr(D0311))))))))))"
                },
                {"D0313",
                 "(D0308 + D0312)"
                },
                {"D0314",
                 "multsint(D0147)"
                },
                {"D0315",
                 "multsint(D0188)"
                },
                {"D0316",
                 "multsint(D0189)"
                },
                {"D0317",
                 "dt(D0316)"
                },
                {"D0318",
                 "dt(D0189)"
                },
                {"D0319",
                 "multsint(D0318)"
                },
                {"D0320",
                 "(D0317 - D0319)"
                },
                {"D0321",
                 "divr(D0320)"
                },
                {"D0322",
                 "divr(D0321)"
                },
                {"D0323",
                 "(D0315 + D0322)"
                },
                {"D0324",
                 "(D0314 + D0323)"
                },
                {"D0325",
                 "multsint(D0199)"
                },
                {"D0326",
                 "(D0324 - D0325)"
                },
                {"D0327",
                 "multsint(D0211)"
                },
                {"D0328",
                 "(D0326 + D0327)"
                },
                {"D0329",
                 "multsint(D0215)"
                },
                {"D0330",
                 "dt(D0329)"
                },
                {"D0331",
                 "dt(D0215)"
                },
                {"D0332",
                 "multsint(D0331)"
                },
                {"D0333",
                 "(D0330 - D0332)"
                },
                {"D0334",
                 "(3 * (D0333))"
                },
                {"D0335",
                 "(D0328 + D0334)"
                },
                {"D0336",
                 "multsint(D0221)"
                },
                {"D0337",
                 "(D0220 * D0336)"
                },
                {"D0338",
                 "(D0335 + D0337)"
                },
                {"D0339",
                 "multsint(D0041)"
                },
                {"D0340",
                 "multsint(D0043)"
                },
                {"D0341",
                 "multsint(BT)"
                },
                {"D0342",
                 "dt(D0341)"
                },
                {"D0343",
                 "dt(BT)"
                },
                {"D0344",
                 "multsint(D0343)"
                },
                {"D0345",
                 "(D0342 - D0344)"
                },
                {"D0346",
                 "(D0340 + D0345)"
                },
                {"D0347",
                 "(D0339 + D0346)"
                },
                {"D0348",
                 "(D0037 * D0347)"
                },
                {"D0349",
                 "(-1 * (D0348))"
                },
                {"D0350",
                 "(D0213 * D0349)"
                },
                {"D0351",
                 "divr(D0350)"
                },
                {"D0352",
                 "divr(D0351)"
                },
                {"D0353",
                 "(D0352 * D0036)"
                },
                {"D0354",
                 "(6 * (D0353))"
                },
                {"D0355",
                 "(D0338 + D0354)"
                },
            };
            return D;
        }

        inline const std::vector<FiniteJEq>& equations()
        {
            static const std::vector<FiniteJEq> E = {
                {"EQTW",
                 "D0128"
                },
                {"ESHR",
                 "D0187"
                },
                {"ESHT",
                 "D0355"
                },
                {"EPHI",
                 "D0246"
                },
                {"EQFN",
                 "D0286"
                },
                {"ESIG",
                 "D0313"
                },
            };
            return E;
        }

        inline const std::vector<FiniteJCheck>& checks()
        {
            static const std::vector<FiniteJCheck> C = {
                {"CK0010", "D0010", "D0007 D0009",
                 "(D0007 - D0009)"
                },
                {"CK0014", "D0014", "D0011 D0013",
                 "(D0011 - D0013)"
                },
                {"CK0017", "D0017", "D0010 D0016",
                 "(D0010 - D0016)"
                },
                {"CK0020", "D0020", "D0014 D0019",
                 "(D0014 - D0019)"
                },
                {"CK0024", "D0024", "D0022 D0023",
                 "(D0022 + D0023)"
                },
                {"CK0029", "D0029", "D0027 D0028",
                 "(D0027 + D0028)"
                },
                {"CK0040", "D0040", "D0038 D0039",
                 "(D0038 + D0039)"
                },
                {"CK0044", "D0044", "",
                 "(divsint(dt(multsint(BT))) - dt(BT))"
                },
                {"CK0046", "D0046", "D0043 D0045",
                 "(D0043 + D0045)"
                },
                {"CK0047", "D0047", "D0041 D0046",
                 "(D0041 + D0046)"
                },
                {"CK0054", "D0054", "D0052 D0053",
                 "(D0052 + D0053)"
                },
                {"CK0057", "D0057", "D0055 D0056",
                 "(D0055 + D0056)"
                },
                {"CK0058", "D0058", "D0050 D0057",
                 "(D0050 + D0057)"
                },
                {"CK0060", "D0060", "D0058 D0059",
                 "(D0059 - D0058)"
                },
                {"CK0064", "D0064", "D0062 D0063",
                 "(D0062 - D0063)"
                },
                {"CK0066", "D0066", "D0051 D0065",
                 "(D0051 + D0065)"
                },
                {"CK0080", "D0080", "D0076 D0079",
                 "(D0076 + D0079)"
                },
                {"CK0084", "D0084", "D0080 D0083",
                 "(D0080 + D0083)"
                },
                {"CK0090", "D0090", "D0087 D0089",
                 "(D0087 + D0089)"
                },
                {"CK0097", "D0097", "D0094 D0096",
                 "(D0094 + D0096)"
                },
                {"CK0101", "D0101", "D0084 D0100",
                 "(D0084 + D0100)"
                },
                {"CK0112", "D0112", "D0111",
                 "(divsint(dt(multsint(D0111))) - dt(D0111))"
                },
                {"CK0115", "D0115", "D0110 D0114",
                 "(D0110 + D0114)"
                },
                {"CK0117", "D0117", "D0108 D0116",
                 "(D0108 - D0116)"
                },
                {"CK0119", "D0119", "D0117 D0118",
                 "(D0117 + D0118)"
                },
                {"CK0123", "D0123", "D0119 D0122",
                 "(D0119 + D0122)"
                },
                {"CK0126", "D0126", "D0098 D0125",
                 "(D0125 + D0098)"
                },
                {"CK0128", "D0128", "D0123 D0127",
                 "(D0123 + D0127)"
                },
                {"CK0134", "D0134", "D0132 D0133",
                 "(D0132 + D0133)"
                },
                {"CK0135", "D0135", "D0130 D0134",
                 "(D0130 + D0134)"
                },
                {"CK0137", "D0137", "D0129 D0136",
                 "(D0129 + D0136)"
                },
                {"CK0140", "D0140", "D0138 D0139",
                 "(D0138 + D0139)"
                },
                {"CK0144", "D0144", "D0142 D0143",
                 "(D0142 - D0143)"
                },
                {"CK0145", "D0145", "D0141 D0144",
                 "(D0141 + D0144)"
                },
                {"CK0147", "D0147", "D0140 D0146",
                 "(D0140 + D0146)"
                },
                {"CK0150", "D0150", "D0149",
                 "(divsint(dt(multsint(D0149))) - dt(D0149))"
                },
                {"CK0153", "D0153", "D0148 D0152",
                 "(D0148 + D0152)"
                },
                {"CK0154", "D0154", "D0137 D0153",
                 "(D0137 + D0153)"
                },
                {"CK0159", "D0159", "D0155 D0158",
                 "(D0155 + D0158)"
                },
                {"CK0160", "D0160", "D0154 D0159",
                 "(D0154 - D0159)"
                },
                {"CK0172", "D0172", "D0160 D0171",
                 "(D0160 + D0171)"
                },
                {"CK0178", "D0178", "D0172 D0177",
                 "(D0172 + D0177)"
                },
                {"CK0182", "D0182", "D0178 D0181",
                 "(D0178 + D0181)"
                },
                {"CK0187", "D0187", "D0182 D0186",
                 "(D0182 + D0186)"
                },
                {"CK0199", "D0199", "D0195 D0198",
                 "(D0195 + D0198)"
                },
                {"CK0233", "D0233", "D0232",
                 "(divsint(dt(multsint(D0232))) - dt(D0232))"
                },
                {"CK0236", "D0236", "D0231 D0235",
                 "(D0231 + D0235)"
                },
                {"CK0237", "D0237", "D0229 D0236",
                 "(D0229 + D0236)"
                },
                {"CK0239", "D0239", "D0091 D0101",
                 "(D0101 - D0091)"
                },
                {"CK0241", "D0241", "D0237 D0240",
                 "(D0237 - D0240)"
                },
                {"CK0246", "D0246", "D0241 D0245",
                 "(D0241 - D0245)"
                },
                {"CK0250", "D0250", "D0247 D0249",
                 "(D0247 + D0249)"
                },
                {"CK0255", "D0255", "D0252 D0254",
                 "(D0252 + D0254)"
                },
                {"CK0257", "D0257", "D0251 D0256",
                 "(D0251 + D0256)"
                },
                {"CK0263", "D0263", "D0259 D0262",
                 "(D0259 + D0262)"
                },
                {"CK0265", "D0265", "D0257 D0264",
                 "(D0257 - D0264)"
                },
                {"CK0269", "D0269", "D0268",
                 "(divsint(dt(multsint(D0268))) - dt(D0268))"
                },
                {"CK0272", "D0272", "D0267 D0271",
                 "(D0267 + D0271)"
                },
                {"CK0274", "D0274", "D0265 D0273",
                 "(D0265 - D0273)"
                },
                {"CK0276", "D0276", "D0101 D0275",
                 "(D0101 - D0275)"
                },
                {"CK0279", "D0279", "D0274 D0278",
                 "(D0274 + D0278)"
                },
                {"CK0283", "D0283", "D0281 D0282",
                 "(D0281 - D0282)"
                },
                {"CK0286", "D0286", "D0279 D0285",
                 "(D0279 + D0285)"
                },
                {"CK0293", "D0293", "D0289 D0292",
                 "(D0289 + D0292)"
                },
                {"CK0295", "D0295", "D0287 D0294",
                 "(D0287 + D0294)"
                },
                {"CK0299", "D0299", "D0298",
                 "(divsint(dt(multsint(D0298))) - dt(D0298))"
                },
                {"CK0302", "D0302", "D0297 D0301",
                 "(D0297 + D0301)"
                },
                {"CK0305", "D0305", "D0295 D0304",
                 "(D0295 + D0304)"
                },
                {"CK0308", "D0308", "D0305 D0307",
                 "(D0305 + D0307)"
                },
                {"CK0310", "D0310", "D0250 D0309",
                 "(D0250 - D0309)"
                },
                {"CK0313", "D0313", "D0308 D0312",
                 "(D0308 + D0312)"
                },
                {"CK0320", "D0320", "D0317 D0319",
                 "(D0317 - D0319)"
                },
                {"CK0323", "D0323", "D0315 D0322",
                 "(D0315 + D0322)"
                },
                {"CK0324", "D0324", "D0314 D0323",
                 "(D0314 + D0323)"
                },
                {"CK0326", "D0326", "D0324 D0325",
                 "(D0324 - D0325)"
                },
                {"CK0328", "D0328", "D0326 D0327",
                 "(D0326 + D0327)"
                },
                {"CK0333", "D0333", "D0330 D0332",
                 "(D0330 - D0332)"
                },
                {"CK0335", "D0335", "D0328 D0334",
                 "(D0328 + D0334)"
                },
                {"CK0338", "D0338", "D0335 D0337",
                 "(D0335 + D0337)"
                },
                {"CK0345", "D0345", "D0342 D0344",
                 "(D0342 - D0344)"
                },
                {"CK0346", "D0346", "D0340 D0345",
                 "(D0340 + D0345)"
                },
                {"CK0347", "D0347", "D0339 D0346",
                 "(D0339 + D0346)"
                },
                {"CK0355", "D0355", "D0338 D0354",
                 "(D0338 + D0354)"
                },
            };
            return C;
        }

        /// Read a def into CONFIGURATION space.  Fetching the Val_domain
        /// is not enough -- indexing it is what converts, and a probe that
        /// only fetched returned two false negatives (round 108).
        inline void read_def(Kadath::System_of_eqs& syst,
                             const Kadath::Space& sp, const char* nm,
                             int dmin, int dmax)
        {
            for (int d = dmin; d <= dmax; d++) {
                const Kadath::Val_domain& v =
                    syst.give_val_def_scalar_domain(nm, d);
                Kadath::Index ix(sp.get_domain(d)->get_nbr_points());
                (void)v(ix);
            }
        }
    } // namespace finiteJ_detail

    /// The sub-def names, in dependency order, for reading values back.
    inline const std::vector<const char*>& finiteJ_names()
    {
        static const std::vector<const char*> N = [] {
            std::vector<const char*> v;
            for (const auto& d : finiteJ_detail::subdefs()) v.push_back(d.name);
            return v;
        }();
        return N;
    }

    /// The six equation names.
    inline const std::vector<const char*>& finiteJ_eq_names()
    {
        static const std::vector<const char*> N = [] {
            std::vector<const char*> v;
            for (const auto& e : finiteJ_detail::equations()) v.push_back(e.name);
            return v;
        }();
        return N;
    }

    /// The angular bases this emission was analysed under.  The caller
    /// MUST register the six unknowns in these bases: the basis lattice
    /// that decided every sum ordering assumed them, and if the run
    /// registers something else the analysis describes a different
    /// system.  Names, not integers, so a renumbering in the library
    /// cannot silently reinterpret them.
    inline const std::vector<std::pair<const char*, const char*>>&
    finiteJ_declared_basis()
    {
        static const std::vector<std::pair<const char*, const char*>> B = {
            {"PS", "COS_EVEN"},
            {"PH", "COS_EVEN"},
            {"QF", "COS_EVEN"},
            {"BR", "COS_EVEN"},
            {"BT", "SIN_EVEN"},
            {"QB", "COS_ODD"},
        };
        return B;
    }

    /// Sums reordered by --order-sums, which is seed-specific: see the
    /// header comment.  Empty means the emission was written without it.
    inline const std::vector<const char*>& finiteJ_ordered_sums()
    {
        static const std::vector<const char*> O = {
        };
        return O;
    }

    /// Emission-time AXIS PRECONDITION violations carried into the
    /// artefact: each is a divsint applied where the emitter could not
    /// show the operand vanishes on the axis.  Empty is the only
    /// acceptable state, and since round 342 it is the only reachable
    /// one: the emitter refuses to write a violating emission at all.
    inline const std::vector<const char*>& finiteJ_axis_violations()
    {
        static const std::vector<const char*> V = {
        };
        return V;
    }

    /**
     * Register the emission, keeping the read-state contract.
     *
     * read_defs = false deliberately BREAKS the contract.  It exists so a
     * caller can show finiteJ_check() catches the breach; nothing else
     * should ever pass it.
     */
    inline void finiteJ_register(Kadath::System_of_eqs& syst,
                                 const Kadath::Space& sp, int dmin, int dmax,
                                 bool read_defs = true)
    {
        for (const auto& d : finiteJ_detail::subdefs()) {
            syst.add_def((std::string(d.name) + " = " + d.def).c_str());
            if (read_defs)
                finiteJ_detail::read_def(syst, sp, d.name, dmin, dmax);
        }
        for (const auto& e : finiteJ_detail::equations()) {
            syst.add_def((std::string(e.name) + " = " + e.def).c_str());
            if (read_defs)
                finiteJ_detail::read_def(syst, sp, e.name, dmin, dmax);
        }
    }

    /**
     * THE CONTROL.  Re-register every sum with its operands READ first and
     * compare pointwise with the original.  Returns the worst relative
     * difference and throws above tol.
     *
     * ⚠ Reading the operands before re-parsing is the whole mechanism.  A
     * version that re-registers without reading puts both spellings in the
     * same evaluator state, and two spellings in one state cannot
     * discriminate a defect whose variable IS the state -- which is how
     * round 107 shipped a check weaker than it was reported to be.
     */
    inline double finiteJ_check(Kadath::System_of_eqs& syst,
                                const Kadath::Space& sp, int dmin, int dmax,
                                double tol = 1e-12)
    {
        double worst = 0.0;
        std::string worst_name;
        for (const auto& c : finiteJ_detail::checks()) {
            std::istringstream is(c.reads);
            for (std::string nm; is >> nm;)
                finiteJ_detail::read_def(syst, sp, nm.c_str(), dmin, dmax);
            syst.add_def((std::string(c.name) + " = " + c.def).c_str());
            double mx = 0.0, scale = 0.0;
            for (int d = dmin; d <= dmax; d++) {
                const Kadath::Val_domain& a =
                    syst.give_val_def_scalar_domain(c.of, d);
                const Kadath::Val_domain& b =
                    syst.give_val_def_scalar_domain(c.name, d);
                Kadath::Index ix(sp.get_domain(d)->get_nbr_points());
                do {
                    mx = std::max(mx, std::fabs(a(ix) - b(ix)));
                    scale = std::max(scale, std::fabs(a(ix)));
                } while (ix.inc());
            }
            const double rel = mx / std::max(scale, 1e-300);
            if (rel > worst) { worst = rel; worst_name = c.of; }
        }
        if (worst > tol)
            throw std::runtime_error(
                "finiteJ read-state contract broken: " + worst_name
                + " differs from its own re-expression by "
                + std::to_string(worst)
                + " -- the defs were registered without being read");
        return worst;
    }

} // namespace Trumpet
