/*
 * throatth_eqs.hpp -- GENERATED by scripts/throat_emit.py.  Do not edit.
 *
 * The grade-1 throat rows as theta-ODEs at the inner face: the INNER
 * BOUNDARY CONDITION of the matched formulation (research round 504),
 * 6nt - 3 conditions on the 6nt - 3 grade-0 and 6nt - 3 grade-1
 * matching amplitudes.
 *
 * Every monomial was checked as an IDENTITY against its sympy original by
 * reading the emitted string back through the inverse vocabulary, and the
 * emission was refused by the axis lattice until E_sh^theta carried its
 * sin(theta) weight distributed over the monomials and Qbar was declared
 * at sin-order 4 (research round 511 ruling 3: Qb == multsint^4(QB)).
 */
#pragma once

#include <cstdio>
#include <cstdlib>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include "For_Kadath/Array/headcpp.hpp"
#include "For_Kadath/Space/space.hpp"
#include "For_Kadath/System_of_eqs/system_of_eqs.hpp"

namespace Trumpet
{
    struct ThDef { const char* name; const char* def; };

    namespace throatth_detail
    {
        inline const std::vector<ThDef>& subdefs()
        {
            static const std::vector<ThDef> D = {
                {"ZA0000", "dt(QBH)"},
                {"ZA0001", "dt(UH)"},
                {"ZA0002", "(ZA0000 * ZA0001)"},
                {"ZA0003", "(8 * (ZA0002))"},
                {"ZA0004", "(-1 * (ZA0003))"},
                {"ZA0005", "(1 / (PHH))"},
                {"ZA0006", "dt(PHH)"},
                {"ZA0007", "(ZA0005 * ZA0006)"},
                {"ZA0008", "(ZA0007 * ZA0000)"},
                {"ZA0009", "(JJ * ZA0001)"},
                {"ZA0010", "multsint(ZA0009)"},
                {"ZA0011", "multsint(ZA0010)"},
                {"ZA0012", "multsint(ZA0011)"},
                {"ZA0013", "(48 * (ZA0012))"},
                {"ZA0014", "(-1 * (ZA0013))"},
                {"ZA0015", "(divsint(dt(multsint(ZA0000))) - dt(ZA0000))"},
                {"ZA0016", "(3 * (ZA0015))"},
                {"ZA0017", "(-1 * (ZA0016))"},
                {"ZA0018", "(JJ * ZA0007)"},
                {"ZA0019", "multsint(ZA0018)"},
                {"ZA0020", "multsint(ZA0019)"},
                {"ZA0021", "multsint(ZA0020)"},
                {"ZA0022", "(6 * (ZA0021))"},
                {"ZA0023", "(BTH * BTH)"},
                {"ZA0024", "(ZA0005 * ZA0005)"},
                {"ZA0025", "(ZA0023 * ZA0024)"},
                {"ZA0026", "dt(ZA0000)"},
                {"ZA0027", "(ZA0025 * ZA0026)"},
                {"ZA0028", "(2 * (QH))"},
                {"ZA0029", "exp(ZA0028)"},
                {"ZA0030", "(ZA0027 * ZA0029)"},
                {"ZA0031", "(8 * (UH))"},
                {"ZA0032", "exp(ZA0031)"},
                {"ZA0033", "(ZA0030 * ZA0032)"},
                {"ZA0034", "(-1 * (ZA0033))"},
                {"ZA0035", "(ZA0024 * ZA0005)"},
                {"ZA0036", "(ZA0023 * ZA0035)"},
                {"ZA0037", "(ZA0036 * ZA0006)"},
                {"ZA0038", "(ZA0037 * ZA0000)"},
                {"ZA0039", "(ZA0038 * ZA0029)"},
                {"ZA0040", "(ZA0039 * ZA0032)"},
                {"ZA0041", "dt(BTH)"},
                {"ZA0042", "(ZA0024 * ZA0041)"},
                {"ZA0043", "(ZA0042 * ZA0000)"},
                {"ZA0044", "(ZA0043 * BTH)"},
                {"ZA0045", "(ZA0044 * ZA0029)"},
                {"ZA0046", "(ZA0045 * ZA0032)"},
                {"ZA0047", "(-1 * (ZA0046))"},
                {"ZA0048", "(ZA0025 * ZA0000)"},
                {"ZA0049", "(ZA0048 * ZA0001)"},
                {"ZA0050", "(ZA0049 * ZA0029)"},
                {"ZA0051", "(ZA0050 * ZA0032)"},
                {"ZA0052", "(6 * (ZA0051))"},
                {"ZA0053", "(BH * BH)"},
                {"ZA0054", "(ZA0024 * ZA0053)"},
                {"ZA0055", "(ZA0054 * P1)"},
                {"ZA0056", "(ZA0055 * QB1)"},
                {"ZA0057", "(ZA0056 * ZA0029)"},
                {"ZA0058", "(ZA0057 * ZA0032)"},
                {"ZA0059", "((nexp * nexp) * ZA0058)"},
                {"ZA0060", "(ZA0024 * ZA0000)"},
                {"ZA0061", "(ZA0060 * B2)"},
                {"ZA0062", "(ZA0061 * BH)"},
                {"ZA0063", "(ZA0062 * ZA0029)"},
                {"ZA0064", "(ZA0063 * ZA0032)"},
                {"ZA0065", "(nexp * ZA0064)"},
                {"ZA0066", "(-1 * (ZA0065))"},
                {"ZA0067", "dt(BH)"},
                {"ZA0068", "(ZA0024 * ZA0067)"},
                {"ZA0069", "(ZA0068 * BTH)"},
                {"ZA0070", "(ZA0069 * QB1)"},
                {"ZA0071", "(ZA0070 * ZA0029)"},
                {"ZA0072", "(ZA0071 * ZA0032)"},
                {"ZA0073", "(nexp * ZA0072)"},
                {"ZA0074", "(-1 * (ZA0073))"},
                {"ZA0075", "(ZA0054 * QB1)"},
                {"ZA0076", "(ZA0075 * B1)"},
                {"ZA0077", "(ZA0076 * ZA0029)"},
                {"ZA0078", "(ZA0077 * ZA0032)"},
                {"ZA0079", "((nexp * nexp) * ZA0078)"},
                {"ZA0080", "(-1 * (ZA0079))"},
                {"ZA0081", "(ZA0042 * BTH)"},
                {"ZA0082", "(ZA0081 * ZA0029)"},
                {"ZA0083", "(ZA0082 * ZA0032)"},
                {"ZA0084", "(JJ * ZA0083)"},
                {"ZA0085", "multsint(ZA0084)"},
                {"ZA0086", "multsint(ZA0085)"},
                {"ZA0087", "multsint(ZA0086)"},
                {"ZA0088", "(6 * (ZA0087))"},
                {"ZA0089", "(-1 * (ZA0088))"},
                {"ZA0090", "dt(QB1)"},
                {"ZA0091", "(ZA0024 * ZA0090)"},
                {"ZA0092", "(ZA0091 * BTH)"},
                {"ZA0093", "(ZA0092 * BH)"},
                {"ZA0094", "(ZA0093 * ZA0029)"},
                {"ZA0095", "(ZA0094 * ZA0032)"},
                {"ZA0096", "(nexp * ZA0095)"},
                {"ZA0097", "(2 * (ZA0096))"},
                {"ZA0098", "(-1 * (ZA0097))"},
                {"ZA0099", "(ZA0048 * ZA0029)"},
                {"ZA0100", "(ZA0099 * ZA0032)"},
                {"ZA0101", "(divsint(dt(multsint(ZA0100))) - dt(ZA0100))"},
                {"ZA0102", "(4 * (ZA0101))"},
                {"ZA0103", "(ZA0037 * ZA0029)"},
                {"ZA0104", "(ZA0103 * ZA0032)"},
                {"ZA0105", "(JJ * ZA0104)"},
                {"ZA0106", "multsint(ZA0105)"},
                {"ZA0107", "multsint(ZA0106)"},
                {"ZA0108", "multsint(ZA0107)"},
                {"ZA0109", "(6 * (ZA0108))"},
                {"ZA0110", "(ZA0025 * ZA0029)"},
                {"ZA0111", "(ZA0110 * ZA0032)"},
                {"ZA0112", "(JJ * ZA0111)"},
                {"ZA0113", "(dt(multsint(ZA0112)) - multsint(dt(ZA0112)))"},
                {"ZA0114", "multsint(ZA0113)"},
                {"ZA0115", "multsint(ZA0114)"},
                {"ZA0116", "(6 * (ZA0115))"},
                {"ZA0117", "(ZA0075 * ZA0029)"},
                {"ZA0118", "(ZA0117 * ZA0032)"},
                {"ZA0119", "(ZA0118 * U1)"},
                {"ZA0120", "((nexp * nexp) * ZA0119)"},
                {"ZA0121", "(6 * (ZA0120))"},
                {"ZA0122", "(ZA0025 * ZA0001)"},
                {"ZA0123", "(ZA0122 * ZA0029)"},
                {"ZA0124", "(ZA0123 * ZA0032)"},
                {"ZA0125", "(JJ * ZA0124)"},
                {"ZA0126", "multsint(ZA0125)"},
                {"ZA0127", "multsint(ZA0126)"},
                {"ZA0128", "multsint(ZA0127)"},
                {"ZA0129", "(36 * (ZA0128))"},
                {"ZA0130", "(ZA0035 * ZA0006)"},
                {"ZA0131", "(ZA0130 * BTH)"},
                {"ZA0132", "(ZA0131 * QB1)"},
                {"ZA0133", "(ZA0132 * BH)"},
                {"ZA0134", "(ZA0133 * ZA0029)"},
                {"ZA0135", "(ZA0134 * ZA0032)"},
                {"ZA0136", "(nexp * ZA0135)"},
                {"ZA0137", "(ZA0060 * BTH)"},
                {"ZA0138", "(ZA0137 * P1)"},
                {"ZA0139", "(ZA0138 * BH)"},
                {"ZA0140", "(ZA0139 * ZA0029)"},
                {"ZA0141", "(ZA0140 * ZA0032)"},
                {"ZA0142", "(nexp * ZA0141)"},
                {"ZA0143", "(ZA0024 * B2)"},
                {"ZA0144", "(ZA0143 * BH)"},
                {"ZA0145", "(ZA0144 * ZA0029)"},
                {"ZA0146", "(ZA0145 * ZA0032)"},
                {"ZA0147", "(JJ * ZA0146)"},
                {"ZA0148", "(nexp * ZA0147)"},
                {"ZA0149", "multsint(ZA0148)"},
                {"ZA0150", "multsint(ZA0149)"},
                {"ZA0151", "multsint(ZA0150)"},
                {"ZA0152", "(6 * (ZA0151))"},
                {"ZA0153", "(-1 * (ZA0152))"},
                {"ZA0154", "(ZA0137 * BH)"},
                {"ZA0155", "(ZA0154 * ZA0029)"},
                {"ZA0156", "(ZA0155 * ZA0032)"},
                {"ZA0157", "(ZA0156 * U1)"},
                {"ZA0158", "(nexp * ZA0157)"},
                {"ZA0159", "(6 * (ZA0158))"},
                {"ZA0160", "(ZA0024 * ZA0001)"},
                {"ZA0161", "(ZA0160 * BTH)"},
                {"ZA0162", "(ZA0161 * QB1)"},
                {"ZA0163", "(ZA0162 * BH)"},
                {"ZA0164", "(ZA0163 * ZA0029)"},
                {"ZA0165", "(ZA0164 * ZA0032)"},
                {"ZA0166", "(nexp * ZA0165)"},
                {"ZA0167", "(6 * (ZA0166))"},
                {"ZA0168", "(ZA0024 * BTH)"},
                {"ZA0169", "(ZA0168 * QB1)"},
                {"ZA0170", "(ZA0169 * BH)"},
                {"ZA0171", "(ZA0170 * ZA0029)"},
                {"ZA0172", "(ZA0171 * ZA0032)"},
                {"ZA0173", "(nexp * ZA0172)"},
                {"ZA0174", "(divsint(dt(multsint(ZA0173))) - dt(ZA0173))"},
                {"ZA0175", "(4 * (ZA0174))"},
                {"ZA0176", "(ZA0168 * P1)"},
                {"ZA0177", "(ZA0176 * BH)"},
                {"ZA0178", "(ZA0177 * ZA0029)"},
                {"ZA0179", "(ZA0178 * ZA0032)"},
                {"ZA0180", "(JJ * ZA0179)"},
                {"ZA0181", "(nexp * ZA0180)"},
                {"ZA0182", "multsint(ZA0181)"},
                {"ZA0183", "multsint(ZA0182)"},
                {"ZA0184", "multsint(ZA0183)"},
                {"ZA0185", "(6 * (ZA0184))"},
                {"ZA0186", "(ZA0168 * BH)"},
                {"ZA0187", "(ZA0186 * ZA0029)"},
                {"ZA0188", "(ZA0187 * ZA0032)"},
                {"ZA0189", "(ZA0188 * U1)"},
                {"ZA0190", "(JJ * ZA0189)"},
                {"ZA0191", "(nexp * ZA0190)"},
                {"ZA0192", "multsint(ZA0191)"},
                {"ZA0193", "multsint(ZA0192)"},
                {"ZA0194", "multsint(ZA0193)"},
                {"ZA0195", "(36 * (ZA0194))"},
                {"ZA0196", "(ZA0004 + ZA0008)"},
                {"ZA0197", "(ZA0196 + ZA0014)"},
                {"ZA0198", "(ZA0197 + ZA0017)"},
                {"ZA0199", "(ZA0198 + ZA0022)"},
                {"ZA0200", "(ZA0199 + ZA0034)"},
                {"ZA0201", "(ZA0200 + ZA0040)"},
                {"ZA0202", "(ZA0201 + ZA0047)"},
                {"ZA0203", "(ZA0202 + ZA0052)"},
                {"ZA0204", "(ZA0203 + ZA0059)"},
                {"ZA0205", "(ZA0204 + ZA0066)"},
                {"ZA0206", "(ZA0205 + ZA0074)"},
                {"ZA0207", "(ZA0206 + ZA0080)"},
                {"ZA0208", "(ZA0207 + ZA0089)"},
                {"ZA0209", "(ZA0208 + ZA0098)"},
                {"ZA0210", "(ZA0209 + ZA0102)"},
                {"ZA0211", "(ZA0210 + ZA0109)"},
                {"ZA0212", "(ZA0211 + ZA0116)"},
                {"ZA0213", "(ZA0212 + ZA0121)"},
                {"ZA0214", "(ZA0213 + ZA0129)"},
                {"ZA0215", "(ZA0214 + ZA0136)"},
                {"ZA0216", "(ZA0215 + ZA0142)"},
                {"ZA0217", "(ZA0216 + ZA0153)"},
                {"ZA0218", "(ZA0217 + ZA0159)"},
                {"ZA0219", "(ZA0218 + ZA0167)"},
                {"ZA0220", "(ZA0219 + ZA0175)"},
                {"ZA0221", "(ZA0220 + ZA0185)"},
                {"ZA0222", "(ZA0221 + ZA0195)"},
                {"ZA0223", "(ZA0222 + ZA0026)"},
                {"ZA0224", "(nexp * ZA0041)"},
                {"ZA0225", "dt(B1)"},
                {"ZA0226", "dt(ZA0225)"},
                {"ZA0227", "(ZA0226 * BH)"},
                {"ZA0228", "dt(ZA0067)"},
                {"ZA0229", "(ZA0228 * B1)"},
                {"ZA0230", "dt(P1)"},
                {"ZA0231", "(ZA0230 * ZA0067)"},
                {"ZA0232", "(-1 * (ZA0231))"},
                {"ZA0233", "(ZA0001 * BTH)"},
                {"ZA0234", "(8 * (ZA0233))"},
                {"ZA0235", "(-1 * (ZA0234))"},
                {"ZA0236", "dt(QH)"},
                {"ZA0237", "(ZA0236 * BTH)"},
                {"ZA0238", "(2 * (ZA0237))"},
                {"ZA0239", "(-1 * (ZA0238))"},
                {"ZA0240", "(ZA0225 * ZA0067)"},
                {"ZA0241", "(2 * (ZA0240))"},
                {"ZA0242", "dt(Q1F)"},
                {"ZA0243", "(ZA0067 * ZA0242)"},
                {"ZA0244", "(2 * (ZA0243))"},
                {"ZA0245", "dt(U1)"},
                {"ZA0246", "(ZA0067 * ZA0245)"},
                {"ZA0247", "(8 * (ZA0246))"},
                {"ZA0248", "(ZA0007 * BTH)"},
                {"ZA0249", "(divsint(dt(multsint(BTH))) - dt(BTH))"},
                {"ZA0250", "(-1 * (ZA0249))"},
                {"ZA0251", "(nexp * ZA0237)"},
                {"ZA0252", "(2 * (ZA0251))"},
                {"ZA0253", "(ZA0225 * ZA0236)"},
                {"ZA0254", "(ZA0253 * BH)"},
                {"ZA0255", "(2 * (ZA0254))"},
                {"ZA0256", "(ZA0067 * ZA0236)"},
                {"ZA0257", "(ZA0256 * B1)"},
                {"ZA0258", "(2 * (ZA0257))"},
                {"ZA0259", "(nexp * ZA0233)"},
                {"ZA0260", "(8 * (ZA0259))"},
                {"ZA0261", "(ZA0225 * ZA0001)"},
                {"ZA0262", "(ZA0261 * BH)"},
                {"ZA0263", "(8 * (ZA0262))"},
                {"ZA0264", "(ZA0067 * ZA0001)"},
                {"ZA0265", "(ZA0264 * B1)"},
                {"ZA0266", "(8 * (ZA0265))"},
                {"ZA0267", "(nexp * BTH)"},
                {"ZA0268", "(divsint(dt(multsint(ZA0267))) - dt(ZA0267))"},
                {"ZA0269", "(ZA0225 * BH)"},
                {"ZA0270", "(divsint(dt(multsint(ZA0269))) - dt(ZA0269))"},
                {"ZA0271", "(ZA0067 * B1)"},
                {"ZA0272", "(divsint(dt(multsint(ZA0271))) - dt(ZA0271))"},
                {"ZA0273", "(nexp * ZA0248)"},
                {"ZA0274", "(-1 * (ZA0273))"},
                {"ZA0275", "(ZA0007 * ZA0225)"},
                {"ZA0276", "(ZA0275 * BH)"},
                {"ZA0277", "(-1 * (ZA0276))"},
                {"ZA0278", "(ZA0007 * ZA0067)"},
                {"ZA0279", "(ZA0278 * B1)"},
                {"ZA0280", "(-1 * (ZA0279))"},
                {"ZA0281", "(ZA0224 + ZA0227)"},
                {"ZA0282", "(ZA0281 + ZA0229)"},
                {"ZA0283", "(ZA0282 + ZA0232)"},
                {"ZA0284", "(ZA0283 + ZA0235)"},
                {"ZA0285", "(ZA0284 + ZA0239)"},
                {"ZA0286", "(ZA0285 + ZA0241)"},
                {"ZA0287", "(ZA0286 + ZA0244)"},
                {"ZA0288", "(ZA0287 + ZA0247)"},
                {"ZA0289", "(ZA0288 + ZA0248)"},
                {"ZA0290", "(ZA0289 + ZA0250)"},
                {"ZA0291", "(ZA0290 + ZA0252)"},
                {"ZA0292", "(ZA0291 + ZA0255)"},
                {"ZA0293", "(ZA0292 + ZA0258)"},
                {"ZA0294", "(ZA0293 + ZA0260)"},
                {"ZA0295", "(ZA0294 + ZA0263)"},
                {"ZA0296", "(ZA0295 + ZA0266)"},
                {"ZA0297", "(ZA0296 + ZA0268)"},
                {"ZA0298", "(ZA0297 + ZA0270)"},
                {"ZA0299", "(ZA0298 + ZA0272)"},
                {"ZA0300", "(ZA0299 + ZA0274)"},
                {"ZA0301", "(ZA0300 + ZA0277)"},
                {"ZA0302", "(ZA0301 + ZA0280)"},
                {"ZA0303", "multsint(BTH)"},
                {"ZA0304", "multsint(ZA0303)"},
                {"ZA0305", "(2 * (ZA0304))"},
                {"ZA0306", "(ZA0001 * ZA0001)"},
                {"ZA0307", "(ZA0306 * BTH)"},
                {"ZA0308", "multsint(ZA0307)"},
                {"ZA0309", "multsint(ZA0308)"},
                {"ZA0310", "(16 * (ZA0309))"},
                {"ZA0311", "(-1 * (ZA0310))"},
                {"ZA0312", "dt(ZA0001)"},
                {"ZA0313", "(ZA0312 * BTH)"},
                {"ZA0314", "multsint(ZA0313)"},
                {"ZA0315", "multsint(ZA0314)"},
                {"ZA0316", "(2 * (ZA0315))"},
                {"ZA0317", "(-1 * (ZA0316))"},
                {"ZA0318", "(ZA0041 * ZA0236)"},
                {"ZA0319", "multsint(ZA0318)"},
                {"ZA0320", "multsint(ZA0319)"},
                {"ZA0321", "(2 * (ZA0320))"},
                {"ZA0322", "(ZA0041 * ZA0001)"},
                {"ZA0323", "multsint(ZA0322)"},
                {"ZA0324", "multsint(ZA0323)"},
                {"ZA0325", "(6 * (ZA0324))"},
                {"ZA0326", "(nexp * ZA0269)"},
                {"ZA0327", "multsint(ZA0326)"},
                {"ZA0328", "multsint(ZA0327)"},
                {"ZA0329", "(-1 * (ZA0328))"},
                {"ZA0330", "(ZA0067 * P1)"},
                {"ZA0331", "(nexp * ZA0330)"},
                {"ZA0332", "multsint(ZA0331)"},
                {"ZA0333", "multsint(ZA0332)"},
                {"ZA0334", "(-1 * (ZA0333))"},
                {"ZA0335", "(nexp * ZA0271)"},
                {"ZA0336", "multsint(ZA0335)"},
                {"ZA0337", "multsint(ZA0336)"},
                {"ZA0338", "(-1 * (ZA0337))"},
                {"ZA0339", "(ZA0005 * ZA0041)"},
                {"ZA0340", "(ZA0339 * ZA0006)"},
                {"ZA0341", "multsint(ZA0340)"},
                {"ZA0342", "multsint(ZA0341)"},
                {"ZA0343", "(-1 * (ZA0342))"},
                {"ZA0344", "(ZA0245 * BH)"},
                {"ZA0345", "(nexp * ZA0344)"},
                {"ZA0346", "multsint(ZA0345)"},
                {"ZA0347", "multsint(ZA0346)"},
                {"ZA0348", "(2 * (ZA0347))"},
                {"ZA0349", "(-1 * (ZA0348))"},
                {"ZA0350", "(dt(multsint(BTH)) - multsint(dt(BTH)))"},
                {"ZA0351", "(dt(multsint(ZA0350)) - multsint(dt(ZA0350)))"},
                {"ZA0352", "(2 * (ZA0351))"},
                {"ZA0353", "(-1 * (ZA0352))"},
                {"ZA0354", "(ZA0067 * Q1F)"},
                {"ZA0355", "(nexp * ZA0354)"},
                {"ZA0356", "multsint(ZA0355)"},
                {"ZA0357", "multsint(ZA0356)"},
                {"ZA0358", "(2 * (ZA0357))"},
                {"ZA0359", "(ZA0067 * U1)"},
                {"ZA0360", "(nexp * ZA0359)"},
                {"ZA0361", "multsint(ZA0360)"},
                {"ZA0362", "multsint(ZA0361)"},
                {"ZA0363", "(6 * (ZA0362))"},
                {"ZA0364", "(ZA0001 * BH)"},
                {"ZA0365", "(ZA0364 * U1)"},
                {"ZA0366", "(nexp * ZA0365)"},
                {"ZA0367", "multsint(ZA0366)"},
                {"ZA0368", "multsint(ZA0367)"},
                {"ZA0369", "(16 * (ZA0368))"},
                {"ZA0370", "(-1 * (ZA0369))"},
                {"ZA0371", "(dt(multsint(ZA0233)) - multsint(dt(ZA0233)))"},
                {"ZA0372", "multsint(ZA0371)"},
                {"ZA0373", "(14 * (ZA0372))"},
                {"ZA0374", "(-1 * (ZA0373))"},
                {"ZA0375", "(ZA0001 * B1)"},
                {"ZA0376", "(ZA0375 * BH)"},
                {"ZA0377", "(nexp * ZA0376)"},
                {"ZA0378", "multsint(ZA0377)"},
                {"ZA0379", "multsint(ZA0378)"},
                {"ZA0380", "(8 * (ZA0379))"},
                {"ZA0381", "(-1 * (ZA0380))"},
                {"ZA0382", "(ZA0236 * B1)"},
                {"ZA0383", "(ZA0382 * BH)"},
                {"ZA0384", "(nexp * ZA0383)"},
                {"ZA0385", "multsint(ZA0384)"},
                {"ZA0386", "multsint(ZA0385)"},
                {"ZA0387", "(2 * (ZA0386))"},
                {"ZA0388", "(-1 * (ZA0387))"},
                {"ZA0389", "(ZA0007 * ZA0001)"},
                {"ZA0390", "(ZA0389 * BTH)"},
                {"ZA0391", "multsint(ZA0390)"},
                {"ZA0392", "multsint(ZA0391)"},
                {"ZA0393", "(2 * (ZA0392))"},
                {"ZA0394", "(ZA0007 * B1)"},
                {"ZA0395", "(ZA0394 * BH)"},
                {"ZA0396", "(nexp * ZA0395)"},
                {"ZA0397", "multsint(ZA0396)"},
                {"ZA0398", "multsint(ZA0397)"},
                {"ZA0399", "(dt(multsint(ZA0248)) - multsint(dt(ZA0248)))"},
                {"ZA0400", "multsint(ZA0399)"},
                {"ZA0401", "(B1 * BH)"},
                {"ZA0402", "(nexp * ZA0401)"},
                {"ZA0403", "(dt(multsint(ZA0402)) - multsint(dt(ZA0402)))"},
                {"ZA0404", "multsint(ZA0403)"},
                {"ZA0405", "(-1 * (ZA0404))"},
                {"ZA0406", "(BH * U1)"},
                {"ZA0407", "(nexp * ZA0406)"},
                {"ZA0408", "(dt(multsint(ZA0407)) - multsint(dt(ZA0407)))"},
                {"ZA0409", "multsint(ZA0408)"},
                {"ZA0410", "(6 * (ZA0409))"},
                {"ZA0411", "(-1 * (ZA0410))"},
                {"ZA0412", "(ZA0007 * BH)"},
                {"ZA0413", "(ZA0412 * U1)"},
                {"ZA0414", "(nexp * ZA0413)"},
                {"ZA0415", "multsint(ZA0414)"},
                {"ZA0416", "multsint(ZA0415)"},
                {"ZA0417", "(2 * (ZA0416))"},
                {"ZA0418", "dt(ZA0041)"},
                {"ZA0419", "multsint(ZA0418)"},
                {"ZA0420", "multsint(ZA0419)"},
                {"ZA0421", "(ZA0305 + ZA0311)"},
                {"ZA0422", "(ZA0421 + ZA0317)"},
                {"ZA0423", "(ZA0422 + ZA0321)"},
                {"ZA0424", "(ZA0423 + ZA0325)"},
                {"ZA0425", "(ZA0424 + ZA0329)"},
                {"ZA0426", "(ZA0425 + ZA0334)"},
                {"ZA0427", "(ZA0426 + ZA0338)"},
                {"ZA0428", "(ZA0427 + ZA0343)"},
                {"ZA0429", "(ZA0428 + ZA0349)"},
                {"ZA0430", "(ZA0429 + ZA0353)"},
                {"ZA0431", "(ZA0430 + ZA0358)"},
                {"ZA0432", "(ZA0431 + ZA0363)"},
                {"ZA0433", "(ZA0432 + ZA0370)"},
                {"ZA0434", "(ZA0433 + ZA0374)"},
                {"ZA0435", "(ZA0434 + ZA0381)"},
                {"ZA0436", "(ZA0435 + ZA0388)"},
                {"ZA0437", "(ZA0436 + ZA0393)"},
                {"ZA0438", "(ZA0437 + ZA0398)"},
                {"ZA0439", "(ZA0438 + ZA0400)"},
                {"ZA0440", "(ZA0439 + ZA0405)"},
                {"ZA0441", "(ZA0440 + ZA0411)"},
                {"ZA0442", "(ZA0441 + ZA0417)"},
                {"ZA0443", "(ZA0442 + ZA0420)"},
                {"ZA0444", "(ZA0005 * ZA0067)"},
                {"ZA0445", "(ZA0444 * BTH)"},
                {"ZA0446", "(ZA0445 * ZA0029)"},
                {"ZA0447", "(ZA0446 * ZA0032)"},
                {"ZA0448", "(ZA0067 * ZA0067)"},
                {"ZA0449", "(ZA0448 * ZA0005)"},
                {"ZA0450", "(ZA0449 * P1)"},
                {"ZA0451", "(ZA0450 * ZA0029)"},
                {"ZA0452", "(ZA0451 * ZA0032)"},
                {"ZA0453", "((1 / 2) * (ZA0452))"},
                {"ZA0454", "(ZA0449 * B1)"},
                {"ZA0455", "(ZA0454 * ZA0029)"},
                {"ZA0456", "(ZA0455 * ZA0032)"},
                {"ZA0457", "(-1 * (ZA0456))"},
                {"ZA0458", "(ZA0449 * ZA0029)"},
                {"ZA0459", "(ZA0458 * ZA0032)"},
                {"ZA0460", "(ZA0459 * Q1F)"},
                {"ZA0461", "(-1 * (ZA0460))"},
                {"ZA0462", "(ZA0459 * U1)"},
                {"ZA0463", "(4 * (ZA0462))"},
                {"ZA0464", "(-1 * (ZA0463))"},
                {"ZA0465", "(nexp * ZA0447)"},
                {"ZA0466", "(-1 * (ZA0465))"},
                {"ZA0467", "(ZA0005 * ZA0225)"},
                {"ZA0468", "(ZA0467 * ZA0067)"},
                {"ZA0469", "(ZA0468 * BH)"},
                {"ZA0470", "(ZA0469 * ZA0029)"},
                {"ZA0471", "(ZA0470 * ZA0032)"},
                {"ZA0472", "(-1 * (ZA0471))"},
                {"ZA0473", "(ZA0447 + ZA0453)"},
                {"ZA0474", "(ZA0473 + ZA0457)"},
                {"ZA0475", "(ZA0474 + ZA0461)"},
                {"ZA0476", "(ZA0475 + ZA0464)"},
                {"ZA0477", "(ZA0476 + ZA0466)"},
                {"ZA0478", "(ZA0477 + ZA0472)"},
                {"ZA0479", "(ZA0448 * ZA0024)"},
                {"ZA0480", "(ZA0479 * B1)"},
                {"ZA0481", "(ZA0480 * ZA0029)"},
                {"ZA0482", "(ZA0481 * ZA0032)"},
                {"ZA0483", "((1 / 2) * (ZA0482))"},
                {"ZA0484", "(ZA0479 * ZA0029)"},
                {"ZA0485", "(ZA0484 * ZA0032)"},
                {"ZA0486", "(ZA0485 * Q1F)"},
                {"ZA0487", "((1 / 2) * (ZA0486))"},
                {"ZA0488", "(ZA0485 * U1)"},
                {"ZA0489", "(2 * (ZA0488))"},
                {"ZA0490", "(ZA0479 * P1)"},
                {"ZA0491", "(ZA0490 * ZA0029)"},
                {"ZA0492", "(ZA0491 * ZA0032)"},
                {"ZA0493", "((1 / 2) * (ZA0492))"},
                {"ZA0494", "(-1 * (ZA0493))"},
                {"ZA0495", "(ZA0069 * ZA0029)"},
                {"ZA0496", "(ZA0495 * ZA0032)"},
                {"ZA0497", "((1 / 2) * (ZA0496))"},
                {"ZA0498", "(-1 * (ZA0497))"},
                {"ZA0499", "(nexp * ZA0496)"},
                {"ZA0500", "((1 / 2) * (ZA0499))"},
                {"ZA0501", "(ZA0024 * ZA0225)"},
                {"ZA0502", "(ZA0501 * ZA0067)"},
                {"ZA0503", "(ZA0502 * BH)"},
                {"ZA0504", "(ZA0503 * ZA0029)"},
                {"ZA0505", "(ZA0504 * ZA0032)"},
                {"ZA0506", "((1 / 2) * (ZA0505))"},
                {"ZA0507", "(ZA0483 + ZA0487)"},
                {"ZA0508", "(ZA0507 + ZA0489)"},
                {"ZA0509", "(ZA0508 + ZA0494)"},
                {"ZA0510", "(ZA0509 + ZA0498)"},
                {"ZA0511", "(ZA0510 + ZA0500)"},
                {"ZA0512", "(ZA0511 + ZA0506)"},
                {"ZA0513", "(divsint(dt(multsint(ZA0001))) - dt(ZA0001))"},
                {"ZA0514", "(-1 * (ZA0031))"},
                {"ZA0515", "exp(ZA0514)"},
                {"ZA0516", "((JJ * JJ) * ZA0515)"},
                {"ZA0517", "multsint(ZA0516)"},
                {"ZA0518", "multsint(ZA0517)"},
                {"ZA0519", "(9 * (ZA0518))"},
                {"ZA0520", "(ZA0000 * ZA0000)"},
                {"ZA0521", "(ZA0520 * ZA0515)"},
                {"ZA0522", "divsint(ZA0521)"},
                {"ZA0523", "divsint(ZA0522)"},
                {"ZA0524", "divsint(ZA0523)"},
                {"ZA0525", "divsint(ZA0524)"},
                {"ZA0526", "((1 / 4) * (ZA0525))"},
                {"ZA0527", "((1 / 2) * (ZA0111))"},
                {"ZA0528", "(divsint(dt(multsint(ZA0007))) - dt(ZA0007))"},
                {"ZA0529", "((1 / 2) * (ZA0528))"},
                {"ZA0530", "(ZA0000 * ZA0515)"},
                {"ZA0531", "(JJ * ZA0530)"},
                {"ZA0532", "divsint(ZA0531)"},
                {"ZA0533", "(3 * (ZA0532))"},
                {"ZA0534", "(ZA0025 * ZA0312)"},
                {"ZA0535", "(ZA0534 * ZA0029)"},
                {"ZA0536", "(ZA0535 * ZA0032)"},
                {"ZA0537", "(-1 * (ZA0536))"},
                {"ZA0538", "(ZA0306 * ZA0023)"},
                {"ZA0539", "(ZA0538 * ZA0024)"},
                {"ZA0540", "(ZA0539 * ZA0029)"},
                {"ZA0541", "(ZA0540 * ZA0032)"},
                {"ZA0542", "(2 * (ZA0541))"},
                {"ZA0543", "(-1 * (ZA0542))"},
                {"ZA0544", "(ZA0037 * ZA0001)"},
                {"ZA0545", "(ZA0544 * ZA0029)"},
                {"ZA0546", "(ZA0545 * ZA0032)"},
                {"ZA0547", "(divsint(dt(multsint(ZA0111))) - dt(ZA0111))"},
                {"ZA0548", "(divsint(dt(multsint(ZA0547))) - dt(ZA0547))"},
                {"ZA0549", "((1 / 2) * (ZA0548))"},
                {"ZA0550", "(ZA0042 * ZA0001)"},
                {"ZA0551", "(ZA0550 * BTH)"},
                {"ZA0552", "(ZA0551 * ZA0029)"},
                {"ZA0553", "(ZA0552 * ZA0032)"},
                {"ZA0554", "(-1 * (ZA0553))"},
                {"ZA0555", "(U1 * U1)"},
                {"ZA0556", "(ZA0054 * ZA0555)"},
                {"ZA0557", "(ZA0556 * ZA0029)"},
                {"ZA0558", "(ZA0557 * ZA0032)"},
                {"ZA0559", "((nexp * nexp) * ZA0558)"},
                {"ZA0560", "(2 * (ZA0559))"},
                {"ZA0561", "(-1 * (ZA0560))"},
                {"ZA0562", "(ZA0055 * ZA0029)"},
                {"ZA0563", "(ZA0562 * ZA0032)"},
                {"ZA0564", "(ZA0563 * U1)"},
                {"ZA0565", "((nexp * nexp) * ZA0564)"},
                {"ZA0566", "(divsint(dt(multsint(ZA0104))) - dt(ZA0104))"},
                {"ZA0567", "((1 / 2) * (ZA0566))"},
                {"ZA0568", "(ZA0496 * U1)"},
                {"ZA0569", "(nexp * ZA0568)"},
                {"ZA0570", "(-1 * (ZA0569))"},
                {"ZA0571", "(ZA0160 * B2)"},
                {"ZA0572", "(ZA0571 * BH)"},
                {"ZA0573", "(ZA0572 * ZA0029)"},
                {"ZA0574", "(ZA0573 * ZA0032)"},
                {"ZA0575", "(nexp * ZA0574)"},
                {"ZA0576", "(-1 * (ZA0575))"},
                {"ZA0577", "(ZA0054 * B1)"},
                {"ZA0578", "(ZA0577 * ZA0029)"},
                {"ZA0579", "(ZA0578 * ZA0032)"},
                {"ZA0580", "(ZA0579 * U1)"},
                {"ZA0581", "((nexp * nexp) * ZA0580)"},
                {"ZA0582", "(-1 * (ZA0581))"},
                {"ZA0583", "(divsint(dt(multsint(ZA0124))) - dt(ZA0124))"},
                {"ZA0584", "(-1 * (ZA0583))"},
                {"ZA0585", "(ZA0024 * ZA0245)"},
                {"ZA0586", "(ZA0585 * BTH)"},
                {"ZA0587", "(ZA0586 * BH)"},
                {"ZA0588", "(ZA0587 * ZA0029)"},
                {"ZA0589", "(ZA0588 * ZA0032)"},
                {"ZA0590", "(nexp * ZA0589)"},
                {"ZA0591", "(2 * (ZA0590))"},
                {"ZA0592", "(-1 * (ZA0591))"},
                {"ZA0593", "(divsint(dt(multsint(ZA0083))) - dt(ZA0083))"},
                {"ZA0594", "((1 / 2) * (ZA0593))"},
                {"ZA0595", "(-1 * (ZA0594))"},
                {"ZA0596", "(ZA0131 * BH)"},
                {"ZA0597", "(ZA0596 * ZA0029)"},
                {"ZA0598", "(ZA0597 * ZA0032)"},
                {"ZA0599", "(ZA0598 * U1)"},
                {"ZA0600", "(nexp * ZA0599)"},
                {"ZA0601", "(ZA0161 * P1)"},
                {"ZA0602", "(ZA0601 * BH)"},
                {"ZA0603", "(ZA0602 * ZA0029)"},
                {"ZA0604", "(ZA0603 * ZA0032)"},
                {"ZA0605", "(nexp * ZA0604)"},
                {"ZA0606", "(ZA0161 * BH)"},
                {"ZA0607", "(ZA0606 * ZA0029)"},
                {"ZA0608", "(ZA0607 * ZA0032)"},
                {"ZA0609", "(ZA0608 * U1)"},
                {"ZA0610", "(nexp * ZA0609)"},
                {"ZA0611", "(4 * (ZA0610))"},
                {"ZA0612", "(-1 * (ZA0611))"},
                {"ZA0613", "(nexp * ZA0146)"},
                {"ZA0614", "(divsint(dt(multsint(ZA0613))) - dt(ZA0613))"},
                {"ZA0615", "((1 / 2) * (ZA0614))"},
                {"ZA0616", "(-1 * (ZA0615))"},
                {"ZA0617", "(nexp * ZA0179)"},
                {"ZA0618", "(divsint(dt(multsint(ZA0617))) - dt(ZA0617))"},
                {"ZA0619", "((1 / 2) * (ZA0618))"},
                {"ZA0620", "(nexp * ZA0189)"},
                {"ZA0621", "(divsint(dt(multsint(ZA0620))) - dt(ZA0620))"},
                {"ZA0622", "(-1 * (ZA0621))"},
                {"ZA0623", "((-1 * ((1 / 2))) + ZA0389)"},
                {"ZA0624", "(ZA0623 + ZA0513)"},
                {"ZA0625", "(ZA0624 + ZA0519)"},
                {"ZA0626", "(ZA0625 + ZA0526)"},
                {"ZA0627", "(ZA0626 + ZA0527)"},
                {"ZA0628", "(ZA0627 + ZA0529)"},
                {"ZA0629", "(ZA0628 + ZA0533)"},
                {"ZA0630", "(ZA0629 + ZA0537)"},
                {"ZA0631", "(ZA0630 + ZA0543)"},
                {"ZA0632", "(ZA0631 + ZA0546)"},
                {"ZA0633", "(ZA0632 + ZA0549)"},
                {"ZA0634", "(ZA0633 + ZA0554)"},
                {"ZA0635", "(ZA0634 + ZA0561)"},
                {"ZA0636", "(ZA0635 + ZA0565)"},
                {"ZA0637", "(ZA0636 + ZA0567)"},
                {"ZA0638", "(ZA0637 + ZA0570)"},
                {"ZA0639", "(ZA0638 + ZA0576)"},
                {"ZA0640", "(ZA0639 + ZA0582)"},
                {"ZA0641", "(ZA0640 + ZA0584)"},
                {"ZA0642", "(ZA0641 + ZA0592)"},
                {"ZA0643", "(ZA0642 + ZA0595)"},
                {"ZA0644", "(ZA0643 + ZA0600)"},
                {"ZA0645", "(ZA0644 + ZA0605)"},
                {"ZA0646", "(ZA0645 + ZA0612)"},
                {"ZA0647", "(ZA0646 + ZA0616)"},
                {"ZA0648", "(ZA0647 + ZA0619)"},
                {"ZA0649", "(ZA0648 + ZA0622)"},
                {"ZA0650", "(ZA0649 + ZA0312)"},
            };
            return D;
        }

        /// ⚠ READ, not merely fetched (round 108): the value only
        /// exists once operator()(Index) has been called.
        inline void read_def(Kadath::System_of_eqs& syst,
                             const Kadath::Space& sp,
                             const char* nm, int dmin, int dmax)
        {
            for (int d = dmin; d <= dmax; d++) {
                const Kadath::Val_domain& v =
                    syst.give_val_def_scalar_domain(nm, d);
                Kadath::Index ix(sp.get_domain(d)->get_nbr_points());
                do { (void)v(ix); } while (ix.inc());
            }
        }
    } // namespace throatth_detail

    /// The six rows, with the tau mode count each projects onto.
    inline const std::vector<std::pair<const char*, const char*>>&
    throatth_rows()
    {
        static const std::vector<std::pair<const char*, const char*>> R = {
            {"TEQTW", "ZA0223"},   // E_Q, nt-1 modes
            {"TESHR", "ZA0302"},   // E_sh^r, nt modes
            {"TESHT", "ZA0443"},   // E_sh^th, nt-2 modes
            {"TEPHI", "ZA0478"},   // E_Phi, nt modes
            {"TEQFN", "ZA0512"},   // E_q, nt modes
            {"TESIG", "ZA0650"},   // E_sigma, nt modes
        };
        return R;
    }

    /// mode count per row, in the same order, as a function of nt.
    inline int throatth_row_modes(int k, int nt)
    {
        static const int OFF[6] = {-1, 0, -2, 0, 0, 0};
        return nt + OFF[k];
    }

    /// The sin(theta) weight each row carries, distributed over its
    /// monomials at emission time.  Recorded so a caller cannot
    /// apply it twice, and so the projection basis is checkable.
    inline int throatth_row_weight(int k)
    {
        static const int W[6] = {0, 0, 2, 0, 0, 0};
        return W[k];
    }

    /**
     * The twelve amplitude defs, built from the matching unknowns.
     *
     * G%02d are the grade-0 unknowns and H%02d the grade-1 ones, laid out
     * PS PH QF BR BT QB with nt, nt, nt, nt, nt-2, nt-1 modes -- the same
     * order and the same counts the probe registers them in.  A%s%02d is
     * the PURE ANGULAR profile of that family, with no radial factor: these
     * rows live at one radius, so a radial factor would be a constant
     * folded into an unknown that already carries it.
     */
    inline std::vector<std::pair<std::string, std::string>>
    throatth_amp_defs(int nt)
    {
        const int NCE = nt, NSE = nt - 2, NCO = nt - 1;
        const int cnt[6] = {NCE, NCE, NCE, NCE, NSE, NCO};
        static const char* FN[6] = {"PS", "PH", "QF", "BR", "BT", "QB"};
        static const char* AP[6] = {"ACE", "ACE", "ACE", "ACE", "ASE", "ACO"};
        int tot = 0;
        for (int q = 0; q < 6; q++) tot += cnt[q];
        if (tot != 6 * nt - 3)
            throw std::runtime_error("throatth: the matching block is not 6nt-3");
        std::vector<std::pair<std::string, std::string>> out;
        char b[64];
        int g = 0;
        for (int q = 0; q < 6; q++) {
            std::string s0, s1;
            for (int j = 0; j < cnt[q]; j++) {
                std::snprintf(b, sizeof b, "%sG%02d * %s%02d",
                              j ? " + " : "", g + j, AP[q], j);
                s0 += b;
                std::snprintf(b, sizeof b, "%sH%02d * %s%02d",
                              j ? " + " : "", g + j, AP[q], j);
                s1 += b;
            }
            g += cnt[q];
            out.push_back({std::string("S") + FN[q], "(" + s0 + ")"});
            out.push_back({std::string("H") + FN[q], "(" + s1 + ")"});
        }
        out.push_back({"UH", "((1 / 2) * (log(SPS)))"});
        out.push_back({"PHH", "SPH"});
        out.push_back({"QH", "SQF"});
        out.push_back({"BH", "SBR"});
        out.push_back({"BTH", "SBT"});
        out.push_back({"QBH", "SQB"});
        out.push_back({"U1", "(HPS / (2 * SPS))"});
        out.push_back({"P1", "(HPH / SPH)"});
        out.push_back({"Q1F", "HQF"});
        out.push_back({"B1", "(HBR / SBR)"});
        out.push_back({"B2", "HBT"});
        out.push_back({"QB1", "HQB"});
        return out;
    }

    /// Register the amplitude defs, then the def table, then the
    /// six rows -- in topological order, each READ as it lands.
    inline void throatth_register(Kadath::System_of_eqs& syst,
                                  const Kadath::Space& sp,
                                  int nt, int dmin, int dmax,
                                  bool read_defs = true)
    {
        // ⚠ EVERY add_def NAMES ITSELF ON FAILURE.  Kadath throws
        // "bad valence in definition" with no indication of WHICH,
        // and 611 defs is not a thing to bisect by hand.
        const bool trace = (std::getenv("THROATTH_TRACE") != 0);
        const char* mx = std::getenv("THROATTH_MAX");
        const int maxdef = mx ? std::atoi(mx) : -1;
        int ndone = 0;
        auto one = [&](const std::string& nm, const std::string& tx) {
            // ⚠ A SEGFAULT NAMES NOTHING, and an exception message
            // that names the def is no help when the failure is a
            // signal.  THROATTH_TRACE=1 prints each name BEFORE it
            // is parsed and flushes, so the last line is the one.
            if (maxdef >= 0 && ndone >= maxdef) return;
            ndone++;
            if (trace) { std::printf("throatth %s = %s\n", nm.c_str(), tx.c_str()); std::fflush(stdout); }
            try {
                // ⚠ THE ONE-ARGUMENT OVERLOAD, AND IT IS NOT COSMETIC.
                // add_def(name) loops dom_min..dom_max and calls
                // add_def(dom, name) for each -- so the two spellings
                // should be the same loop.  They are not: a def
                // registered through the per-domain call cannot be
                // SUMMED afterwards, and the sum segfaults inside
                // Ope_def on a null val_t.  Isolated by registering the
                // identical 5-term expression both ways in one run and
                // adding each to the same third def: the one-argument
                // spelling lives, the per-domain one dies.  Nothing
                // about WHICH defs exist changes, which is why this is
                // a safe fix and not an explanation.
                syst.add_def((nm + " = " + tx).c_str());
            } catch (const std::exception& ex) {
                throw std::runtime_error("throatth: " + nm + " = "
                    + tx + "  ->  " + ex.what());
            }
            if (read_defs)
                throatth_detail::read_def(syst, sp, nm.c_str(), dmin, dmax);
        };
        for (const auto& a : throatth_amp_defs(nt)) one(a.first, a.second);
        for (const auto& d : throatth_detail::subdefs()) one(d.name, d.def);
        if (maxdef < 0)
            for (const auto& r : throatth_rows()) one(r.first, r.second);
    }
} // namespace Trumpet
