/*
 * throatth_eqs.hpp -- GENERATED by scripts/throat_emit.py.  Do not edit.
 *
 * The grade-1 throat rows as theta-ODEs at the inner face: the INNER
 * BOUNDARY CONDITION of the matched formulation (research round 504),
 * 6nt - 3 conditions on the 6nt - 3 grade-0 and 6nt - 3 grade-1
 * matching amplitudes.
 *
 * Every monomial was checked as an IDENTITY against its sympy original by
 * reading the emitted string back through the inverse vocabulary, and the
 * emission was refused by the axis lattice until E_sh^theta carried its
 * sin(theta) weight distributed over the monomials and Qbar was declared
 * at sin-order 4 (research round 511 ruling 3: Qb == multsint^4(QB)).
 */
#pragma once

#include <cstdio>
#include <cstdlib>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include "For_Kadath/Array/headcpp.hpp"
#include "For_Kadath/Space/space.hpp"
#include "For_Kadath/System_of_eqs/system_of_eqs.hpp"

namespace Trumpet
{
    struct ThDef { const char* name; const char* def; };

    namespace throatth_detail
    {
        inline const std::vector<ThDef>& subdefs()
        {
            static const std::vector<ThDef> D = {
                {"ZA0000", "dt(QBH)"},
                {"ZA0001", "dt(UH)"},
                {"ZA0002", "(ZA0000 * ZA0001)"},
                {"ZA0003", "(8 * (ZA0002))"},
                {"ZA0004", "(-1 * (ZA0003))"},
                {"ZA0005", "(1 / (PHH))"},
                {"ZA0006", "dt(PHH)"},
                {"ZA0007", "(ZA0005 * ZA0006)"},
                {"ZA0008", "(ZA0007 * ZA0000)"},
                {"ZA0009", "JJ"},
                {"ZA0010", "(ZA0009 * ZA0001)"},
                {"ZA0011", "multsint(ZA0010)"},
                {"ZA0012", "multsint(ZA0011)"},
                {"ZA0013", "multsint(ZA0012)"},
                {"ZA0014", "(48 * (ZA0013))"},
                {"ZA0015", "(-1 * (ZA0014))"},
                {"ZA0016", "(divsint(dt(multsint(ZA0000))) - dt(ZA0000))"},
                {"ZA0017", "(3 * (ZA0016))"},
                {"ZA0018", "(-1 * (ZA0017))"},
                {"ZA0019", "(ZA0009 * ZA0005)"},
                {"ZA0020", "(ZA0019 * ZA0006)"},
                {"ZA0021", "multsint(ZA0020)"},
                {"ZA0022", "multsint(ZA0021)"},
                {"ZA0023", "multsint(ZA0022)"},
                {"ZA0024", "(6 * (ZA0023))"},
                {"ZA0025", "(BTH * BTH)"},
                {"ZA0026", "(ZA0005 * ZA0005)"},
                {"ZA0027", "dt(ZA0000)"},
                {"ZA0028", "(2 * (QH))"},
                {"ZA0029", "exp(ZA0028)"},
                {"ZA0030", "(8 * (UH))"},
                {"ZA0031", "exp(ZA0030)"},
                {"ZA0032", "(ZA0025 * ZA0026)"},
                {"ZA0033", "(ZA0032 * ZA0027)"},
                {"ZA0034", "(ZA0033 * ZA0029)"},
                {"ZA0035", "(ZA0034 * ZA0031)"},
                {"ZA0036", "(-1 * (ZA0035))"},
                {"ZA0037", "(ZA0026 * ZA0005)"},
                {"ZA0038", "(ZA0025 * ZA0037)"},
                {"ZA0039", "(ZA0038 * ZA0006)"},
                {"ZA0040", "(ZA0039 * ZA0000)"},
                {"ZA0041", "(ZA0040 * ZA0029)"},
                {"ZA0042", "(ZA0041 * ZA0031)"},
                {"ZA0043", "dt(BTH)"},
                {"ZA0044", "(ZA0026 * ZA0043)"},
                {"ZA0045", "(ZA0044 * ZA0000)"},
                {"ZA0046", "(ZA0045 * BTH)"},
                {"ZA0047", "(ZA0046 * ZA0029)"},
                {"ZA0048", "(ZA0047 * ZA0031)"},
                {"ZA0049", "(-1 * (ZA0048))"},
                {"ZA0050", "(ZA0032 * ZA0000)"},
                {"ZA0051", "(ZA0050 * ZA0001)"},
                {"ZA0052", "(ZA0051 * ZA0029)"},
                {"ZA0053", "(ZA0052 * ZA0031)"},
                {"ZA0054", "(6 * (ZA0053))"},
                {"ZA0055", "nexp"},
                {"ZA0056", "(ZA0055 * ZA0055)"},
                {"ZA0057", "(BH * BH)"},
                {"ZA0058", "(ZA0056 * ZA0026)"},
                {"ZA0059", "(ZA0058 * ZA0057)"},
                {"ZA0060", "(ZA0059 * P1)"},
                {"ZA0061", "(ZA0060 * QB1)"},
                {"ZA0062", "(ZA0061 * ZA0029)"},
                {"ZA0063", "(ZA0062 * ZA0031)"},
                {"ZA0064", "(ZA0055 * ZA0026)"},
                {"ZA0065", "(ZA0064 * ZA0000)"},
                {"ZA0066", "(ZA0065 * B2)"},
                {"ZA0067", "(ZA0066 * BH)"},
                {"ZA0068", "(ZA0067 * ZA0029)"},
                {"ZA0069", "(ZA0068 * ZA0031)"},
                {"ZA0070", "(-1 * (ZA0069))"},
                {"ZA0071", "dt(BH)"},
                {"ZA0072", "(ZA0064 * ZA0071)"},
                {"ZA0073", "(ZA0072 * BTH)"},
                {"ZA0074", "(ZA0073 * QB1)"},
                {"ZA0075", "(ZA0074 * ZA0029)"},
                {"ZA0076", "(ZA0075 * ZA0031)"},
                {"ZA0077", "(-1 * (ZA0076))"},
                {"ZA0078", "(ZA0059 * QB1)"},
                {"ZA0079", "(ZA0078 * B1)"},
                {"ZA0080", "(ZA0079 * ZA0029)"},
                {"ZA0081", "(ZA0080 * ZA0031)"},
                {"ZA0082", "(-1 * (ZA0081))"},
                {"ZA0083", "(ZA0009 * ZA0026)"},
                {"ZA0084", "(ZA0083 * ZA0043)"},
                {"ZA0085", "(ZA0084 * BTH)"},
                {"ZA0086", "(ZA0085 * ZA0029)"},
                {"ZA0087", "(ZA0086 * ZA0031)"},
                {"ZA0088", "multsint(ZA0087)"},
                {"ZA0089", "multsint(ZA0088)"},
                {"ZA0090", "multsint(ZA0089)"},
                {"ZA0091", "(6 * (ZA0090))"},
                {"ZA0092", "(-1 * (ZA0091))"},
                {"ZA0093", "dt(QB1)"},
                {"ZA0094", "(ZA0064 * ZA0093)"},
                {"ZA0095", "(ZA0094 * BTH)"},
                {"ZA0096", "(ZA0095 * BH)"},
                {"ZA0097", "(ZA0096 * ZA0029)"},
                {"ZA0098", "(ZA0097 * ZA0031)"},
                {"ZA0099", "(2 * (ZA0098))"},
                {"ZA0100", "(-1 * (ZA0099))"},
                {"ZA0101", "(ZA0050 * ZA0029)"},
                {"ZA0102", "(ZA0101 * ZA0031)"},
                {"ZA0103", "(divsint(dt(multsint(ZA0102))) - dt(ZA0102))"},
                {"ZA0104", "(4 * (ZA0103))"},
                {"ZA0105", "(ZA0009 * ZA0025)"},
                {"ZA0106", "(ZA0105 * ZA0037)"},
                {"ZA0107", "(ZA0106 * ZA0006)"},
                {"ZA0108", "(ZA0107 * ZA0029)"},
                {"ZA0109", "(ZA0108 * ZA0031)"},
                {"ZA0110", "multsint(ZA0109)"},
                {"ZA0111", "multsint(ZA0110)"},
                {"ZA0112", "multsint(ZA0111)"},
                {"ZA0113", "(6 * (ZA0112))"},
                {"ZA0114", "(ZA0105 * ZA0026)"},
                {"ZA0115", "(ZA0114 * ZA0029)"},
                {"ZA0116", "(ZA0115 * ZA0031)"},
                {"ZA0117", "(dt(multsint(ZA0116)) - multsint(dt(ZA0116)))"},
                {"ZA0118", "multsint(ZA0117)"},
                {"ZA0119", "multsint(ZA0118)"},
                {"ZA0120", "(6 * (ZA0119))"},
                {"ZA0121", "(ZA0078 * ZA0029)"},
                {"ZA0122", "(ZA0121 * ZA0031)"},
                {"ZA0123", "(ZA0122 * U1)"},
                {"ZA0124", "(6 * (ZA0123))"},
                {"ZA0125", "(ZA0114 * ZA0001)"},
                {"ZA0126", "(ZA0125 * ZA0029)"},
                {"ZA0127", "(ZA0126 * ZA0031)"},
                {"ZA0128", "multsint(ZA0127)"},
                {"ZA0129", "multsint(ZA0128)"},
                {"ZA0130", "multsint(ZA0129)"},
                {"ZA0131", "(36 * (ZA0130))"},
                {"ZA0132", "(ZA0055 * ZA0037)"},
                {"ZA0133", "(ZA0132 * ZA0006)"},
                {"ZA0134", "(ZA0133 * BTH)"},
                {"ZA0135", "(ZA0134 * QB1)"},
                {"ZA0136", "(ZA0135 * BH)"},
                {"ZA0137", "(ZA0136 * ZA0029)"},
                {"ZA0138", "(ZA0137 * ZA0031)"},
                {"ZA0139", "(ZA0065 * BTH)"},
                {"ZA0140", "(ZA0139 * P1)"},
                {"ZA0141", "(ZA0140 * BH)"},
                {"ZA0142", "(ZA0141 * ZA0029)"},
                {"ZA0143", "(ZA0142 * ZA0031)"},
                {"ZA0144", "(ZA0009 * ZA0055)"},
                {"ZA0145", "(ZA0144 * ZA0026)"},
                {"ZA0146", "(ZA0145 * B2)"},
                {"ZA0147", "(ZA0146 * BH)"},
                {"ZA0148", "(ZA0147 * ZA0029)"},
                {"ZA0149", "(ZA0148 * ZA0031)"},
                {"ZA0150", "multsint(ZA0149)"},
                {"ZA0151", "multsint(ZA0150)"},
                {"ZA0152", "multsint(ZA0151)"},
                {"ZA0153", "(6 * (ZA0152))"},
                {"ZA0154", "(-1 * (ZA0153))"},
                {"ZA0155", "(ZA0139 * BH)"},
                {"ZA0156", "(ZA0155 * ZA0029)"},
                {"ZA0157", "(ZA0156 * ZA0031)"},
                {"ZA0158", "(ZA0157 * U1)"},
                {"ZA0159", "(6 * (ZA0158))"},
                {"ZA0160", "(ZA0064 * ZA0001)"},
                {"ZA0161", "(ZA0160 * BTH)"},
                {"ZA0162", "(ZA0161 * QB1)"},
                {"ZA0163", "(ZA0162 * BH)"},
                {"ZA0164", "(ZA0163 * ZA0029)"},
                {"ZA0165", "(ZA0164 * ZA0031)"},
                {"ZA0166", "(6 * (ZA0165))"},
                {"ZA0167", "(ZA0064 * BTH)"},
                {"ZA0168", "(ZA0167 * QB1)"},
                {"ZA0169", "(ZA0168 * BH)"},
                {"ZA0170", "(ZA0169 * ZA0029)"},
                {"ZA0171", "(ZA0170 * ZA0031)"},
                {"ZA0172", "(divsint(dt(multsint(ZA0171))) - dt(ZA0171))"},
                {"ZA0173", "(4 * (ZA0172))"},
                {"ZA0174", "(ZA0145 * BTH)"},
                {"ZA0175", "(ZA0174 * P1)"},
                {"ZA0176", "(ZA0175 * BH)"},
                {"ZA0177", "(ZA0176 * ZA0029)"},
                {"ZA0178", "(ZA0177 * ZA0031)"},
                {"ZA0179", "multsint(ZA0178)"},
                {"ZA0180", "multsint(ZA0179)"},
                {"ZA0181", "multsint(ZA0180)"},
                {"ZA0182", "(6 * (ZA0181))"},
                {"ZA0183", "(ZA0174 * BH)"},
                {"ZA0184", "(ZA0183 * ZA0029)"},
                {"ZA0185", "(ZA0184 * ZA0031)"},
                {"ZA0186", "(ZA0185 * U1)"},
                {"ZA0187", "multsint(ZA0186)"},
                {"ZA0188", "multsint(ZA0187)"},
                {"ZA0189", "multsint(ZA0188)"},
                {"ZA0190", "(36 * (ZA0189))"},
                {"ZA0191", "(ZA0004 + ZA0008)"},
                {"ZA0192", "(ZA0191 + ZA0015)"},
                {"ZA0193", "(ZA0192 + ZA0018)"},
                {"ZA0194", "(ZA0193 + ZA0024)"},
                {"ZA0195", "(ZA0194 + ZA0036)"},
                {"ZA0196", "(ZA0195 + ZA0042)"},
                {"ZA0197", "(ZA0196 + ZA0049)"},
                {"ZA0198", "(ZA0197 + ZA0054)"},
                {"ZA0199", "(ZA0198 + ZA0063)"},
                {"ZA0200", "(ZA0199 + ZA0070)"},
                {"ZA0201", "(ZA0200 + ZA0077)"},
                {"ZA0202", "(ZA0201 + ZA0082)"},
                {"ZA0203", "(ZA0202 + ZA0092)"},
                {"ZA0204", "(ZA0203 + ZA0100)"},
                {"ZA0205", "(ZA0204 + ZA0104)"},
                {"ZA0206", "(ZA0205 + ZA0113)"},
                {"ZA0207", "(ZA0206 + ZA0120)"},
                {"ZA0208", "(ZA0207 + ZA0124)"},
                {"ZA0209", "(ZA0208 + ZA0131)"},
                {"ZA0210", "(ZA0209 + ZA0138)"},
                {"ZA0211", "(ZA0210 + ZA0143)"},
                {"ZA0212", "(ZA0211 + ZA0154)"},
                {"ZA0213", "(ZA0212 + ZA0159)"},
                {"ZA0214", "(ZA0213 + ZA0166)"},
                {"ZA0215", "(ZA0214 + ZA0173)"},
                {"ZA0216", "(ZA0215 + ZA0182)"},
                {"ZA0217", "(ZA0216 + ZA0190)"},
                {"ZA0218", "(ZA0217 + ZA0027)"},
                {"ZA0219", "(ZA0055 * ZA0043)"},
                {"ZA0220", "dt(B1)"},
                {"ZA0221", "dt(ZA0220)"},
                {"ZA0222", "(ZA0221 * BH)"},
                {"ZA0223", "dt(ZA0071)"},
                {"ZA0224", "(ZA0223 * B1)"},
                {"ZA0225", "dt(P1)"},
                {"ZA0226", "(ZA0225 * ZA0071)"},
                {"ZA0227", "(-1 * (ZA0226))"},
                {"ZA0228", "(ZA0001 * BTH)"},
                {"ZA0229", "(8 * (ZA0228))"},
                {"ZA0230", "(-1 * (ZA0229))"},
                {"ZA0231", "dt(QH)"},
                {"ZA0232", "(ZA0231 * BTH)"},
                {"ZA0233", "(2 * (ZA0232))"},
                {"ZA0234", "(-1 * (ZA0233))"},
                {"ZA0235", "(ZA0220 * ZA0071)"},
                {"ZA0236", "(2 * (ZA0235))"},
                {"ZA0237", "dt(Q1F)"},
                {"ZA0238", "(ZA0071 * ZA0237)"},
                {"ZA0239", "(2 * (ZA0238))"},
                {"ZA0240", "dt(U1)"},
                {"ZA0241", "(ZA0071 * ZA0240)"},
                {"ZA0242", "(8 * (ZA0241))"},
                {"ZA0243", "(ZA0007 * BTH)"},
                {"ZA0244", "(divsint(dt(multsint(BTH))) - dt(BTH))"},
                {"ZA0245", "(-1 * (ZA0244))"},
                {"ZA0246", "(ZA0055 * ZA0231)"},
                {"ZA0247", "(ZA0246 * BTH)"},
                {"ZA0248", "(2 * (ZA0247))"},
                {"ZA0249", "(ZA0220 * ZA0231)"},
                {"ZA0250", "(ZA0249 * BH)"},
                {"ZA0251", "(2 * (ZA0250))"},
                {"ZA0252", "(ZA0071 * ZA0231)"},
                {"ZA0253", "(ZA0252 * B1)"},
                {"ZA0254", "(2 * (ZA0253))"},
                {"ZA0255", "(ZA0055 * ZA0001)"},
                {"ZA0256", "(ZA0255 * BTH)"},
                {"ZA0257", "(8 * (ZA0256))"},
                {"ZA0258", "(ZA0220 * ZA0001)"},
                {"ZA0259", "(ZA0258 * BH)"},
                {"ZA0260", "(8 * (ZA0259))"},
                {"ZA0261", "(ZA0071 * ZA0001)"},
                {"ZA0262", "(ZA0261 * B1)"},
                {"ZA0263", "(8 * (ZA0262))"},
                {"ZA0264", "(ZA0055 * BTH)"},
                {"ZA0265", "(divsint(dt(multsint(ZA0264))) - dt(ZA0264))"},
                {"ZA0266", "(ZA0220 * BH)"},
                {"ZA0267", "(divsint(dt(multsint(ZA0266))) - dt(ZA0266))"},
                {"ZA0268", "(ZA0071 * B1)"},
                {"ZA0269", "(divsint(dt(multsint(ZA0268))) - dt(ZA0268))"},
                {"ZA0270", "(ZA0055 * ZA0005)"},
                {"ZA0271", "(ZA0270 * ZA0006)"},
                {"ZA0272", "(ZA0271 * BTH)"},
                {"ZA0273", "(-1 * (ZA0272))"},
                {"ZA0274", "(ZA0007 * ZA0220)"},
                {"ZA0275", "(ZA0274 * BH)"},
                {"ZA0276", "(-1 * (ZA0275))"},
                {"ZA0277", "(ZA0007 * ZA0071)"},
                {"ZA0278", "(ZA0277 * B1)"},
                {"ZA0279", "(-1 * (ZA0278))"},
                {"ZA0280", "(ZA0219 + ZA0222)"},
                {"ZA0281", "(ZA0280 + ZA0224)"},
                {"ZA0282", "(ZA0281 + ZA0227)"},
                {"ZA0283", "(ZA0282 + ZA0230)"},
                {"ZA0284", "(ZA0283 + ZA0234)"},
                {"ZA0285", "(ZA0284 + ZA0236)"},
                {"ZA0286", "(ZA0285 + ZA0239)"},
                {"ZA0287", "(ZA0286 + ZA0242)"},
                {"ZA0288", "(ZA0287 + ZA0243)"},
                {"ZA0289", "(ZA0288 + ZA0245)"},
                {"ZA0290", "(ZA0289 + ZA0248)"},
                {"ZA0291", "(ZA0290 + ZA0251)"},
                {"ZA0292", "(ZA0291 + ZA0254)"},
                {"ZA0293", "(ZA0292 + ZA0257)"},
                {"ZA0294", "(ZA0293 + ZA0260)"},
                {"ZA0295", "(ZA0294 + ZA0263)"},
                {"ZA0296", "(ZA0295 + ZA0265)"},
                {"ZA0297", "(ZA0296 + ZA0267)"},
                {"ZA0298", "(ZA0297 + ZA0269)"},
                {"ZA0299", "(ZA0298 + ZA0273)"},
                {"ZA0300", "(ZA0299 + ZA0276)"},
                {"ZA0301", "(ZA0300 + ZA0279)"},
                {"ZA0302", "multsint(BTH)"},
                {"ZA0303", "(2 * (ZA0302))"},
                {"ZA0304", "(ZA0001 * ZA0001)"},
                {"ZA0305", "(ZA0304 * BTH)"},
                {"ZA0306", "multsint(ZA0305)"},
                {"ZA0307", "(16 * (ZA0306))"},
                {"ZA0308", "(-1 * (ZA0307))"},
                {"ZA0309", "dt(ZA0001)"},
                {"ZA0310", "(ZA0309 * BTH)"},
                {"ZA0311", "multsint(ZA0310)"},
                {"ZA0312", "(2 * (ZA0311))"},
                {"ZA0313", "(-1 * (ZA0312))"},
                {"ZA0314", "(ZA0043 * ZA0231)"},
                {"ZA0315", "multsint(ZA0314)"},
                {"ZA0316", "(2 * (ZA0315))"},
                {"ZA0317", "(ZA0043 * ZA0001)"},
                {"ZA0318", "multsint(ZA0317)"},
                {"ZA0319", "(6 * (ZA0318))"},
                {"ZA0320", "(ZA0055 * ZA0220)"},
                {"ZA0321", "(ZA0320 * BH)"},
                {"ZA0322", "multsint(ZA0321)"},
                {"ZA0323", "(-1 * (ZA0322))"},
                {"ZA0324", "(ZA0055 * ZA0071)"},
                {"ZA0325", "(ZA0324 * P1)"},
                {"ZA0326", "multsint(ZA0325)"},
                {"ZA0327", "(-1 * (ZA0326))"},
                {"ZA0328", "(ZA0324 * B1)"},
                {"ZA0329", "multsint(ZA0328)"},
                {"ZA0330", "(-1 * (ZA0329))"},
                {"ZA0331", "(ZA0005 * ZA0043)"},
                {"ZA0332", "(ZA0331 * ZA0006)"},
                {"ZA0333", "multsint(ZA0332)"},
                {"ZA0334", "(-1 * (ZA0333))"},
                {"ZA0335", "(ZA0055 * ZA0240)"},
                {"ZA0336", "(ZA0335 * BH)"},
                {"ZA0337", "multsint(ZA0336)"},
                {"ZA0338", "(2 * (ZA0337))"},
                {"ZA0339", "(-1 * (ZA0338))"},
                {"ZA0340", "(dt(multsint(ZA0244)) - multsint(dt(ZA0244)))"},
                {"ZA0341", "(2 * (ZA0340))"},
                {"ZA0342", "(-1 * (ZA0341))"},
                {"ZA0343", "(ZA0324 * Q1F)"},
                {"ZA0344", "multsint(ZA0343)"},
                {"ZA0345", "(2 * (ZA0344))"},
                {"ZA0346", "(ZA0324 * U1)"},
                {"ZA0347", "multsint(ZA0346)"},
                {"ZA0348", "(6 * (ZA0347))"},
                {"ZA0349", "(ZA0255 * BH)"},
                {"ZA0350", "(ZA0349 * U1)"},
                {"ZA0351", "multsint(ZA0350)"},
                {"ZA0352", "(16 * (ZA0351))"},
                {"ZA0353", "(-1 * (ZA0352))"},
                {"ZA0354", "(dt(multsint(ZA0228)) - multsint(dt(ZA0228)))"},
                {"ZA0355", "(14 * (ZA0354))"},
                {"ZA0356", "(-1 * (ZA0355))"},
                {"ZA0357", "(ZA0255 * B1)"},
                {"ZA0358", "(ZA0357 * BH)"},
                {"ZA0359", "multsint(ZA0358)"},
                {"ZA0360", "(8 * (ZA0359))"},
                {"ZA0361", "(-1 * (ZA0360))"},
                {"ZA0362", "(ZA0246 * B1)"},
                {"ZA0363", "(ZA0362 * BH)"},
                {"ZA0364", "multsint(ZA0363)"},
                {"ZA0365", "(2 * (ZA0364))"},
                {"ZA0366", "(-1 * (ZA0365))"},
                {"ZA0367", "(ZA0007 * ZA0001)"},
                {"ZA0368", "(ZA0367 * BTH)"},
                {"ZA0369", "multsint(ZA0368)"},
                {"ZA0370", "(2 * (ZA0369))"},
                {"ZA0371", "(ZA0271 * B1)"},
                {"ZA0372", "(ZA0371 * BH)"},
                {"ZA0373", "multsint(ZA0372)"},
                {"ZA0374", "(dt(multsint(ZA0243)) - multsint(dt(ZA0243)))"},
                {"ZA0375", "(ZA0055 * B1)"},
                {"ZA0376", "(ZA0375 * BH)"},
                {"ZA0377", "(dt(multsint(ZA0376)) - multsint(dt(ZA0376)))"},
                {"ZA0378", "(-1 * (ZA0377))"},
                {"ZA0379", "(ZA0055 * BH)"},
                {"ZA0380", "(ZA0379 * U1)"},
                {"ZA0381", "(dt(multsint(ZA0380)) - multsint(dt(ZA0380)))"},
                {"ZA0382", "(6 * (ZA0381))"},
                {"ZA0383", "(-1 * (ZA0382))"},
                {"ZA0384", "(ZA0271 * BH)"},
                {"ZA0385", "(ZA0384 * U1)"},
                {"ZA0386", "multsint(ZA0385)"},
                {"ZA0387", "(2 * (ZA0386))"},
                {"ZA0388", "dt(ZA0043)"},
                {"ZA0389", "multsint(ZA0388)"},
                {"ZA0390", "(ZA0303 + ZA0308)"},
                {"ZA0391", "(ZA0390 + ZA0313)"},
                {"ZA0392", "(ZA0391 + ZA0316)"},
                {"ZA0393", "(ZA0392 + ZA0319)"},
                {"ZA0394", "(ZA0393 + ZA0323)"},
                {"ZA0395", "(ZA0394 + ZA0327)"},
                {"ZA0396", "(ZA0395 + ZA0330)"},
                {"ZA0397", "(ZA0396 + ZA0334)"},
                {"ZA0398", "(ZA0397 + ZA0339)"},
                {"ZA0399", "(ZA0398 + ZA0342)"},
                {"ZA0400", "(ZA0399 + ZA0345)"},
                {"ZA0401", "(ZA0400 + ZA0348)"},
                {"ZA0402", "(ZA0401 + ZA0353)"},
                {"ZA0403", "(ZA0402 + ZA0356)"},
                {"ZA0404", "(ZA0403 + ZA0361)"},
                {"ZA0405", "(ZA0404 + ZA0366)"},
                {"ZA0406", "(ZA0405 + ZA0370)"},
                {"ZA0407", "(ZA0406 + ZA0373)"},
                {"ZA0408", "(ZA0407 + ZA0374)"},
                {"ZA0409", "(ZA0408 + ZA0378)"},
                {"ZA0410", "(ZA0409 + ZA0383)"},
                {"ZA0411", "(ZA0410 + ZA0387)"},
                {"ZA0412", "(ZA0411 + ZA0389)"},
                {"ZA0413", "(ZA0005 * ZA0071)"},
                {"ZA0414", "(ZA0413 * BTH)"},
                {"ZA0415", "(ZA0414 * ZA0029)"},
                {"ZA0416", "(ZA0415 * ZA0031)"},
                {"ZA0417", "(ZA0071 * ZA0071)"},
                {"ZA0418", "(ZA0417 * ZA0005)"},
                {"ZA0419", "(ZA0418 * P1)"},
                {"ZA0420", "(ZA0419 * ZA0029)"},
                {"ZA0421", "(ZA0420 * ZA0031)"},
                {"ZA0422", "((1 / 2) * (ZA0421))"},
                {"ZA0423", "(ZA0418 * B1)"},
                {"ZA0424", "(ZA0423 * ZA0029)"},
                {"ZA0425", "(ZA0424 * ZA0031)"},
                {"ZA0426", "(-1 * (ZA0425))"},
                {"ZA0427", "(ZA0418 * ZA0029)"},
                {"ZA0428", "(ZA0427 * ZA0031)"},
                {"ZA0429", "(ZA0428 * Q1F)"},
                {"ZA0430", "(-1 * (ZA0429))"},
                {"ZA0431", "(ZA0428 * U1)"},
                {"ZA0432", "(4 * (ZA0431))"},
                {"ZA0433", "(-1 * (ZA0432))"},
                {"ZA0434", "(ZA0270 * ZA0071)"},
                {"ZA0435", "(ZA0434 * BTH)"},
                {"ZA0436", "(ZA0435 * ZA0029)"},
                {"ZA0437", "(ZA0436 * ZA0031)"},
                {"ZA0438", "(-1 * (ZA0437))"},
                {"ZA0439", "(ZA0005 * ZA0220)"},
                {"ZA0440", "(ZA0439 * ZA0071)"},
                {"ZA0441", "(ZA0440 * BH)"},
                {"ZA0442", "(ZA0441 * ZA0029)"},
                {"ZA0443", "(ZA0442 * ZA0031)"},
                {"ZA0444", "(-1 * (ZA0443))"},
                {"ZA0445", "(ZA0416 + ZA0422)"},
                {"ZA0446", "(ZA0445 + ZA0426)"},
                {"ZA0447", "(ZA0446 + ZA0430)"},
                {"ZA0448", "(ZA0447 + ZA0433)"},
                {"ZA0449", "(ZA0448 + ZA0438)"},
                {"ZA0450", "(ZA0449 + ZA0444)"},
                {"ZA0451", "(ZA0417 * ZA0026)"},
                {"ZA0452", "(ZA0451 * B1)"},
                {"ZA0453", "(ZA0452 * ZA0029)"},
                {"ZA0454", "(ZA0453 * ZA0031)"},
                {"ZA0455", "((1 / 2) * (ZA0454))"},
                {"ZA0456", "(ZA0451 * ZA0029)"},
                {"ZA0457", "(ZA0456 * ZA0031)"},
                {"ZA0458", "(ZA0457 * Q1F)"},
                {"ZA0459", "((1 / 2) * (ZA0458))"},
                {"ZA0460", "(ZA0457 * U1)"},
                {"ZA0461", "(2 * (ZA0460))"},
                {"ZA0462", "(ZA0451 * P1)"},
                {"ZA0463", "(ZA0462 * ZA0029)"},
                {"ZA0464", "(ZA0463 * ZA0031)"},
                {"ZA0465", "((1 / 2) * (ZA0464))"},
                {"ZA0466", "(-1 * (ZA0465))"},
                {"ZA0467", "(ZA0026 * ZA0071)"},
                {"ZA0468", "(ZA0467 * BTH)"},
                {"ZA0469", "(ZA0468 * ZA0029)"},
                {"ZA0470", "(ZA0469 * ZA0031)"},
                {"ZA0471", "((1 / 2) * (ZA0470))"},
                {"ZA0472", "(-1 * (ZA0471))"},
                {"ZA0473", "(ZA0073 * ZA0029)"},
                {"ZA0474", "(ZA0473 * ZA0031)"},
                {"ZA0475", "((1 / 2) * (ZA0474))"},
                {"ZA0476", "(ZA0026 * ZA0220)"},
                {"ZA0477", "(ZA0476 * ZA0071)"},
                {"ZA0478", "(ZA0477 * BH)"},
                {"ZA0479", "(ZA0478 * ZA0029)"},
                {"ZA0480", "(ZA0479 * ZA0031)"},
                {"ZA0481", "((1 / 2) * (ZA0480))"},
                {"ZA0482", "(ZA0455 + ZA0459)"},
                {"ZA0483", "(ZA0482 + ZA0461)"},
                {"ZA0484", "(ZA0483 + ZA0466)"},
                {"ZA0485", "(ZA0484 + ZA0472)"},
                {"ZA0486", "(ZA0485 + ZA0475)"},
                {"ZA0487", "(ZA0486 + ZA0481)"},
                {"ZA0488", "(divsint(dt(multsint(ZA0001))) - dt(ZA0001))"},
                {"ZA0489", "(ZA0009 * ZA0009)"},
                {"ZA0490", "(-1 * (ZA0030))"},
                {"ZA0491", "exp(ZA0490)"},
                {"ZA0492", "(ZA0489 * ZA0491)"},
                {"ZA0493", "multsint(ZA0492)"},
                {"ZA0494", "multsint(ZA0493)"},
                {"ZA0495", "(9 * (ZA0494))"},
                {"ZA0496", "(ZA0000 * ZA0000)"},
                {"ZA0497", "(ZA0496 * ZA0491)"},
                {"ZA0498", "divsint(ZA0497)"},
                {"ZA0499", "divsint(ZA0498)"},
                {"ZA0500", "divsint(ZA0499)"},
                {"ZA0501", "divsint(ZA0500)"},
                {"ZA0502", "((1 / 4) * (ZA0501))"},
                {"ZA0503", "(ZA0032 * ZA0029)"},
                {"ZA0504", "(ZA0503 * ZA0031)"},
                {"ZA0505", "((1 / 2) * (ZA0504))"},
                {"ZA0506", "(divsint(dt(multsint(ZA0007))) - dt(ZA0007))"},
                {"ZA0507", "((1 / 2) * (ZA0506))"},
                {"ZA0508", "(ZA0009 * ZA0000)"},
                {"ZA0509", "(ZA0508 * ZA0491)"},
                {"ZA0510", "divsint(ZA0509)"},
                {"ZA0511", "(3 * (ZA0510))"},
                {"ZA0512", "(ZA0032 * ZA0309)"},
                {"ZA0513", "(ZA0512 * ZA0029)"},
                {"ZA0514", "(ZA0513 * ZA0031)"},
                {"ZA0515", "(-1 * (ZA0514))"},
                {"ZA0516", "(ZA0304 * ZA0025)"},
                {"ZA0517", "(ZA0516 * ZA0026)"},
                {"ZA0518", "(ZA0517 * ZA0029)"},
                {"ZA0519", "(ZA0518 * ZA0031)"},
                {"ZA0520", "(2 * (ZA0519))"},
                {"ZA0521", "(-1 * (ZA0520))"},
                {"ZA0522", "(ZA0039 * ZA0001)"},
                {"ZA0523", "(ZA0522 * ZA0029)"},
                {"ZA0524", "(ZA0523 * ZA0031)"},
                {"ZA0525", "(divsint(dt(multsint(ZA0504))) - dt(ZA0504))"},
                {"ZA0526", "(divsint(dt(multsint(ZA0525))) - dt(ZA0525))"},
                {"ZA0527", "((1 / 2) * (ZA0526))"},
                {"ZA0528", "(ZA0044 * ZA0001)"},
                {"ZA0529", "(ZA0528 * BTH)"},
                {"ZA0530", "(ZA0529 * ZA0029)"},
                {"ZA0531", "(ZA0530 * ZA0031)"},
                {"ZA0532", "(-1 * (ZA0531))"},
                {"ZA0533", "(U1 * U1)"},
                {"ZA0534", "(ZA0059 * ZA0533)"},
                {"ZA0535", "(ZA0534 * ZA0029)"},
                {"ZA0536", "(ZA0535 * ZA0031)"},
                {"ZA0537", "(2 * (ZA0536))"},
                {"ZA0538", "(-1 * (ZA0537))"},
                {"ZA0539", "(ZA0060 * ZA0029)"},
                {"ZA0540", "(ZA0539 * ZA0031)"},
                {"ZA0541", "(ZA0540 * U1)"},
                {"ZA0542", "(ZA0039 * ZA0029)"},
                {"ZA0543", "(ZA0542 * ZA0031)"},
                {"ZA0544", "(divsint(dt(multsint(ZA0543))) - dt(ZA0543))"},
                {"ZA0545", "((1 / 2) * (ZA0544))"},
                {"ZA0546", "(ZA0474 * U1)"},
                {"ZA0547", "(-1 * (ZA0546))"},
                {"ZA0548", "(ZA0160 * B2)"},
                {"ZA0549", "(ZA0548 * BH)"},
                {"ZA0550", "(ZA0549 * ZA0029)"},
                {"ZA0551", "(ZA0550 * ZA0031)"},
                {"ZA0552", "(-1 * (ZA0551))"},
                {"ZA0553", "(ZA0059 * B1)"},
                {"ZA0554", "(ZA0553 * ZA0029)"},
                {"ZA0555", "(ZA0554 * ZA0031)"},
                {"ZA0556", "(ZA0555 * U1)"},
                {"ZA0557", "(-1 * (ZA0556))"},
                {"ZA0558", "(ZA0032 * ZA0001)"},
                {"ZA0559", "(ZA0558 * ZA0029)"},
                {"ZA0560", "(ZA0559 * ZA0031)"},
                {"ZA0561", "(divsint(dt(multsint(ZA0560))) - dt(ZA0560))"},
                {"ZA0562", "(-1 * (ZA0561))"},
                {"ZA0563", "(ZA0064 * ZA0240)"},
                {"ZA0564", "(ZA0563 * BTH)"},
                {"ZA0565", "(ZA0564 * BH)"},
                {"ZA0566", "(ZA0565 * ZA0029)"},
                {"ZA0567", "(ZA0566 * ZA0031)"},
                {"ZA0568", "(2 * (ZA0567))"},
                {"ZA0569", "(-1 * (ZA0568))"},
                {"ZA0570", "(ZA0044 * BTH)"},
                {"ZA0571", "(ZA0570 * ZA0029)"},
                {"ZA0572", "(ZA0571 * ZA0031)"},
                {"ZA0573", "(divsint(dt(multsint(ZA0572))) - dt(ZA0572))"},
                {"ZA0574", "((1 / 2) * (ZA0573))"},
                {"ZA0575", "(-1 * (ZA0574))"},
                {"ZA0576", "(ZA0134 * BH)"},
                {"ZA0577", "(ZA0576 * ZA0029)"},
                {"ZA0578", "(ZA0577 * ZA0031)"},
                {"ZA0579", "(ZA0578 * U1)"},
                {"ZA0580", "(ZA0161 * P1)"},
                {"ZA0581", "(ZA0580 * BH)"},
                {"ZA0582", "(ZA0581 * ZA0029)"},
                {"ZA0583", "(ZA0582 * ZA0031)"},
                {"ZA0584", "(ZA0161 * BH)"},
                {"ZA0585", "(ZA0584 * ZA0029)"},
                {"ZA0586", "(ZA0585 * ZA0031)"},
                {"ZA0587", "(ZA0586 * U1)"},
                {"ZA0588", "(4 * (ZA0587))"},
                {"ZA0589", "(-1 * (ZA0588))"},
                {"ZA0590", "(ZA0064 * B2)"},
                {"ZA0591", "(ZA0590 * BH)"},
                {"ZA0592", "(ZA0591 * ZA0029)"},
                {"ZA0593", "(ZA0592 * ZA0031)"},
                {"ZA0594", "(divsint(dt(multsint(ZA0593))) - dt(ZA0593))"},
                {"ZA0595", "((1 / 2) * (ZA0594))"},
                {"ZA0596", "(-1 * (ZA0595))"},
                {"ZA0597", "(ZA0167 * P1)"},
                {"ZA0598", "(ZA0597 * BH)"},
                {"ZA0599", "(ZA0598 * ZA0029)"},
                {"ZA0600", "(ZA0599 * ZA0031)"},
                {"ZA0601", "(divsint(dt(multsint(ZA0600))) - dt(ZA0600))"},
                {"ZA0602", "((1 / 2) * (ZA0601))"},
                {"ZA0603", "(ZA0167 * BH)"},
                {"ZA0604", "(ZA0603 * ZA0029)"},
                {"ZA0605", "(ZA0604 * ZA0031)"},
                {"ZA0606", "(ZA0605 * U1)"},
                {"ZA0607", "(divsint(dt(multsint(ZA0606))) - dt(ZA0606))"},
                {"ZA0608", "(-1 * (ZA0607))"},
                {"ZA0609", "((-1 * ((1 / 2))) + ZA0367)"},
                {"ZA0610", "(ZA0609 + ZA0488)"},
                {"ZA0611", "(ZA0610 + ZA0495)"},
                {"ZA0612", "(ZA0611 + ZA0502)"},
                {"ZA0613", "(ZA0612 + ZA0505)"},
                {"ZA0614", "(ZA0613 + ZA0507)"},
                {"ZA0615", "(ZA0614 + ZA0511)"},
                {"ZA0616", "(ZA0615 + ZA0515)"},
                {"ZA0617", "(ZA0616 + ZA0521)"},
                {"ZA0618", "(ZA0617 + ZA0524)"},
                {"ZA0619", "(ZA0618 + ZA0527)"},
                {"ZA0620", "(ZA0619 + ZA0532)"},
                {"ZA0621", "(ZA0620 + ZA0538)"},
                {"ZA0622", "(ZA0621 + ZA0541)"},
                {"ZA0623", "(ZA0622 + ZA0545)"},
                {"ZA0624", "(ZA0623 + ZA0547)"},
                {"ZA0625", "(ZA0624 + ZA0552)"},
                {"ZA0626", "(ZA0625 + ZA0557)"},
                {"ZA0627", "(ZA0626 + ZA0562)"},
                {"ZA0628", "(ZA0627 + ZA0569)"},
                {"ZA0629", "(ZA0628 + ZA0575)"},
                {"ZA0630", "(ZA0629 + ZA0579)"},
                {"ZA0631", "(ZA0630 + ZA0583)"},
                {"ZA0632", "(ZA0631 + ZA0589)"},
                {"ZA0633", "(ZA0632 + ZA0596)"},
                {"ZA0634", "(ZA0633 + ZA0602)"},
                {"ZA0635", "(ZA0634 + ZA0608)"},
                {"ZA0636", "(ZA0635 + ZA0309)"},
            };
            return D;
        }

        /// ⚠ READ, not merely fetched (round 108): the value only
        /// exists once operator()(Index) has been called.
        inline void read_def(Kadath::System_of_eqs& syst,
                             const Kadath::Space& sp,
                             const char* nm, int dmin, int dmax)
        {
            for (int d = dmin; d <= dmax; d++) {
                const Kadath::Val_domain& v =
                    syst.give_val_def_scalar_domain(nm, d);
                Kadath::Index ix(sp.get_domain(d)->get_nbr_points());
                do { (void)v(ix); } while (ix.inc());
            }
        }
    } // namespace throatth_detail

    /// The six rows, with the tau mode count each projects onto.
    inline const std::vector<std::pair<const char*, const char*>>&
    throatth_rows()
    {
        static const std::vector<std::pair<const char*, const char*>> R = {
            {"TEQTW", "ZA0218"},   // E_Q, nt-1 modes
            {"TESHR", "ZA0301"},   // E_sh^r, nt modes
            {"TESHT", "ZA0412"},   // E_sh^th, nt-2 modes
            {"TEPHI", "ZA0450"},   // E_Phi, nt modes
            {"TEQFN", "ZA0487"},   // E_q, nt modes
            {"TESIG", "ZA0636"},   // E_sigma, nt modes
        };
        return R;
    }

    /// mode count per row, in the same order, as a function of nt.
    inline int throatth_row_modes(int k, int nt)
    {
        static const int OFF[6] = {-1, 0, -2, 0, 0, 0};
        return nt + OFF[k];
    }

    /// The sin(theta) weight each row carries, distributed over its
    /// monomials at emission time.  Recorded so a caller cannot
    /// apply it twice, and so the projection basis is checkable.
    inline int throatth_row_weight(int k)
    {
        static const int W[6] = {0, 0, 1, 0, 0, 0};
        return W[k];
    }

    /**
     * The twelve amplitude defs, built from the matching unknowns.
     *
     * G%02d are the grade-0 unknowns and H%02d the grade-1 ones, laid out
     * PS PH QF BR BT QB with nt, nt, nt, nt, nt-2, nt-1 modes -- the same
     * order and the same counts the probe registers them in.  A%s%02d is
     * the PURE ANGULAR profile of that family, with no radial factor: these
     * rows live at one radius, so a radial factor would be a constant
     * folded into an unknown that already carries it.
     */
    inline std::vector<std::pair<std::string, std::string>>
    throatth_amp_defs(int nt)
    {
        const int NCE = nt, NSE = nt - 2, NCO = nt - 1;
        const int cnt[6] = {NCE, NCE, NCE, NCE, NSE, NCO};
        static const char* FN[6] = {"PS", "PH", "QF", "BR", "BT", "QB"};
        static const char* AP[6] = {"ACE", "ACE", "ACE", "ACE", "ASE", "ACO"};
        int tot = 0;
        for (int q = 0; q < 6; q++) tot += cnt[q];
        if (tot != 6 * nt - 3)
            throw std::runtime_error("throatth: the matching block is not 6nt-3");
        std::vector<std::pair<std::string, std::string>> out;
        char b[64];
        int g = 0;
        for (int q = 0; q < 6; q++) {
            std::string s0, s1;
            for (int j = 0; j < cnt[q]; j++) {
                std::snprintf(b, sizeof b, "%sG%02d * %s%02d",
                              j ? " + " : "", g + j, AP[q], j);
                s0 += b;
                std::snprintf(b, sizeof b, "%sH%02d * %s%02d",
                              j ? " + " : "", g + j, AP[q], j);
                s1 += b;
            }
            g += cnt[q];
            out.push_back({std::string("S") + FN[q], "(" + s0 + ")"});
            out.push_back({std::string("H") + FN[q], "(" + s1 + ")"});
        }
        out.push_back({"UH", "((1 / 2) * (log(SPS)))"});
        out.push_back({"PHH", "SPH"});
        out.push_back({"QH", "SQF"});
        out.push_back({"BH", "SBR"});
        out.push_back({"BTH", "SBT"});
        out.push_back({"QBH", "SQB"});
        out.push_back({"U1", "(HPS / (2 * SPS))"});
        out.push_back({"P1", "(HPH / SPH)"});
        out.push_back({"Q1F", "HQF"});
        out.push_back({"B1", "(HBR / SBR)"});
        out.push_back({"B2", "HBT"});
        out.push_back({"QB1", "HQB"});
        return out;
    }

    /// Register the amplitude defs, then the def table, then the
    /// six rows -- in topological order, each READ as it lands.
    inline void throatth_register(Kadath::System_of_eqs& syst,
                                  const Kadath::Space& sp,
                                  int nt, int dmin, int dmax,
                                  bool read_defs = true)
    {
        // ⚠ EVERY add_def NAMES ITSELF ON FAILURE.  Kadath throws
        // "bad valence in definition" with no indication of WHICH,
        // and 611 defs is not a thing to bisect by hand.
        const bool trace = (std::getenv("THROATTH_TRACE") != 0);
        const char* mx = std::getenv("THROATTH_MAX");
        const int maxdef = mx ? std::atoi(mx) : -1;
        int ndone = 0;
        auto one = [&](const std::string& nm, const std::string& tx) {
            // ⚠ A SEGFAULT NAMES NOTHING, and an exception message
            // that names the def is no help when the failure is a
            // signal.  THROATTH_TRACE=1 prints each name BEFORE it
            // is parsed and flushes, so the last line is the one.
            if (maxdef >= 0 && ndone >= maxdef) return;
            ndone++;
            if (trace) { std::printf("throatth %s\n", nm.c_str()); std::fflush(stdout); }
            try {
                // ⚠ PER DOMAIN, NOT add_def(name).  The one-argument
                // overload loops dom_min..dom_max, and Ope_def EVALUATES
                // its expression in the constructor -- so registering
                // these in the compact domain evaluates log(SPS) where
                // the pure-angular profiles are zero at the r = infinity
                // node, and the Term_eq comes back with a null value that
                // the valence check then dereferences.  A segfault inside
                // add_def, naming nothing.  They live at the inner face.
                for (int dd = dmin; dd <= dmax; dd++)
                    syst.add_def(dd, (nm + " = " + tx).c_str());
            } catch (const std::exception& ex) {
                throw std::runtime_error("throatth: " + nm + " = "
                    + tx + "  ->  " + ex.what());
            }
            if (read_defs)
                throatth_detail::read_def(syst, sp, nm.c_str(), dmin, dmax);
        };
        for (const auto& a : throatth_amp_defs(nt)) one(a.first, a.second);
        for (const auto& d : throatth_detail::subdefs()) one(d.name, d.def);
        if (maxdef < 0)
            for (const auto& r : throatth_rows()) one(r.first, r.second);
    }
} // namespace Trumpet
